### ISSUE TITLE
onnxruntime的gpu怎么支持？

### ISSUE THREAD

**Issue by xinsuinizhuan** [DefTruth/lite.ai.toolkit#10]

**Comment by DefTruth** [comment]
你需要额外编译GPU版本的onnxruntime的GPU版本的库哦，我这没专门测试，代码是不用改的，但链接的库需要改。  
* onnxruntime 官方编译的包在这 [onnxruntime-win-gpu-x64-1.8.1.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.8.1/onnxruntime-win-gpu-x64-1.8.1.zip
)  
有个小伙伴尝试了GPU下的测试 #9

**Comment by xinsuinizhuan** [comment]
> 
> 
> 你需要额外编译GPU版本的onnxruntime的GPU版本的库哦，我这没专门测试，代码是不用改的，但链接的库需要改。
> 
>     * onnxruntime 官方编译的包在这 [onnxruntime-win-gpu-x64-1.8.1.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.8.1/onnxruntime-win-gpu-x64-1.8.1.zip)
> 
> 
> 另外，有个小伙伴尝试了GPU下的测试 #9 ，应该是ok的
> 话说回来，现在onnxruntime竟然有官方built了，真是幸福，之前都是得build from source~ 🙃🙃🙃

这个是1.8.1的库，我们的支持吗？
另外，我之前一直是使用的onnxruntime1.6.0的库，然后，就是默认单线程跑，yolov5和yolox都是95ms左右，然后直接替换了1.7.0的库后，就变成了247ms左右，然后把线程改成了8，就又恢复到了95ms左右。

**Comment by DefTruth** [comment]
我这默认的线程数是1，你可以尝试别的线程数。
> 
> ```c++
> class LITE_EXPORTS YoloX : public BasicOrtHandler
> {
>   public:
>     explicit YoloX(const std::string &_onnx_path, unsigned int _num_threads = 1) :  // 线程数默认为1
>         BasicOrtHandler(_onnx_path, _num_threads)
>     {};
> }
> ```
> 
> 可以修改为别的线程数：
> 
> ```c++
> auto *yolox = new lite::cv::detection::YoloX(onnx_path, 8);  // 8 threads.
> ```
1.8.1的库，我还没有测过高版本的库，一般情况下这些库都是向后兼容的。你可以直接替换1.8.1的库和头文件试一下。另外需要注意的是，可能你得看一下官方说明里边对于CUDA版本的要求。希望小伙伴能尝试成功啊~

**Comment by xinsuinizhuan** [comment]
> 
> 
> 我这默认的线程数是1，你可以尝试别的线程数。
> 
> > ```c++
> > class LITE_EXPORTS YoloX : public BasicOrtHandler
> > {
> >   public:
> >     explicit YoloX(const std::string &_onnx_path, unsigned int _num_threads = 1) :  // 线程数默认为1
> >         BasicOrtHandler(_onnx_path, _num_threads)
> >     {};
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以修改为别的线程数：
> > ```c++
> > auto *yolox = new lite::cv::detection::YoloX(onnx_path, 8);  // 8 threads.
> > ```
> 
> 1.8.1的库，我还没有测过高版本的库，一般情况下这些库都是向后兼容的。你可以直接替换1.8.1的库和头文件试一下。另外需要注意的是，可能你得看一下官方说明里边对于CUDA版本的要求。希望小伙伴能尝试成功啊~

嗯嗯。刚刚下载了1.8.1的gpu的库，然后重新编译试了试，结果没啥效果，更1.7.0 cpu版本一样，甚至还不如，一张图改成了8线程后，107ms。应该是要使用gpu，是需要一个设置和变量的。

**Comment by DefTruth** [comment]
可以尝试下设置CUDAProvider, 在ort_handler.cpp中修改session_options.  
```c++  
// GPU compatiable.  尝试增加以下2句，emmm..... 我们有windows环境，其实没试过
OrtCUDAProviderOptions provider_options; // C接口
session_options.AppendExecutionProvider_CUDA(provider_options);  
// 1. session
ort_session = new Ort::Session(ort_env, onnx_path, session_options);
```

**Comment by 1VeniVediVeci1** [comment]
GPU推理需要在ort_handler的initialize_handler()里加上OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);

**Comment by 1VeniVediVeci1** [comment]
gpu除了nuget安装外，不需要额外配置环境，因为cuda在安装时已经在电脑的环境变量中添加了路径

**Comment by xinsuinizhuan** [comment]
> ```c
>  ORT_ABORT_ON_ERROR(OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0));
> ```

不对的，我加了这句话后，崩溃：
跟cuda cudnn什么的怎么匹配？
![图片](https://user-images.githubusercontent.com/40679769/127791891-910fbd68-a63f-41fb-8201-64dcc63ef40a.png)
![图片](https://user-images.githubusercontent.com/40679769/127791915-838bd885-4fab-4203-94c7-471d550db3db.png)
加了
/ GPU compatiable.  尝试增加以下2句，emmm..... 我没有windows环境，其实没试过
OrtCUDAProviderOptions provider_options; // C接口
session_options.AppendExecutionProvider_CUDA(provider_options);  
// 1. session
ort_session = new Ort::Session(ort_env, onnx_path, session_options); 

后，new Ort::Session崩溃

**Comment by DefTruth** [comment]
> > ```c
> >  ORT_ABORT_ON_ERROR(OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0));
> > ```
> 
> 不对的，我加了这句话后，崩溃：
> 跟cuda cudnn什么的怎么匹配？   


应该也不能完全说不对的，应该还是用法有些问题。我这版代码是暂时没有做GPU兼容的，应该有些地方需要你去修改。首先你需要确保你用的GPU版本的库以及对应CUDA版本是对的。 我们可以从源码来分析一下用法。在onnxruntime_c_api.cc中有一段：  
```c++  
# include "core/session/onnxruntime_c_api.h"
// ...省略一部分头文件
#ifdef USE_CUDA
#include "core/providers/cuda/cuda_provider_factory.h"
#endif
```  
可以看到 如果是GPU版本 定义了USE_CUDA 则会引入cuda_provider_factory.h. 这个头文件放的就是OrtSessionOptionsAppendExecutionProvider_CUDA的函数签名：  
```c++  
/**
 * \param device_id cuda device id, starts from zero.
 */
ORT_API_STATUS(OrtSessionOptionsAppendExecutionProvider_CUDA, _In_ OrtSessionOptions* options, int device_id);
```  
我们看到这里需要输入的是一个OrtSessionOptions指针，而并非Ort::SessionOptions. 但事实上：  
```c++  
struct SessionOptions : Base<OrtSessionOptions> {};
struct Base<const T> {
  using contained_type = const T;

  Base() = default;
  Base(const T* p) : p_{p} {
    if (!p)
      ORT_CXX_API_THROW("Invalid instance ptr", ORT_INVALID_ARGUMENT);
  }
  ~Base() = default;

  operator const T*() const { return p_; }  // 注意这里重载了T*()的类型转换函数。
// ...
}
```
由于Ort::SessionOptions重载了类型转换函数，所以可以直接使用OrtSessionOptionsAppendExecutionProvider_CUDA接口，在传参时会通过 (OrtSessionOptions*)session_options 对 session_options进行隐式转换。另一种方式就是使用C++封装了一层的接口。他们的本质上是一样的。 在onnxruntime_cxx_inline.h中：
```c++  
inline SessionOptions& SessionOptions::AppendExecutionProvider_CUDA(const OrtCUDAProviderOptions& provider_options) {
  // 这个指针p_就是 OrtSessionOptions*, OrtCUDAProviderOptions在前面的分析已经讲过了，就不重复了
  ThrowOnError(GetApi().SessionOptionsAppendExecutionProvider_CUDA(p_, &provider_options));
  return *this;
}
```  
关于Ort::Session、Ort::SessionOptions、Ort::Env的更多分析，你可以参考 #8 , 这位小伙伴贴出了一份 GPU版本的代码，你可以看下。 或者你可以把error具体的log发上来，这样我们能清楚具体发生了什么问题。至于一些环境问题，可能需要小伙伴你自己解决一下了~ good luck ~ 🙃🙃🙃

**Comment by xinsuinizhuan** [comment]
按照上面那个小伙伴说的：OrtSessionOptionsAppendExecutionProvider_CUDA这个接口没找到，没法用，
if (m_gpuIdx != -1) 
    {
        Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_CUDA(sessionOptions, m_gpuIdx));
    }

![图片](https://user-images.githubusercontent.com/40679769/127871823-c963d145-b344-4fd8-92ce-85915a38c0be.png)

**Comment by xinsuinizhuan** [comment]
我想问一下，模型导出的时候，有没有cpu和gpu之分，导出的cpu模型，gpu不能加载？

**Comment by xinsuinizhuan** [comment]
我的环境：cuda 11.3 cudnn 8.0.1.6, vs2019 onnxruntime 1.8.1 gpu版本
报错：
![图片](https://user-images.githubusercontent.com/40679769/127872781-7663a821-fba0-4080-aa64-d94093186710.png)

![图片](https://user-images.githubusercontent.com/40679769/127872738-13f21774-cdb3-486a-b0ba-09320ac48eb8.png)
帮忙看看，能不能找到点头绪？

**Comment by DefTruth** [comment]
> 我想问一下，模型导出的时候，有没有cpu和gpu之分，导出的cpu模型，gpu不能加载？

这个没有cpu和gpu区别的，都是可以用的。你现在用的是GPU版本的库和头文件吗？你直接导入这些头文件试试？onnxruntime_c_api.h已经是被包含在onnxruntime_cxx_api.h里面的， OrtSessionOptionsAppendExecutionProvider_CUDA这个C API应该能找到才对啊。你这有点奇怪  
```c++
#include <onnxruntime/core/providers/cuda/cuda_provider_factory.h>
#include <onnxruntime/core/session/onnxruntime_cxx_api.h>
```

**Comment by xinsuinizhuan** [comment]
> 
> 
> > 我想问一下，模型导出的时候，有没有cpu和gpu之分，导出的cpu模型，gpu不能加载？
> 
> 这个没有cpu和gpu区别的，都是可以用的。你现在用的是GPU版本的库和头文件吗？你直接导入这些头文件试试？onnxruntime_c_api.h已经是被包含在onnxruntime_cxx_api.h里面的， OrtSessionOptionsAppendExecutionProvider_CUDA这个C API应该能找到才对啊。你这有点奇怪
> 
> ```c++
> #include <onnxruntime/core/providers/cuda/cuda_provider_factory.h>
> #include <onnxruntime/core/session/onnxruntime_cxx_api.h>
> ```

https://github.com/microsoft/onnxruntime/releases 我是从这里下载的，这里下载的，貌似就没有cuda那个文件夹

**Comment by DefTruth** [comment]
> 我的环境：cuda 11.3 cudnn 8.0.1.6, vs2019 onnxruntime 1.8.1 gpu版本
> 帮忙看看，能不能找到点头绪？

你电脑确定是NVIDIA的显卡吗？只能是N卡哦

**Comment by xinsuinizhuan** [comment]
![图片](https://user-images.githubusercontent.com/40679769/127873953-dfe8e4f9-6099-4300-ab0e-8cf9979e9019.png)
显卡

**Comment by xinsuinizhuan** [comment]
非常感谢，可以了。哎。
头文件添加：

#include "onnxruntime_c_api.h"

#ifdef USE_CUDA
#include "cuda_provider_factory.h"
#endif

然后：
initialize_handler()中，添加：
#ifdef USE_CUDA
  //OrtCUDAProviderOptions provider_options; // C接口
  //session_options.AppendExecutionProvider_CUDA(provider_options);
  //OrtCUDAProviderOptions options;
  //options.device_id = 0;
  //options.arena_extend_strategy = 0;
  //options.cudnn_conv_algo_search = OrtCudnnConvAlgoSearch::EXHAUSTIVE;
  //options.do_copy_in_default_stream = 1;
  //session_options.AppendExecutionProvider_CUDA(options);

  OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);
#endif

![图片](https://user-images.githubusercontent.com/40679769/127874622-9d92d943-1c2d-4575-80cf-095952631eb4.png)

**Comment by DefTruth** [comment]
> > > 我想问一下，模型导出的时候，有没有cpu和gpu之分，导出的cpu模型，gpu不能加载？
> > 
> > 
> > 这个没有cpu和gpu区别的，都是可以用的。你现在用的是GPU版本的库和头文件吗？你直接导入这些头文件试试？onnxruntime_c_api.h已经是被包含在onnxruntime_cxx_api.h里面的， OrtSessionOptionsAppendExecutionProvider_CUDA这个C API应该能找到才对啊。你这有点奇怪
> > ```c++
> > #include <onnxruntime/core/providers/cuda/cuda_provider_factory.h>
> > #include <onnxruntime/core/session/onnxruntime_cxx_api.h>
> > ```
> 
> https://github.com/microsoft/onnxruntime/releases 我是从这里下载的，这里下载的，貌似就没有cuda那个文件夹

我看到是有cuda_provider_factory.h的，应该是一样。官方包里面的头文件目录结构和自己编的是不一样的。官方包里面的include是这样的。

**Comment by xinsuinizhuan** [comment]
gpu运行时间22ms：
![图片](https://user-images.githubusercontent.com/40679769/127874853-5dde5fc3-e7a9-4ae0-96ba-45d445e27e91.png)
cpu运行时间97ms

**Comment by xinsuinizhuan** [comment]
感谢。感谢。就是，其他两种方式不行，还必须就得OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);

**Comment by DefTruth** [comment]
> 非常感谢，可以了。哎。

 你太艰难了~ 哈哈 ~

**Comment by DefTruth** [comment]
> 没事，只要弄成了，再难都值得。哈哈。你可以把这一句加上了，兼容gpu。

get ~

**Comment by xinsuinizhuan** [comment]
只是，接下来，希望把yolor模型进行兼容吧

**Comment by DefTruth** [comment]
> 只是，接下来，希望把yolor模型进行兼容吧

之后看时间允不允许，平时工作也比较忙。不过这个项目应该会长期维护~

**Comment by xinsuinizhuan** [comment]
嗯。加油。希望可以整个qq群吧，这样交流起来比较方便点。

**Comment by DefTruth** [comment]
> 嗯。加油。希望可以整个qq群吧，这样交流起来比较方便点。

精力有限，暂时没有这个计划哈哈~

**Comment by xinsuinizhuan** [comment]
另外，如果模型输入，不是640*640，和是自定义数据集，coco.name，怎么修改？

**Comment by DefTruth** [comment]
> 另外，如果模型输入，不是640*640，怎么修改？

看这个issue #9 ，这里面有讨论这个问题，yolox.cpp现在兼容非方形输入，不会有问题的，你需要下载Lite.AI最新版的代码，或者直接拷贝新的[yolox.cpp](https://github.com/DefTruth/lite.ai/blob/main/ort/cv/yolox.cpp) 和 [yolox.h](https://github.com/DefTruth/lite.ai/blob/main/ort/cv/yolox.h) 替换原来的即可。

**Comment by hejian81** [comment]
> 非常感谢，可以了。哎。 头文件添加：
> 
> #include “onnxruntime_c_api.h”
> 
> #ifdef USE_CUDA #include "cuda_provider_factory.h" #endif
> 
> 然后： initialize_handler()中，添加： #ifdef USE_CUDA //OrtCUDAProviderOptions provider_options; // C接口 //session_options.AppendExecutionProvider_CUDA(provider_options); //OrtCUDAProviderOptions 选项； //options.device_id = 0; //options.arena_extend_strategy = 0; //options.cudnn_conv_algo_search = OrtCudnnConvAlgoSearch::EXHAUSTIVE; //options.do_copy_in_default_stream = 1; //session_options.AppendExecutionProvider_CUDA(options);
> 
> OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0); ＃万一
> 
> ![图片](https://user-images.githubusercontent.com/40679769/127874622-9d92d943-1c2d-4575-80cf-095952631eb4.png)

#include <cuda_provider_factory.h> 加上这个头文件找不到以下文件
![image](https://user-images.githubusercontent.com/57781813/157673142-db3c241d-2d7b-4749-8bc4-961d914bc7df.png)

**Comment by DefTruth** [comment]
> > 非常感谢，可以了。哎。 头文件添加：
> > #include “onnxruntime_c_api.h”
> > #ifdef USE_CUDA #include "cuda_provider_factory.h" #endif
> > 然后： initialize_handler()中，添加： #ifdef USE_CUDA //OrtCUDAProviderOptions provider_options; // C接口 //session_options.AppendExecutionProvider_CUDA(provider_options); //OrtCUDAProviderOptions 选项； //options.device_id = 0; //options.arena_extend_strategy = 0; //options.cudnn_conv_algo_search = OrtCudnnConvAlgoSearch::EXHAUSTIVE; //options.do_copy_in_default_stream = 1; //session_options.AppendExecutionProvider_CUDA(options);
> > OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0); ＃万一
> > ![图片](https://user-images.githubusercontent.com/40679769/127874622-9d92d943-1c2d-4575-80cf-095952631eb4.png)
> 
> #include <cuda_provider_factory.h> 加上这个头文件找不到以下文件 ![image](https://user-images.githubusercontent.com/57781813/157673142-db3c241d-2d7b-4749-8bc4-961d914bc7df.png)

最新的代码已经修复了。你可以看一下ort_config.h和ort_defs.h的代码，编译CUDA版本前，现在可以指定-D ENABLE_ONNXRUNTIME_CUDA=ON，编译GPU版本。但前提是你下载的onnxruntime库是cuda版本，以及你的设备已经配置好相关的环境。windows下的编译可以参考： 

* #207 

两个相关的头文件：

* https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/core/ort_defs.h
* https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/core/ort_config.h

**Comment by hejian81** [comment]
> > > 非常感谢，可以了。哎。 头文件添加：
> > > #include "onnxruntime_c_api.h" 
> > > #ifdef USE_CUDA #include "cuda_provider_factory.h" #endif
> > > 然后：initialize_handler()中，添加：#ifdef USE_CUDA //OrtCUDAProviderOptions // C接口 //session_options.AppendExecutionProvider_CUDA(provider_options); //OrtCUDAProviderOptions 选项； //options.device_id = 0; //options.arena_extend_strategy = 0; //options.cudnn_conv_algo_search = OrtCudnnConvAlgoSearch::EXHAUSTIVE; //options.do_copy_in_default_stream = 1; //session_options.AppendExecutionProvider_CUDA(options); 
> > > OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0); ＃万一
> > > ![图片](https://user-images.githubusercontent.com/40679769/127874622-9d92d943-1c2d-4575-80cf-095952631eb4.png)
> > 
> > 
> > #include <cuda_provider_factory.h> 加上这个头文件找不到以下文件![图片](https://user-images.githubusercontent.com/57781813/157673142-db3c241d-2d7b-4749-8bc4-961d914bc7df.png)
> 
> 最新的代码已经修复了。你可以看一下ort_config.h和ort_defs.h的代码，编译CUDA版本前，现在可以指定-D ENABLE_ONNXRUNTIME_CUDA=ON，编译GPU版本。但前提是你下载的onnxruntime库是cuda版本，以及你的设备已经配置好相关的环境。windows下的编译可以参考：
> 
> * [🔥Windows10  VS2019  CUDA 11.1 配置lite.ai.toolkit库 #207](https://github.com/DefTruth/lite.ai.toolkit/issues/207)
> 
> 两个相关的头文件：
> 
> * https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/core/ort_defs.h
> * https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/core/ort_config.h

我这边已经利用下载的二进制文件可以调用了，但是我测试了下，还是没有用到GPU，咋回事，是因为cuda环境不对吗

**Comment by hejian81** [comment]
> > > 非常感谢，可以了。哎。 头文件添加：
> > > #include “onnxruntime_c_api.h”
> > > #ifdef USE_CUDA #include "cuda_provider_factory.h" #endif
> > > 然后： initialize_handler()中，添加： #ifdef USE_CUDA //OrtCUDAProviderOptions provider_options; // C接口 //session_options.AppendExecutionProvider_CUDA(provider_options); //OrtCUDAProviderOptions 选项； //options.device_id = 0; //options.arena_extend_strategy = 0; //options.cudnn_conv_algo_search = OrtCudnnConvAlgoSearch::EXHAUSTIVE; //options.do_copy_in_default_stream = 1; //session_options.AppendExecutionProvider_CUDA(options);
> > > OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0); ＃万一
> > > ![图片](https://user-images.githubusercontent.com/40679769/127874622-9d92d943-1c2d-4575-80cf-095952631eb4.png)
> > 
> > 
> > #include <cuda_provider_factory.h> 加上这个头文件找不到以下文件 ![image](https://user-images.githubusercontent.com/57781813/157673142-db3c241d-2d7b-4749-8bc4-961d914bc7df.png)
> 
> 最新的代码已经修复了。你可以看一下ort_config.h和ort_defs.h的代码，编译CUDA版本前，现在可以指定-D ENABLE_ONNXRUNTIME_CUDA=ON，编译GPU版本。但前提是你下载的onnxruntime库是cuda版本，以及你的设备已经配置好相关的环境。windows下的编译可以参考：
> 
> * [🔥Windows10  VS2019  CUDA 11.1 配置lite.ai.toolkit库 #207](https://github.com/DefTruth/lite.ai.toolkit/issues/207)
> 
> 两个相关的头文件：
> 
> * https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/core/ort_defs.h
> * https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/core/ort_config.h

感谢，我看完了所有的回复……或多或少的帮助我解决问题啦，哈哈哈

**Comment by SonwYang** [comment]
> 

你好，请问下如果用onnxruntime-gpu的话，链接库的代码在哪里修改
