### ISSUE TITLE
求助 ubuntu下测试lite yolov5，开启onnxruntime USE_CUDA反而比不开更慢 有人遇到过吗？

### ISSUE THREAD

**Issue by zyc4me** [DefTruth/lite.ai.toolkit#102]
CUDA 10.2 
onnxruntime-gpu  1.8.1 是直接下载的编译好的

**Comment by DefTruth** [comment]
>  cuda 11, cudnn 8, linux Ubuntu 16.04, libonnxruntime gpu 1.7

换成这个配置试试？另外，可以参考这个 #97 以及 #99 ，另一个小伙伴在windows用 onnxruntime 1.8.1 gpu 似乎也有问题。有可能是CUDAExecuteProvider对应的设备号不一定是0，我这里写死了是0.  在 [lite/ort/core/ort_handler.cpp](https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/core/ort_handler.cpp) 中：  

```C++
  // GPU compatiable.
  // OrtCUDAProviderOptions provider_options;
  // session_options.AppendExecutionProvider_CUDA(provider_options);
#ifdef USE_CUDA
  OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0); // C API stable.
#endif
  // 1. session
  ort_session = new Ort::Session(ort_env, onnx_path, session_options);
```   

另外，需要手动定义宏USE_CUDA，才会启用上面这段代码。在[lite/ort/core/ort_config.h](https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/core/ort_config.h)  中

```C++
#ifndef LITE_AI_ORT_CORE_ORT_CONFIG_H
#define LITE_AI_ORT_CORE_ORT_CONFIG_H

#include "ort_defs.h"
#include "lite/lite.ai.headers.h"

#ifdef ENABLE_ONNXRUNTIME
#include "onnxruntime/core/session/onnxruntime_cxx_api.h"
/* Need to define USE_CUDA macro manually by users who want to
 * enable onnxruntime and lite.ai.toolkit with CUDA support. It
 * seems that the latest onnxruntime will no longer pre-defined the
 * USE_CUDA macro and just let the decision make by users
 * who really know the environments of running device.*/
// #define USE_CUDA
#  ifdef USE_CUDA
#include "onnxruntime/core/providers/cuda/cuda_provider_factory.h"
#  endif
#endif

namespace core {}

#endif //LITE_AI_ORT_CORE_ORT_CONFIG_H
```  
还可以参考onnxruntime的官方案例，检查一下OrtSessionOptionsAppendExecutionProvider_CUDA返回的status是否正常。  [fns_candy_style_transfer.c](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/c_cxx/fns_candy_style_transfer/fns_candy_style_transfer.c)
```C++
int enable_cuda(OrtSessionOptions* session_options) {
  // OrtCUDAProviderOptions is a C struct. C programming language doesn't have constructors/destructors.
  OrtCUDAProviderOptions o;
  // Here we use memset to initialize every field of the above data struct to zero.
  memset(&o, 0, sizeof(o));
  // But is zero a valid value for every variable? Not quite. It is not guaranteed. In the other words: does every enum
  // type contain zero? The following line can be omitted because EXHAUSTIVE is mapped to zero in onnxruntime_c_api.h.
  o.cudnn_conv_algo_search = EXHAUSTIVE;
  o.gpu_mem_limit = SIZE_MAX;
  OrtStatus* onnx_status = g_ort->SessionOptionsAppendExecutionProvider_CUDA(session_options, &o);
  if (onnx_status != NULL) {
    const char* msg = g_ort->GetErrorMessage(onnx_status);
    fprintf(stderr, "%s\n", msg);
    g_ort->ReleaseStatus(onnx_status);
    return -1;
  }
  return 0;
}
```  
希望对你有用~ 
补充：不太确定我用的1.7的头文件是否适配1.8.1，也可以试一下更换1.8.1的头文件，需要你自己需改合适的头文件路径。因为官方pre-built的提供头文件比较少。我这边是从源码自己编译的，包含了所有的头文件，并且头文件目录结构和官方提供的不太一样。

**Comment by DefTruth** [comment]
关于 lite_yolov5 的测试方式，因为用的是 yolov5s.onnx ，本身是小模型，在CPU是可以跑挺快的，如果切换成GPU，不能只跑我写的demo，我写的只是单次推理。GPU的首次推理通常比较慢，之后会变快。你需要参考test_lite_yolov5.cpp的例子，在 new 完 lite::cv::detection::YoloV5 后，跑个循环测一下，忽略首次推理。

**Comment by zyc4me** [comment]
> 关于 lite_yolov5 的测试方式，因为用的是 yolov5s.onnx ，本身是小模型，在CPU是可以跑挺快的，如果切换成GPU，不能只跑我写的demo，我写的只是单次推理。GPU的首次推理通常比较慢，之后会变快。你需要参考test_lite_yolov5.cpp的例子，在 new 完 lite::cv::detection::YoloV5 后，跑个循环测一下，忽略首次推理。

是的，先空跑10轮 再测试一次时间就快很多了👍
