### ISSUE TITLE
Linux compile

### ISSUE THREAD

**Issue by LuoYingzhao** [DefTruth/lite.ai.toolkit#104]
If I want to build the LiteAiToolKit on Linux to do inference with MNN, can I choose the MNN as backend? Or must select ONNXRuntime as backend.

**Comment by DefTruth** [comment]
Try ONNXRuntime + MNN with `-DENABLE_MNN=ON`, the ONNXRuntime is needed by default. Currently, lite.ai.toolkit is not support for building the lib without ONNXRuntime because only a few models are currently supported by MNN、NCNN or TNN. I will consider adding such compilation support in the future.

**Comment by LuoYingzhao** [comment]
I build with ONNXRuntime+MNN，and shared libs in ./onnxruntime and ./MNN has been replaced by offical build.
When build by build.sh, some error occurred. 
Looks like it want to find onnxruntime&MNN from /usr.
Could you please provide some advice?

Error attached below.(xxxxxx replace the long root path of this project)

Preparing  /xxxxxx/build/lite.ai.toolkit/lib ... done!
Preparing  /xxxxxx/build/lite.ai.toolkit/bin ... done!
Installing opencv2 headers to /xxxxxx/build/lite.ai.toolkit/opencv2 ... done!
Installing onnxruntime headers to/xxxxxx/build/lite.ai.toolkit/include/onnxruntime ... done!
Installing MNN headers to /xxxxxx/build/lite.ai.toolkit/include/MNN ... done!
/usr/bin/ld: cannot find -lonnxruntime
/usr/bin/ld: cannot find -lMNN
collect2: error: ld returned 1 exit status
CMakeFiles/lite.ai.toolkit.dir/build.make:1317: recipe for target 'lite.ai.toolkit/lib/liblite.ai.toolkit.so.0.1.0' failed
make[2]: *** [lite.ai.toolkit/lib/liblite.ai.toolkit.so.0.1.0] Error 1
CMakeFiles/Makefile2:254: recipe for target 'CMakeFiles/lite.ai.toolkit.dir/all' failed
make[1]: *** [CMakeFiles/lite.ai.toolkit.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DefTruth** [comment]
### Linux and Windows.  

⚠️ *Lite.AI.ToolKit* is not directly support Linux and Windows now. For Linux and Windows, you need to build or download(if have official builts) the shared libs of *OpenCV*、*ONNXRuntime* and any other Engines(like MNN, NCNN, TNN) firstly, then put the headers into the specific directories or just let these directories unchange(use the headers offer by this repo, the header file of the dependent library of this project is directly copied from the corresponding official library). However, the dynamic libraries under different operating systems need to be recompiled or downloaded. MacOS users can directly use the dynamic libraries of each dependent library provided by this project:   
* *lite.ai.toolkit/opencv2*  
  ```shell
    cp -r you-path-to-downloaded-or-built-opencv/include/opencv4/opencv2 lite.ai.toolkit/opencv2
  ```
* *lite.ai.toolkit/onnxruntime*  
  ```shell
    cp -r you-path-to-downloaded-or-built-onnxruntime/include/onnxruntime lite.ai.toolkit/onnxruntime
  ```
* *lite.ai.toolkit/MNN*  
  ```shell
    cp -r you-path-to-downloaded-or-built-MNN/include/MNN lite.ai.toolkit/MNN
  ```
* *lite.ai.toolkit/ncnn*   
  ```shell
    cp -r you-path-to-downloaded-or-built-ncnn/include/ncnn lite.ai.toolkit/ncnn
  ```
* *lite.ai.toolkit/tnn*   
  ```shell
    cp -r you-path-to-downloaded-or-built-TNN/include/tnn lite.ai.toolkit/tnn
  ```

and put the libs into *lite.ai.toolkit/lib* directory. Please reference the build-docs[<sup>1</sup>](#lite.ai.toolkit-1) for *third_party*.   
* *lite.ai.toolkit/lib*  
  ```shell
    cp you-path-to-downloaded-or-built-opencv/lib/*opencv* lite.ai.toolkit/lib
    cp you-path-to-downloaded-or-built-onnxruntime/lib/*onnxruntime* lite.ai.toolkit/lib
    cp you-path-to-downloaded-or-built-MNN/lib/*MNN* lite.ai.toolkit/lib
    cp you-path-to-downloaded-or-built-ncnn/lib/*ncnn* lite.ai.toolkit/lib
    cp you-path-to-downloaded-or-built-TNN/lib/*TNN* lite.ai.toolkit/lib
  ```
you should copy the shared libs to `your/path/to/lite.ai.toolkit/lib`
