### ISSUE TITLE
请问有没有一个单独的yolox tnn的demo，这个工程混在一起有点搞不懂

### ISSUE THREAD

**Issue by TD-wzw** [DefTruth/lite.ai.toolkit#112]

**Comment by DefTruth** [comment]
@TD-wzw 你可以参考以下这几个C++文件改成你需要的，我这里把自己感兴趣的模型捏在了一起，应该不会单独再整一个小工程。
* [tnn_yolox_v0.1.1.h](https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/tnn/cv/tnn_yolox_v0.1.1.h)
* [tnn_yolox_v0.1.1.cpp](https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/tnn/cv/tnn_yolox_v0.1.1.cpp)
* [tnn_handler.cpp](https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/tnn/core/tnn_handler.cpp)
* [tnn_handler.h](https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/tnn/core/tnn_handler.h)

或者看一下这个应用示例：https://github.com/DefTruth/yolox.lite.ai.toolkit  
good luck ~
