### ISSUE TITLE
onnxruntime推理，支持批量图片推理吗？

### ISSUE THREAD

**Issue by xinsuinizhuan** [DefTruth/lite.ai.toolkit#113]
就是推理时，可以一次多张图像推理？

**Comment by DefTruth** [comment]
onnxruntime是支持的，但是在pytorch转onnx文件是需要指定bacth_size为动态维度。我这里转换是用的是静态维度bacth_size固定为1. 所以动态维度的onnx文件需要你自己去转换，应该可以查到比较多资料。
