### ISSUE TITLE
导出的onnxruntime模型能支持图片size动态输入吗

### ISSUE THREAD

**Issue by GarenLancaster** [DefTruth/lite.ai.toolkit#116]
看了下subpixle的超分，它只能固定输入输出，那不是失去超分的意义吗 （鸢尾花新手求解）

**Comment by DefTruth** [comment]
@GarenLancaster 
1. onnxruntime是支持图片动态维度输入的，但要在pytorch转onnx文件时指定动态维度，比如我这个仓库的DeepLabV3。不过我这大部分模型在转换时处理成了静态维度。
2. 关于SubPixelCNN，是的，这里是先捏了个例子。超分这个模块还没添加比较好的模型。固定的输入输出意义不大，后面应该会换掉。

**Comment by GarenLancaster** [comment]
好滴 谢谢
