### ISSUE TITLE
建议添加 scrfd face detection

### ISSUE THREAD

**Issue by zhongwenkun886** [DefTruth/lite.ai.toolkit#120]
https://github.com/deepinsight/insightface/tree/master/detection/scrfd
一个综合性能非常好的人脸检测模型，建议能添加进来，目前Github上已有ncnn和onnx版本。
https://github.com/ppogg/onnx-scrfd-flask
https://github.com/nihui/ncnn-android-scrfd

**Comment by DefTruth** [comment]
LGTM

**Comment by 205418367** [comment]
scrfd人脸检测不如百度的blazeface-fpn-ssh

**Comment by DefTruth** [comment]
已经增加
