### ISSUE TITLE
音频网络

### ISSUE THREAD

**Issue by DickyQi** [DefTruth/lite.ai.toolkit#123]
经常使用音频应用，不知是否可以添加些音频相关的网络，比如spleeter等，或是语音识别，变声类的网络。音频也是一个很大的领域啊

**Comment by DefTruth** [comment]
刚开始确实是有这样的计划。。。但是后来发现一个人的精力实在是比较有限的，只能先关注自己比较感兴趣的领域了(CV)。其实你可以考虑基于这个toolkit的框架去捏你自己感兴趣的语音模型，可能我短期内都没有时间去整理语音的模型了。以后的话？看缘分吧，缘分到了可能会玩一下语音的算法。
