### ISSUE TITLE
RVM项目，.onnx转.mnn格式

### ISSUE THREAD

**Issue by niujindacidian** [DefTruth/lite.ai.toolkit#124]
您好，想请教您一些问题。.onnx转.mnn的过程中，激活函数hardswish是怎么转过去的。
我自己转出来的激活函数是关于RELU6的一堆东西，整个mnn文件结构比在您官网下载的要复杂。

**Comment by DefTruth** [comment]
hardswish可以看这个讨论：https://github.com/PeterL1n/RobustVideoMatting/issues/47
另外就是我修改了比较多东西，比如不转动态维度，而是静态维度。不同input_size转不同的模型。我是用自己转换的静态onnx文件来转mnn，并且用onnxsim过了一遍。

**Comment by niujindacidian** [comment]
.onnx我转出来了，修改为静态维度，固定了input_size大小，激活函数可以转成HardSigmoid，跟您官网结构一样。想请问您在转mnn的过程中，有修改什么东西吗，因为我转出来的.mnn格式结构复杂，激活函数是用RELU6表示的。麻烦您了。

**Comment by DefTruth** [comment]
你要不直接用我仓库的onnx文件转mnn试一下？我用的是最新的mnn-1.2.0的Converter，在Mac下转的，没特别修改什么东西。就是把onnx先用onnxsim先过一遍，再转mnn
