### ISSUE TITLE
请教ssrnet  年龄识别问题

### ISSUE THREAD

**Issue by 205418367** [DefTruth/lite.ai.toolkit#125]
我用了你的代码mnn_ssrnet.cpp 测试，发现年龄识别不准确。
我测试的过程：
    1、人脸检测
    2、人脸对齐
    3、年龄识别
请教测试过程需要注意什么呢？

**Comment by DefTruth** [comment]
1. 可以看下原作者的仓库，我转换的是这个模型：https://github.com/oukohou/SSR_Net_Pytorch
2. 年龄估计一般是有>5岁的平均误差的，真实年龄一般就连让人去识别也很难准确。所以你可以多测一些图片取平均误差看看。
3. 侧脸、低头、抬头等情况会误差变大；开源数据小孩子年龄段很少，因此小孩子年龄误差会变大。
