### ISSUE TITLE
rvm ncnn 网络没有输出

### ISSUE THREAD

**Issue by DickyQi** [DefTruth/lite.ai.toolkit#138]
编译lite.ai Mac版本， 打开ENABLE_NCNN， 测试lite_rvm ncnn分支（模型rvm_mobilenetv3_fp32-480-480-opt已复制到目录中）
ncnn初始化输出
@"Input: src: shape: c=0 h=0 w=0\r\n"
@"Input: r1i: shape: c=0 h=0 w=0\r\n"
@"Input: r2i: shape: c=0 h=0 w=0\r\n"
@"Input: r3i: shape: c=0 h=0 w=0\r\n"
@"Input: r4i: shape: c=0 h=0 w=0\r\n"
@"=============== Output-Dims ==============\r\n"
@"Output: fgr: shape: c=0 h=0 w=0\r\n"
@"Output: pha: shape: c=0 h=0 w=0\r\n"
@"========================================\r\n"

程序异常在
// fast assign & channel transpose(CHW->HWC).
  cv::Mat rmat(input_height, input_width, CV_32FC1, fgr_ptr);

原因是
extractor.extract("fgr", fgr);
  extractor.extract("pha", pha);
网络没有输出

**Comment by DefTruth** [comment]
是的，ncnn的版本还有点问题，还没时间调试清楚。出来的是nullptr。你可以先用 MNN/TNN/ONNXRuntime的版本。
