### ISSUE TITLE
更新一下utils::offset_nms？感觉精度损失，这里有关系。

### ISSUE THREAD

**Issue by xinsuinizhuan** [DefTruth/lite.ai.toolkit#142]
// reference: https://github.com/ultralytics/yolov5/blob/master/utils/general.py
void ortcv::utils::offset_nms(std::vector<DetReuslltInfo> &input, std::vector<DetReuslltInfo> &output,
                              float iou_threshold, unsigned int topk)；

https://github.com/ultralytics/yolov5/blob/master/utils/general.py这里跟您的已经不一样了

**Comment by DefTruth** [comment]
逻辑上是一样的，应该没有问题。都是利用offset将不同类别先拉开足够多的距离，然后再按照score排序后的顺序进行nms，相当于不同的类别分开做nms。你可以尝试一下按照自己的思路改改看看效果会不会变好哈~

**Comment by DefTruth** [comment]
另外对于YOLOv5和YOLOX的最新版本，前后处理和之前的不一样了。你可以尝试下对应的c++实现：  
* https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/cv/yolov5_v6.0.cpp  
* https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/cv/yolox_v0.1.1.cpp

**Comment by xinsuinizhuan** [comment]
yolov5_v6.0.cpp版本我看和之前的一样呢，yolox_v0.1.1.cpp的话，是不一样了

**Comment by DefTruth** [comment]
> yolov5_v6.0.cpp版本我看和之前的一样呢，yolox_v0.1.1.cpp的话，是不一样了

yolov5_v6.0如果你用ncnn推就不一样，因为新版本去掉了Focus，新旧版本的推理代码不能兼容。用ONNXRuntime/MNN/TNN的话，推理代码是可以一样的
