### ISSUE TITLE
Yolox reasoning is inaccurate

### ISSUE THREAD

**Issue by xinyujituan** [DefTruth/lite.ai.toolkit#149]
Yolox reasoning is inaccurate. Different from py test results, the accuracy is almost 0

It should be generate_ There's a problem with bboxes

**Comment by DefTruth** [comment]
it's weird, all is well in my test. can you  should me your tested images?  
my results is:   
![test_lite_yolox_v0 1 1_1](https://user-images.githubusercontent.com/31974251/147586268-ca3f5631-badb-4610-9acf-ebb3fe691980.jpg)
![test_lite_yolox_v0 1 1_2](https://user-images.githubusercontent.com/31974251/147586276-608bd2e6-1837-434f-a89e-56a679cbd9ac.jpg)

**Comment by xinyujituan** [comment]
Here is my prediction code and results
std::string onnx_path = "E:/C++/lite.ai.toolkit-main/build/lite.ai.toolkit/lib/Release/yolox_s.onnx";
	std::string test_img_path = "E:/C++/lite.ai.toolkit-main/build/lite.ai.toolkit/lib/Release/1.bmp";
	std::string save_img_path = "E:/C++/lite.ai.toolkit-main/build/lite.ai.toolkit/lib/Release/save.jpg";

	// 1. Test Default Engine ONNXRuntime
	lite::cv::detection::YoloX* yolox = new lite::cv::detection::YoloX(onnx_path); // default

	std::vector<lite::types::Boxf> detected_boxes;
	cv::Mat img_bgr = cv::imread(test_img_path);
	yolox->detect(img_bgr, detected_boxes);

	lite::utils::draw_boxes_inplace(img_bgr, detected_boxes);

	cv::imwrite(save_img_path, img_bgr);
![1](https://user-images.githubusercontent.com/53806323/147589718-8f36d157-0f74-4dfe-8ba2-9d3588682a75.jpg)

	std::cout << "Default Version Detected Boxes Num: " << detected_boxes.size() << std::endl;

	delete yolox
![save](https://user-images.githubusercontent.com/53806323/147589700-1d45a6e2-732d-4813-8916-24f9cd73e751.jpg)
;

**Comment by xinyujituan** [comment]
python predict image
![test_lite_deeplabv3_resnet101](https://user-images.githubusercontent.com/53806323/147591214-743ed07d-5440-40eb-ac2e-d42afe99350b.png)

**Comment by DefTruth** [comment]
不知道是不是bmp格式的原因，你试一下png或jpg? 另外就是，可以看一下我写的关于YOLOX的例子，测了一批图片，结果也挺正常。等我空闲了，再测测你这个样例。  
https://github.com/DefTruth/YOLOX.lite.ai.toolkit

**Comment by xinyujituan** [comment]
我试了你的例子确实是可以，但是我从yolox的github上下载了他们的onnx模型，包括我自己下载原生的yolox模型转onnx后发现识别都有问题，只有你例子里的yolox_s.onnx可以正常识别,不知道是什么问题,我对比了模型的大小和标签数量等等都是一致的

**Comment by DefTruth** [comment]
那我知道了，因为新版本的YOLOX的前处理和旧版本的不一样了，官方README有说明，你需要用0.1.1版本的C++实现：  
https://github.com/DefTruth/lite.ai.toolkit/blob/main/examples/lite/cv/test_lite_yolox_v0.1.1.cpp

**Comment by xinyujituan** [comment]
感谢耐心解答，有没有qq群之类的可以讨论的地方呢，想向您多学习学习

**Comment by DefTruth** [comment]
可能暂时不弄qq群了，平时工作比较忙，没时间管理qq群了。可以提issue，会尽量回答哈~

**Comment by xinyujituan** [comment]
您整合的模型里要在有个多字符模型的网络就更加完美了，请问哪些多字符模型网络比较好用呢

**Comment by DefTruth** [comment]
哈哈，有这个计划，但看时间是否允许。
