### ISSUE TITLE
VS015 编译报错

### ISSUE THREAD

**Issue by xinsuinizhuan** [DefTruth/lite.ai.toolkit#15]
![图片](https://user-images.githubusercontent.com/40679769/128603035-f2d735de-1a49-407a-9ca2-731d3eb99f9b.png)
vs2019时正常，但是，项目需要vs2015，改成VS015活，编译报错，貌似对模板什么的支持不好

**Comment by DefTruth** [comment]
> vs2019时正常，但是，项目需要vs2015，改成VS015活，编译报错，貌似对模板什么的支持不好

这个可能没办法，你可以考虑单独拎出其中你需要的模型重新实现下推理，可以参考下我这的代码。Lite.AI包含的模型太多了，比较建议你单独使用你需要的那部分。另外就是，onnxruntime c++的API也是需要编译器支持模板特性的，不支持的话会有点麻烦。我记得vs2015和vs2019是ABI兼容的，可以考虑下用vs2019编好库拿到vs2015用。具体我也没试过。。。

**Comment by xinsuinizhuan** [comment]
好的。没办法的话，只能是，vs2019编译后库，让2015调用
