### ISSUE TITLE
windows10 vs2019 编译错误

### ISSUE THREAD

**Issue by xinsuinizhuan** [DefTruth/lite.ai.toolkit#16]
![图片](https://user-images.githubusercontent.com/40679769/128635382-cd053a85-5b94-46a6-bec4-855e645a6dc1.png)

**Comment by DefTruth** [comment]
有一处宏判断写错了。确实有处宏判断写错了。在ort_handler.cpp原来的代码：  
```c++  
#ifdef LITEHUB_WIN32
#include "ort_utils.h"
#endif
```  
需要修改成  
```c++  
#ifdef LITE_WIN32
#include "ort_utils.h"
#endif
```
