### ISSUE TITLE
关于实时检测

### ISSUE THREAD

**Issue by FL77N** [DefTruth/lite.ai.toolkit#162]
你好，目标检测方面可以直接外接摄像头或者进行实时目标检测吗？

**Comment by DefTruth** [comment]
hello~ 👋 
* 关于实时检测：这个toolkit里面捏的很多模型其实都是实时的，比如YOLOX-S，NanoDet，YOLOv5-S等等
* 关于外接摄像头：我这里没有专门写摄像头的处理，这个处理很偏具体的业务逻辑了。toolkit只是提供了一套可以直接使用的API，目前只是做了PC端。工作之余，时间比较有限。你可以编译完之后，直接用这里的API，接入到你自己的具体的逻辑。

**Comment by FL77N** [comment]
> hello~ 👋
> 
> * 关于实时检测：这个toolkit里面捏的很多模型其实都是实时的，比如YOLOX-S，NanoDet，YOLOv5-S等等
> * 关于外接摄像头：我这里没有专门写摄像头的处理，这个处理很偏具体的业务逻辑了。toolkit只是提供了一套可以直接使用的API，目前只是做了PC端。工作之余，时间比较有限。你可以编译完之后，直接用这里的API，接入到你自己的具体的逻辑。

了解了，谢谢回答！
