### ISSUE TITLE
帮忙Windows配环境，有偿

### ISSUE THREAD

**Issue by meifannao** [DefTruth/lite.ai.toolkit#179]
QQ:2809514115

**Comment by meifannao** [comment]
只要能让抠图的程序跑起来就行

**Comment by xinsuinizhuan** [comment]
我给你配置

**Comment by xinsuinizhuan** [comment]
微信：xinsuinizhuan

**Comment by meifannao** [comment]
> 我给你配置

大概多少

**Comment by Baiyuetribe** [comment]
同求windows初始化教程，去年10月份请求作者添加Windows入门教程，至今没有消息。[https://github.com/DefTruth/lite.ai.toolkit/issues/48](https://github.com/DefTruth/lite.ai.toolkit/issues/48)

**Comment by DefTruth** [comment]
> 

emmmm...., 可能是因为太穷了，手上没有趁手的windows电脑🤐。现阶段的话，可以参考README.md的windows配置部分的文档，结合CMake和CLion来配。其实有去捏win/linux/mac的预编译库的打算，但是不确定什么时候会有时间完善，平时太卷啦....现在有些算法模块也不够完善，所以是先计划完善算法模块，之后才会来完善兼容各个操作系统的问题。快看RoadMap，今年一定会捏好（说的我自己都信了）。这个项目还是会持续更新的，但是可能会按照我自己的规划来弄。

**Comment by DefTruth** [comment]
@xinsuinizhuan  👋Hi~大佬要不要考虑来写个Windows下的lite.ai.toolkit入门教程（写在docs/build/Window.zh.md），成为contributor哈，不妨考虑提个PR啥的到dev分支，我会merge进lite.ai.toolkit 🤔
