### ISSUE TITLE
模型都是怎么转换的？

### ISSUE THREAD

**Issue by xinsuinizhuan** [DefTruth/lite.ai.toolkit#18]
我这边自定义训练的一个resnet数据模型是pt模型，怎么转onnx模型呢，我在您链接的vison里面没找到怎么转换？

**Comment by DefTruth** [comment]
转换成onnx你可以查一下pytorch的接口，以及对onnx的opset的支持程度。这是已经是另外一个话题了，涉及的知识点很多，比如遇到不支持的算子怎么办，如何修改转换后的onnx节点，pytorch的张量直接内存操作和onnx算子的行为是否能对齐等等。这些需要你自己查一下，每个模型都不一样，遇到的问题也会不一样。每个模型的转换的细节处理都是不一样的，这个项目不计划把这些杂乱的代码放上来。
