### ISSUE TITLE
关于 Linux 中 onnxruntime 的编译

### ISSUE THREAD

**Issue by FL77N** [DefTruth/lite.ai.toolkit#182]
您好！我想请教一下，想在 Linux 中运行您工作中的 onnx 模型，需要：
* 在类似 vscode 之类中编译吗？还是直接可以在终端完成检测、抠图，就好了
* 除了 opencv 需要安装其他依赖吗
* 因为看到您的仓库中有 onnx，所以可以直接用吗？还是得像您 readme 中说的自己去官方下载

**Comment by DefTruth** [comment]
linux下的话需要重新编译onnxruntime或者去官方网站下载，请参考README中的说明。也可以查看一下相关的issue:
* https://github.com/DefTruth/lite.ai.toolkit/issues/97
* https://github.com/DefTruth/lite.ai.toolkit/issues/104
* https://github.com/DefTruth/lite.ai.toolkit/issues/81
* https://github.com/DefTruth/lite.ai.toolkit/issues/27

**Comment by FL77N** [comment]
> linux下的话需要重新编译onnxruntime或者去官方网站下载，请参考README中的说明。也可以查看一下相关的issue:

谢谢您的回答，我是安装 cpu 版的 onnxruntime。
