### ISSUE TITLE
抠图模型在Inter I7 CPU上运行FPS大概多少

### ISSUE THREAD

**Issue by meifannao** [DefTruth/lite.ai.toolkit#183]

**Comment by meifannao** [comment]
在 intel i7 CPU 处理一个 1080p 视频的时间是否能不高于 50ms/帧，  15fps

**Comment by DefTruth** [comment]
可以看原论文的实验结果，只有在GPU上跑才能实时，cpu会比较慢。  
* https://github.com/PeterL1n/RobustVideoMatting 
![image](https://user-images.githubusercontent.com/31974251/153007617-5e8e69fe-2db3-4b21-ac3b-51a95c578458.png)

**Comment by amcones** [comment]
请问有实现张量的并行传输吗

**Comment by DefTruth** [comment]
> 请问有实现张量的并行传输吗

python的版本有实现，可以看我fork的分支里的inference_onnx.py:  
* https://github.com/DefTruth/RobustVideoMatting/blob/onnx/inference_onnx.py  

以及我在RVM里的PR:  
* https://github.com/PeterL1n/RobustVideoMatting/pull/27

**Comment by meifannao** [comment]
> 可以看原论文的实验结果，只有在GPU上跑才能实时，cpu会比较慢。
> 
> * https://github.com/PeterL1n/RobustVideoMatting
>   ![image](https://user-images.githubusercontent.com/31974251/153007617-5e8e69fe-2db3-4b21-ac3b-51a95c578458.png)

问一个这个抠图程序把环境部署好了可以直接在Visual Studio上生成exe文件吗
还是说只提供了demo，生成exe的话还需要自己编写
