### ISSUE TITLE
compile problem for ARM

### ISSUE THREAD

**Issue by MyraBaba** [DefTruth/lite.ai.toolkit#188]
Hi,

in Mac Os x all is good. compiling succesfully . But raspi iot ubunutu has issue.

gives : 

`/usr/bin/ld: /home/pi/Projects/lite.ai.toolkit/build/lite.ai.toolkit/lib/liblite.ai.toolkit.so: undefined reference to `cv::Mat::Mat()'
`
also liblite examples same error. 

`undefined reference to `cv::Mat::Mat()'`

when I look liblite.ai.toolkit.so with ldd: it linked to the opencv.

`ldd  /home/pi/Projects/lite.ai.toolkit/build/lite.ai.toolkit/lib/liblite.ai.toolkit.so
	linux-vdso.so.1 (0x0000007f9e95c000)
	libopencv_video.so.4.5 => /usr/local/lib/libopencv_video.so.4.5 (0x0000007f9e762000)
	libopencv_videoio.so.4.5 => /usr/local/lib/libopencv_videoio.so.4.5 (0x0000007f9e6e9000)
	libonnxruntime.so.1.11.0 => /home/pi/USBA/onnxruntime/build/Linux/RelWithDebInfo/libonnxruntime.so.1.11.0 (0x0000007f9dd30000)
	libopencv_calib3d.so.4.5 => /usr/local/lib/libopencv_calib3d.so.4.5 (0x0000007f9db7b000)
	libopencv_features2d.so.4.5 => /usr/local/lib/libopencv_features2d.so.4.5 (0x0000007f9dabc000)
	libopencv_flann.so.4.5 => /usr/local/lib/libopencv_flann.so.4.5 (0x0000007f9da50000)
	libopencv_imgcodecs.so.4.5 => /usr/local/lib/libopencv_imgcodecs.so.4.5 (0x0000007f9d7e6000)
	libopencv_imgproc.so.4.5 => /usr/local/lib/libopencv_imgproc.so.4.5 (0x0000007f9d3b2000)
	libopencv_core.so.4.5 => /usr/local/lib/libopencv_core.so.4.5 (0x0000007f9d036000)
	libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007f9ce8d000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f9cdd0000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007f9cdac000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f9cc3a000)
	libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007f9cc26000)
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f9cbf7000)
	libdc1394.so.22 => /usr/lib/aarch64-linux-gnu/libdc1394.so.22 (0x0000007f9cb75000)
	libgstreamer-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstreamer-1.0.so.0 (0x0000007f9ca20000)
	libgobject-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgobject-2.0.so.0 (0x0000007f9c9b9000)
	libglib-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0 (0x0000007f9c886000)
	libgstapp-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstapp-1.0.so.0 (0x0000007f9c867000)
	libgstriff-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstriff-1.0.so.0 (0x0000007f9c849000)
	libgstpbutils-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstpbutils-1.0.so.0 (0x0000007f9c7ff000)
	libavcodec.so.58 => /usr/lib/aarch64-linux-gnu/libavcodec.so.58 (0x0000007f9b507000)
	libavformat.so.58 => /usr/lib/aarch64-linux-gnu/libavformat.so.58 (0x0000007f9b2a1000)
	libavutil.so.56 => /usr/lib/aarch64-linux-gnu/libavutil.so.56 (0x0000007f9b217000)
	libswscale.so.5 => /usr/lib/aarch64-linux-gnu/libswscale.so.5 (0x0000007f9b196000)
	librt.so.1 => /lib/aarch64-linux-gnu/librt.so.1 (0x0000007f9b17e000)
	libjpeg.so.62 => /usr/lib/aarch64-linux-gnu/libjpeg.so.62 (0x0000007f9b12e000)
	libpng16.so.16 => /usr/lib/aarch64-linux-gnu/libpng16.so.16 (0x0000007f9b0e9000)
	libtiff.so.5 => /usr/lib/aarch64-linux-gnu/libtiff.so.5 (0x0000007f9b05e000)
	libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000007f9b031000)
	libtbb.so => /usr/local/lib/libtbb.so (0x0000007f9aff1000)
	/lib/ld-linux-aarch64.so.1 (0x0000007f9e92e000)
	libraw1394.so.11 => /usr/lib/aarch64-linux-gnu/libraw1394.so.11 (0x0000007f9afd4000)
	libusb-1.0.so.0 => /lib/aarch64-linux-gnu/libusb-1.0.so.0 (0x0000007f9afad000)
	libgmodule-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgmodule-2.0.so.0 (0x0000007f9af97000)
	libffi.so.6 => /usr/lib/aarch64-linux-gnu/libffi.so.6 (0x0000007f9af7f000)
	libpcre.so.3 => /lib/aarch64-linux-gnu/libpcre.so.3 (0x0000007f9af0c000)
	libgstbase-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstbase-1.0.so.0 (0x0000007f9ae8c000)
	libgstaudio-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstaudio-1.0.so.0 (0x0000007f9ae0d000)
	libgsttag-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgsttag-1.0.so.0 (0x0000007f9adc1000)
	libgstvideo-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libgstvideo-1.0.so.0 (0x0000007f9ad1f000)
	libswresample.so.3 => /usr/lib/aarch64-linux-gnu/libswresample.so.3 (0x0000007f9acf8000)
	libvpx.so.5 => /usr/lib/aarch64-linux-gnu/libvpx.so.5 (0x0000007f9ab54000)
	libwebpmux.so.3 => /usr/lib/aarch64-linux-gnu/libwebpmux.so.3 (0x0000007f9ab3b000)
	libwebp.so.6 => /usr/lib/aarch64-linux-gnu/libwebp.so.6 (0x0000007f9aae1000)
	liblzma.so.5 => /lib/aarch64-linux-gnu/liblzma.so.5 (0x0000007f9aaac000)
	librsvg-2.so.2 => /usr/lib/aarch64-linux-gnu/librsvg-2.so.2 (0x0000007f9a5f2000)
	libcairo.so.2 => /usr/lib/aarch64-linux-gnu/libcairo.so.2 (0x0000007f9a4d3000)
	libzvbi.so.0 => /usr/lib/aarch64-linux-gnu/libzvbi.so.0 (0x0000007f9a439000)
	libsnappy.so.1 => /usr/lib/aarch64-linux-gnu/libsnappy.so.1 (0x0000007f9a420000)
	libaom.so.0 => /usr/lib/aarch64-linux-gnu/libaom.so.0 (0x0000007f9a0f8000)
	libcodec2.so.0.8.1 => /usr/lib/aarch64-linux-gnu/libcodec2.so.0.8.1 (0x0000007f9a087000)
	libgsm.so.1 => /usr/lib/aarch64-linux-gnu/libgsm.so.1 (0x0000007f9a06a000)
	libmp3lame.so.0 => /usr/lib/aarch64-linux-gnu/libmp3lame.so.0 (0x0000007f99fed000)
	libopenjp2.so.7 => /usr/lib/aarch64-linux-gnu/libopenjp2.so.7 (0x0000007f99f8d000)
	libopus.so.0 => /usr/lib/aarch64-linux-gnu/libopus.so.0 (0x0000007f99f2f000)
	libshine.so.3 => /usr/lib/aarch64-linux-gnu/libshine.so.3 (0x0000007f99f15000)
	libspeex.so.1 => /usr/lib/aarch64-linux-gnu/libspeex.so.1 (0x0000007f99ef0000)
	libtheoraenc.so.1 => /usr/lib/aarch64-linux-gnu/libtheoraenc.so.1 (0x0000007f99ead000)
	libtheoradec.so.1 => /usr/lib/aarch64-linux-gnu/libtheoradec.so.1 (0x0000007f99e84000)
	libtwolame.so.0 => /usr/lib/aarch64-linux-gnu/libtwolame.so.0 (0x0000007f99e54000)
	libvorbis.so.0 => /usr/lib/aarch64-linux-gnu/libvorbis.so.0 (0x0000007f99e1b000)
	libvorbisenc.so.2 => /usr/lib/aarch64-linux-gnu/libvorbisenc.so.2 (0x0000007f99d6b000)
	libwavpack.so.1 => /usr/lib/aarch64-linux-gnu/libwavpack.so.1 (0x0000007f99d36000)
	libx264.so.155 => /usr/lib/aarch64-linux-gnu/libx264.so.155 (0x0000007f99ae4000)
	libx265.so.165 => /usr/lib/aarch64-linux-gnu/libx265.so.165 (0x0000007f99838000)
	libxvidcore.so.4 => /usr/lib/aarch64-linux-gnu/libxvidcore.so.4 (0x0000007f99750000)
	libva.so.2 => /usr/lib/aarch64-linux-gnu/libva.so.2 (0x0000007f9971f000)
	libxml2.so.2 => /usr/lib/aarch64-linux-gnu/libxml2.so.2 (0x0000007f9956f000)
	libbz2.so.1.0 => /lib/aarch64-linux-gnu/libbz2.so.1.0 (0x0000007f9954b000)
	libgme.so.0 => /usr/lib/aarch64-linux-gnu/libgme.so.0 (0x0000007f994f5000)
	libopenmpt.so.0 => /usr/lib/aarch64-linux-gnu/libopenmpt.so.0 (0x0000007f9931c000)
	libchromaprint.so.1 => /usr/lib/aarch64-linux-gnu/libchromaprint.so.1 (0x0000007f992f9000)
	libbluray.so.2 => /usr/lib/aarch64-linux-gnu/libbluray.so.2 (0x0000007f9929e000)
	libgnutls.so.30 => /usr/lib/aarch64-linux-gnu/libgnutls.so.30 (0x0000007f990ca000)
	libssh-gcrypt.so.4 => /usr/lib/aarch64-linux-gnu/libssh-gcrypt.so.4 (0x0000007f99039000)
	libva-drm.so.2 => /usr/lib/aarch64-linux-gnu/libva-drm.so.2 (0x0000007f99026000)
	libva-x11.so.2 => /usr/lib/aarch64-linux-gnu/libva-x11.so.2 (0x0000007f99010000)
	libvdpau.so.1 => /usr/lib/aarch64-linux-gnu/libvdpau.so.1 (0x0000007f98ffc000)
	libX11.so.6 => /usr/lib/aarch64-linux-gnu/libX11.so.6 (0x0000007f98eb2000)
	libdrm.so.2 => /usr/lib/aarch64-linux-gnu/libdrm.so.2 (0x0000007f98e90000)
	libzstd.so.1 => /usr/lib/aarch64-linux-gnu/libzstd.so.1 (0x0000007f98df7000)
	libjbig.so.0 => /usr/lib/aarch64-linux-gnu/libjbig.so.0 (0x0000007f98dda000)
	libudev.so.1 => /lib/aarch64-linux-gnu/libudev.so.1 (0x0000007f98da6000)
	liborc-0.4.so.0 => /usr/lib/aarch64-linux-gnu/liborc-0.4.so.0 (0x0000007f98d17000)
	libsoxr.so.0 => /usr/lib/aarch64-linux-gnu/libsoxr.so.0 (0x0000007f98cb5000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x0000007f98c7e000)
	libgio-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgio-2.0.so.0 (0x0000007f98a9e000)
	libpangocairo-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libpangocairo-1.0.so.0 (0x0000007f98a80000)
	libpangoft2-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libpangoft2-1.0.so.0 (0x0000007f98a5a000)
	libpango-1.0.so.0 => /usr/lib/aarch64-linux-gnu/libpango-1.0.so.0 (0x0000007f98a01000)
	libfontconfig.so.1 => /usr/lib/aarch64-linux-gnu/libfontconfig.so.1 (0x0000007f989aa000)
	libcroco-0.6.so.3 => /usr/lib/aarch64-linux-gnu/libcroco-0.6.so.3 (0x0000007f9895e000)
	libpixman-1.so.0 => /usr/lib/aarch64-linux-gnu/libpixman-1.so.0 (0x0000007f988ee000)
	libfreetype.so.6 => /usr/lib/aarch64-linux-gnu/libfreetype.so.6 (0x0000007f9882f000)
	libxcb-shm.so.0 => /usr/lib/aarch64-linux-gnu/libxcb-shm.so.0 (0x0000007f9881b000)
	libxcb.so.1 => /usr/lib/aarch64-linux-gnu/libxcb.so.1 (0x0000007f987e4000)
	libxcb-render.so.0 => /usr/lib/aarch64-linux-gnu/libxcb-render.so.0 (0x0000007f987c5000)
	libXrender.so.1 => /usr/lib/aarch64-linux-gnu/libXrender.so.1 (0x0000007f987ac000)
	libXext.so.6 => /usr/lib/aarch64-linux-gnu/libXext.so.6 (0x0000007f9878c000)
	libogg.so.0 => /usr/lib/aarch64-linux-gnu/libogg.so.0 (0x0000007f98774000)
	libnuma.so.1 => /usr/lib/aarch64-linux-gnu/libnuma.so.1 (0x0000007f98754000)
	libicui18n.so.63 => /usr/lib/aarch64-linux-gnu/libicui18n.so.63 (0x0000007f9847f000)
	libicuuc.so.63 => /usr/lib/aarch64-linux-gnu/libicuuc.so.63 (0x0000007f982a4000)
	libicudata.so.63 => /usr/lib/aarch64-linux-gnu/libicudata.so.63 (0x0000007f968a6000)
	libmpg123.so.0 => /usr/lib/aarch64-linux-gnu/libmpg123.so.0 (0x0000007f96847000)
	libvorbisfile.so.3 => /usr/lib/aarch64-linux-gnu/libvorbisfile.so.3 (0x0000007f9682e000)
	libp11-kit.so.0 => /usr/lib/aarch64-linux-gnu/libp11-kit.so.0 (0x0000007f966e6000)
	libidn2.so.0 => /usr/lib/aarch64-linux-gnu/libidn2.so.0 (0x0000007f966b9000)
	libunistring.so.2 => /usr/lib/aarch64-linux-gnu/libunistring.so.2 (0x0000007f96533000)
	libtasn1.so.6 => /usr/lib/aarch64-linux-gnu/libtasn1.so.6 (0x0000007f96512000)
	libnettle.so.6 => /usr/lib/aarch64-linux-gnu/libnettle.so.6 (0x0000007f964cb000)
	libhogweed.so.4 => /usr/lib/aarch64-linux-gnu/libhogweed.so.4 (0x0000007f96484000)
	libgmp.so.10 => /usr/lib/aarch64-linux-gnu/libgmp.so.10 (0x0000007f963fa000)
	libgcrypt.so.20 => /lib/aarch64-linux-gnu/libgcrypt.so.20 (0x0000007f9632d000)
	libgssapi_krb5.so.2 => /usr/lib/aarch64-linux-gnu/libgssapi_krb5.so.2 (0x0000007f962d4000)
	libXfixes.so.3 => /usr/lib/aarch64-linux-gnu/libXfixes.so.3 (0x0000007f962be000)
	libgomp.so.1 => /usr/lib/aarch64-linux-gnu/libgomp.so.1 (0x0000007f96282000)
	libmount.so.1 => /lib/aarch64-linux-gnu/libmount.so.1 (0x0000007f96210000)
	libselinux.so.1 => /lib/aarch64-linux-gnu/libselinux.so.1 (0x0000007f961dc000)
	libresolv.so.2 => /lib/aarch64-linux-gnu/libresolv.so.2 (0x0000007f961b6000)
	libharfbuzz.so.0 => /usr/lib/aarch64-linux-gnu/libharfbuzz.so.0 (0x0000007f960b8000)
	libthai.so.0 => /usr/lib/aarch64-linux-gnu/libthai.so.0 (0x0000007f9609f000)
	libfribidi.so.0 => /usr/lib/aarch64-linux-gnu/libfribidi.so.0 (0x0000007f96072000)
	libexpat.so.1 => /lib/aarch64-linux-gnu/libexpat.so.1 (0x0000007f96033000)
	libuuid.so.1 => /lib/aarch64-linux-gnu/libuuid.so.1 (0x0000007f9601b000)
	libXau.so.6 => /usr/lib/aarch64-linux-gnu/libXau.so.6 (0x0000007f96008000)
	libXdmcp.so.6 => /usr/lib/aarch64-linux-gnu/libXdmcp.so.6 (0x0000007f95ff2000)
	libgpg-error.so.0 => /lib/aarch64-linux-gnu/libgpg-error.so.0 (0x0000007f95fc0000)
	libkrb5.so.3 => /usr/lib/aarch64-linux-gnu/libkrb5.so.3 (0x0000007f95ed5000)
	libk5crypto.so.3 => /usr/lib/aarch64-linux-gnu/libk5crypto.so.3 (0x0000007f95e93000)
	libcom_err.so.2 => /lib/aarch64-linux-gnu/libcom_err.so.2 (0x0000007f95e7f000)
	libkrb5support.so.0 => /usr/lib/aarch64-linux-gnu/libkrb5support.so.0 (0x0000007f95e62000)
	libkeyutils.so.1 => /lib/aarch64-linux-gnu/libkeyutils.so.1 (0x0000007f95e4d000)
	libblkid.so.1 => /lib/aarch64-linux-gnu/libblkid.so.1 (0x0000007f95de6000)
	libgraphite2.so.3 => /usr/lib/aarch64-linux-gnu/libgraphite2.so.3 (0x0000007f95db3000)
	libdatrie.so.1 => /usr/lib/aarch64-linux-gnu/libdatrie.so.1 (0x0000007f95d9b000)
	libbsd.so.0 => /usr/lib/aarch64-linux-gnu/libbsd.so.0 (0x0000007f95d75000)
`

i couldn solve 

Best

**Comment by DefTruth** [comment]
Not sure if it's compatible with ARM,  but linux should be ok. by the way, lite.ai.toolkit need to link opencv and inference engines(onnxruntime or others) at runtime, so you have to make sure lite.ai.toolkit can link to these libraries.

**Comment by MyraBaba** [comment]
Same error for ubuntu 20 intel cpu .

**Comment by DefTruth** [comment]
@MyraBaba 
*  https://github.com/DefTruth/lite.ai.toolkit/issues/97  

I hope it helps~

**Comment by MyraBaba** [comment]
I check the shared lib and looks all fine but same error: 
```

readelf -d  /home/pi/Projects/lite.ai.toolkit/build/lite.ai.toolkit/lib/liblite.ai.toolkit.so | head -20 

Dynamic section at offset 0x72c3a8 contains 36 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_core.so.4.5]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_imgproc.so.4.5]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_imgcodecs.so.4.5]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_video.so.4.5]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_videoio.so.4.5]
 0x0000000000000001 (NEEDED)             Shared library: [libonnxruntime.so.1.11.0]
 0x0000000000000001 (NEEDED)             Shared library: [libMNN.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [liblite.ai.toolkit.so.0.1.0]
 0x000000000000001d (RUNPATH)            Library runpath: [/home/pi/Projects/lite.ai.toolkit/lib:/home/pi/USBA/onnxruntime/build/Linux/RelWithDebInfo]
 0x000000000000000c (INIT)               0xf5f00
 0x000000000000000d (FINI)               0x654c14
 0x0000000000000019 (INIT_ARRAY)         0x71f6e8
 0x000000000000001b (INIT_ARRAYSZ)       1600 (bytes)

```

runpath has all opencv needed ones.

no success

**Comment by FL77N** [comment]
@MyraBaba In linux, I copied the files from opencv-4.x\include\opencv2 which is downloaded to the corresponding directory, built opencv and did it again for the files in the built opencv/lib. [The installation of opencv in linux](https://www.jianshu.com/p/f54b0fc13811) may help you~

**Comment by MyraBaba** [comment]
I will try this also. 

Isn’t it the same to use find_package( OpenCV REQUIRED ) which we can use at setu_opencv_cmake located at cmake folder ? Did you test it ?

Let you know the results for copying to include folders.



find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
target_link_libraries( …... ${OpenCV_LIBS} )


Best

**Comment by MyraBaba** [comment]
@DefTruth 

Dear friend write here because it not and general issue.

Meanwhile I would love to hear your experience regarding to realtime face recognition from video feed .
detection faces 25/fps means 25 faces every second for one person. If there is 3 person it means 3x25 = 75 faces per second has to be feature extracted and search through db. But there is 3 person.

what would be the best performant solution to lower faces number to send to recognition server for process ?

lowering fps could cause the miss the desired face chip or on the detection process using the low feature (12) to understan if the still same person and not to send to recognition server ?

What would be your suggestion ? Consider there will be 10 camera and a lot of faces coming { ie : 3 person per camera and 25 fps = 750 faces per second to hand } . Meanwhile recognition server re-detect face for better alignment .

Would love to hear your opinion and suggestion

Best
