### ISSUE TITLE
linux下编译出现onnxruntime问题

### ISSUE THREAD

**Issue by jun214384468** [DefTruth/lite.ai.toolkit#193]
你好,我在编译的时候出现/usr/bin/ld: cannot find -lonnxruntime

[  2%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/nanodet_plus.cpp.o
[  2%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/rexnet_emotion7.cpp.o
[  3%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/colorizer.cpp.o
[  5%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/utils.cpp.o
[  6%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/fast_style_transfer.cpp.o
[  7%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/resnext.cpp.o
[  8%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/tiny_yolov4_voc.cpp.o
[ 10%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/resnet.cpp.o
[ 11%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/densenet.cpp.o
[ 12%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/pose_robust_face.cpp.o
[ 13%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/yolov4.cpp.o
[ 15%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/efficient_emotion7.cpp.o
[ 16%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/scaled_yolov4.cpp.o
[ 17%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/efficientdet.cpp.o
[ 18%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/facenet.cpp.o
[ 20%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/mobile_emotion7.cpp.o
[ 21%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/yolov5_v6.0.cpp.o
[ 22%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/cava_ghost_arcface.cpp.o
[ 23%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/ultraface.cpp.o
[ 25%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/focal_arcface.cpp.o
[ 26%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/mobile_facenet.cpp.o
[ 27%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/pfld.cpp.o
[ 28%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/ssrnet.cpp.o
[ 30%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/efficientnet_lite4.cpp.o
[ 31%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/yolop.cpp.o
[ 32%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/nanodet_efficientnet_lite.cpp.o
[ 33%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/ssd.cpp.o
[ 35%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/gender_googlenet.cpp.o
[ 36%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/fcn_resnet101.cpp.o
[ 37%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/glint_cosface.cpp.o
[ 38%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/glint_arcface.cpp.o
[ 40%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/vgg16_age.cpp.o
[ 41%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/efficient_emotion8.cpp.o
[ 42%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/efficientdet_d8.cpp.o
[ 43%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/yolox.cpp.o
[ 45%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/deeplabv3_resnet101.cpp.o
[ 46%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/shufflenetv2.cpp.o
[ 47%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/emotion_ferplus.cpp.o
[ 48%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/yolov5.cpp.o
[ 50%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/pfld68.cpp.o
[ 51%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/tencent_curricular_face.cpp.o
[ 52%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/yolox_v0.1.1.cpp.o
[ 53%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/center_loss_face.cpp.o
[ 55%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/faceboxes.cpp.o
[ 56%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/tiny_yolov3.cpp.o
[ 57%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/ssd_mobilenetv1.cpp.o
[ 58%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/nanodet.cpp.o
[ 60%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/hardnet.cpp.o
[ 61%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/mobilenetv2_68.cpp.o
[ 62%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/tencent_cifp_face.cpp.o
[ 63%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/ibnnet.cpp.o
[ 65%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/age_googlenet.cpp.o
[ 66%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/vgg16_gender.cpp.o
[ 67%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/sphere_face.cpp.o
[ 68%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/glint_partial_fc.cpp.o
[ 70%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/cava_combined_face.cpp.o
[ 71%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/mg_matting.cpp.o
[ 72%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/fsanet.cpp.o
[ 73%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/face_landmarks_1000.cpp.o
[ 75%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/yolov3.cpp.o
[ 76%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/tiny_yolov4_coco.cpp.o
[ 77%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/scrfd.cpp.o
[ 78%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/efficientdet_d7.cpp.o
[ 80%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/naive_pose_robust_face.cpp.o
[ 81%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/mobilenetv2_se_68.cpp.o
[ 82%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/yolor.cpp.o
[ 83%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/mobilese_focal_face.cpp.o
[ 85%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/retinaface.cpp.o
[ 86%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/subpixel_cnn.cpp.o
[ 87%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/mobilenetv2.cpp.o
[ 88%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/ghostnet.cpp.o
[ 90%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/yolo5face.cpp.o
[ 91%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/focal_asia_arcface.cpp.o
[ 92%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/rvm.cpp.o
[ 93%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/cv/pfld98.cpp.o
[ 95%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/core/ort_handler.cpp.o
[ 96%] Building CXX object CMakeFiles/lite.ai.toolkit.dir/lite/ort/core/ort_utils.cpp.o
[ 97%] Linking CXX shared library lite.ai.toolkit/lib/liblite.ai.toolkit.so
Preparing  /home/ai/PycharmProjects/lite.ai.toolkit/build/lite.ai.toolkit/lib ... done!
Preparing  /home/ai/PycharmProjects/lite.ai.toolkit/build/lite.ai.toolkit/bin ... done!
Installing opencv2 headers to /home/ai/PycharmProjects/lite.ai.toolkit/build/lite.ai.toolkit/opencv2 ... done!
Installing onnxruntime headers to /home/ai/PycharmProjects/lite.ai.toolkit/build/lite.ai.toolkit/include/onnxruntime ... done!
/usr/bin/ld: cannot find -lonnxruntime
collect2: error: ld returned 1 exit status
CMakeFiles/lite.ai.toolkit.dir/build.make:2070: recipe for target 'lite.ai.toolkit/lib/liblite.ai.toolkit.so.0.1.0' failed
make[2]: *** [lite.ai.toolkit/lib/liblite.ai.toolkit.so.0.1.0] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/lite.ai.toolkit.dir/all' failed
make[1]: *** [CMakeFiles/lite.ai.toolkit.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DefTruth** [comment]
> 我通过pip install onnxruntime 安装的cpu版本的onnx

pip安装的是python的啊，lite.ai.toolkit需要依赖的是c++的onnxruntime和opencv，可以看看README.md的Linux编译文档，以及参考：  
* #185

**Comment by jun214384468** [comment]
> ip安装的是python的啊，lite.ai.toolkit需要依赖的是c++的onnxruntime和opencv，可以看看README.md的Linux编译文档，以及参考：

谢谢您的指点, 对我有极大的帮助
