### ISSUE TITLE
windows下CPU运行RVM模型抠图程序出现视频被拉长的问题

### ISSUE THREAD

**Issue by Xzavierlovescoding** [DefTruth/lite.ai.toolkit#194]
![image](https://user-images.githubusercontent.com/78554364/153863715-51dd87b3-a0df-449a-82d8-cfbd1f63b5ce.png)
从上往下依次是用原作者给出的inference.py推理出的结果、用lite.ai.toolkit的rvm推理出的结果和原视频素材
后来我又推理了几个也是出现被拉长的情况，总长变成了9s导致不同步，而且因为是使用CPU推理，速度很慢，这个6s的视频要推理78s
![image](https://user-images.githubusercontent.com/78554364/153865025-8a6fbc1c-2195-45b4-ae6b-d1f6c9771119.png)
另一个视频素材推理前后叠加效果不同步
请问一下有解决办法吗QAQ
（小白一枚，Windows环境下编译出错，于是把原工具箱中的RVM相关的部分拿出来改完报错可以跑通了，但是有这两个问题）
运行速度参考：之前用python源码中的inference_speed.py测速得到的fps为19.67
![OB_`MHJ{8N N$T{15@I%Y5](https://user-images.githubusercontent.com/78554364/153864634-ca4914d7-a289-46e9-bcad-d43e05114538.png)

**Comment by DefTruth** [comment]
@Xzavierlovescoding detect_video有个帧率的参数，我设置默认fps是25，如果你的视频帧率高于25，输出的视频会比输入的时间长。你要设置成和你视频一致的帧率。另外就是，能否匹配不能按时间算，要按帧数算，帧数一致就能匹配上。  
```c++
     /**
     * Video Matting Using RVM(https://github.com/PeterL1n/RobustVideoMatting)
     * @param video_path: eg. xxx/xxx/input.mp4
     * @param output_path: eg. xxx/xxx/output.mp4
     * @param contents: vector of MattingContent to catch the detected results.
     * @param save_contents: false by default, whether to save MattingContent.
     * @param downsample_ratio: 0.25 by default.
     * See https://github.com/PeterL1n/RobustVideoMatting/blob/master/documentation/inference_zh_Hans.md
     * @param writer_fps: FPS for VideoWriter, 20 by default.
     */
    void detect_video(const std::string &video_path,
                      const std::string &output_path,
                      std::vector<types::MattingContent> &contents,
                      bool save_contents = false,
                      float downsample_ratio = 0.25f,
                      unsigned int writer_fps = 20);
```

**Comment by Xzavierlovescoding** [comment]
> 
感谢！帮大忙啦，问题解决了

**Comment by Xzavierlovescoding** [comment]
> 
另外想请教一下博主，因为我们的需求是必须使用CPU和C++来跑模型，而且对fps的要求要达到20帧/s，请问有什么办法可以提速吗😢或者说，有没有其他适用于CPU的抠图模型呢

**Comment by DefTruth** [comment]
@Xzavierlovescoding 
* 1. 可以尝试一下用MNN版本的模型，这里的MNN版本是用的静态维度，ONNX是动态维度，输入图片分辨率越高耗时越多。关于如何将RVM转静态ONNX->MNN，可以看我的示例项目[RobustVideoMatting.lite.ai.toolkit](https://github.com/DefTruth/RobustVideoMatting.lite.ai.toolkit) 里面的issue，本来也想整理一下写个文章说明的，但似乎卷忘了
* 2. 推荐一下[MODNet](https://github.com/ZHKKKe/MODNet) , 虽然我也还没集成进来，但目前看起来是开源里性能最好的。
* 3. CPU实时跑抠图够呛啊，Matting本来的难度就比分割高，细节信息很重要，一般一套模型量化压缩玩下来你模型的精度就没了，int8和float32包含的细节信息量是完全不一样的
* 4. 去关注一下[PaddleSeg](https://github.com/PaddlePaddle/PaddleSeg)，其实这个做的确实是蛮好的，无论是性能还是效果

**Comment by Xzavierlovescoding** [comment]
> 

好的！谢谢博主❤️😊
