### ISSUE TITLE
👉Windows10 build error(For Windows users)

### ISSUE THREAD

**Issue by DefTruth** [DefTruth/lite.ai.toolkit#196]
## References for Windows10 users
windows下的使用可以参考以下这几个讨论(some references for windows users)
* 👉  #6 
* 👉  #10 
* 👉  #32 
* 👉  #48 
* 👉  #39 
* 👉  #77 

另外,是win32和system32，目前lite.ai.toolkit没有考虑32位的系统。还有就是在windows下编译完之后，需要手动把依赖库都拷贝到build/lite.ai.toolkit/lib和build/lite.ai.toolkit/bin，并且检查修改下模型文件的路径，比如说路径的反斜杠之类的。(Also, for win32 and system32, currently, lite.ai.toolkit does not consider 32-bit systems. Also, after compiling under Windows, you need to manually copy the dependent libraries to build/lite.ai.toolkit/lib and build/lite.ai.toolkit/bin, and check and modify the path of the model file, for example, The backslash of the path.)

## Search issues about windows
![image](https://user-images.githubusercontent.com/31974251/154252712-1e1816b2-0a11-4ce1-88f6-9f8be44f071e.png)

**Comment by DefTruth** [comment]
Windows的用户可以先看看这里的issue

**Comment by zhanghongyong123456** [comment]
> Windows的用户可以先看看这里的issue

你好，请问大佬 ，我按照你的要求，从官方下载的编译好的各个库模块都替换了，
第一步：
![image](https://user-images.githubusercontent.com/48466610/155477283-d1a2c2af-cd04-4648-b488-033da50e6b87.png)
opencv 下载的debug 编译版本：  
![image](https://user-images.githubusercontent.com/48466610/155477824-e76ae9c5-96fe-49ff-81b3-a1c3c4777985.png)
替换项目下的opencv2
onnxruntime 采用 1.9 gpu版本，由于没有你指出的文件夹，我下载了对应的源码进行替换
![image](https://user-images.githubusercontent.com/48466610/155478201-9fc66f7b-4ee3-4ffc-be9a-46fe92790290.png)
![image](https://user-images.githubusercontent.com/48466610/155478661-0da0fa7d-6fac-4070-b715-224b6ae184e1.png)

MNN ncnn 下载源码进行编译的，源码里面可以找到对应的include（MNN）以及自己编译的debug下install里面的include（NCNN），进行替换
![image](https://user-images.githubusercontent.com/48466610/155479860-52b3c3d7-37bb-4861-8da4-08c609a2e322.png)
tnn 下载的windows编译版本，复制其下对应的include到对应的文件下
![image](https://user-images.githubusercontent.com/48466610/155480253-bc43f8ee-4d23-4b17-a352-9a639e9bd0d7.png)
第二步：lib文件替换：
![image](https://user-images.githubusercontent.com/48466610/155480432-839767bf-1735-4c57-ae7d-c5164a71049e.png)
找到opencv：发行版本debug版本
![image](https://user-images.githubusercontent.com/48466610/155480532-8f48bd21-2f1e-4fbf-86cc-fd4f8b7f3edf.png)
onnxruntime-win64-gpu-1.9.0 lib
![image](https://user-images.githubusercontent.com/48466610/155480679-9cfdc047-e0af-4f4f-8e0b-c8af9214ff37.png)
MNN 自己编译的debug 64 ：
![image](https://user-images.githubusercontent.com/48466610/155480878-333873b1-9549-4a3c-a42e-b7eab3632d60.png)
ncnn 自己编译的debug 64：
![image](https://user-images.githubusercontent.com/48466610/155481044-d4b123db-c090-4cef-aed7-9cc064d1e60b.png)
tnn windows发行版本：
![image](https://user-images.githubusercontent.com/48466610/155481229-9100597a-cdd2-48ba-a7de-d105b8111394.png)
第三步：开始编译
![image](https://user-images.githubusercontent.com/48466610/155481365-2ce63aa7-4f9b-42e5-b171-d4ffdbc8c0a3.png)
删除原有的build，新建build
cd build  
cmake \
  -DCMAKE_BUILD_TYPE=MinSizeRel \  我这里使用 debug  
  -DINCLUDE_OPENCV=ON \
  -DENABLE_MNN=OFF \
  -DENABLE_NCNN=OFF \
  -DENABLE_TNN=OFF \
使用VS2019 打开项目
![image](https://user-images.githubusercontent.com/48466610/155481959-f85f5197-0e39-4596-b27e-665c117c5136.png)
在编译时候出现这个错误：
![image](https://user-images.githubusercontent.com/48466610/155482117-90c1b36a-8707-49b7-a0b3-b48c0839e0aa.png)
![image](https://user-images.githubusercontent.com/48466610/155482162-6bfde015-8fc1-4981-847d-6a44b4e482dc.png)
我不确定这个错误是我的操作流程有误，还是其他错误，请大佬指点一下，

**Comment by DefTruth** [comment]
你试一下把所有的dll都放到lite.ai.toolkit/lib文件夹下，在vs再设置一下链接？感觉你这就是没连接到库

**Comment by zhanghongyong123456** [comment]
> 你试一下把所有的dll都放到lite.ai.toolkit/lib文件夹下，在vs再设置一下链接？感觉你这就是没连接到库
我按照你说的拷贝了所有的dll文件，请问在VS需要设置什么链接，如何设置，我没找到这个错误需要的lib，这个是最后编译成功后生成的吗，我引用的那些库都没有这个lib  ——lite.ai.toolkit.lib
LINK : fatal error LNK1181: 无法打开输入文件“..\..\lite.ai.toolkit\lib\MinSizeRel\lite.ai.toolkit.lib”
![image](https://user-images.githubusercontent.com/48466610/155637307-b490734d-5118-4c09-9b12-8bc6c3e1d9d4.png)

**Comment by DefTruth** [comment]
....我没有在vs下编译过(对vs不熟悉，用clion多)，目前能确认的是mac和linux问题不大，但windows下的编译，可能需要你看下别人怎么弄的。windows下的lib文件应该是和dll对应的符号表的文件。你看一lite.ai.toolkit的CMakeLists.txt，先把LITE_AI_BUILD_TEST关了，只编译库，不编译测试工程。先看看这个库编出来是咋样的。

**Comment by zhanghongyong123456** [comment]
> 

好的 好的，我试一下，我不确定我发的那几个步骤是否正确或者有遗漏，期待大佬的指点

**Comment by zhanghongyong123456** [comment]
> ....我没有在vs下编译过(对vs不熟悉，用clion多)，目前能确认的是mac和linux问题不大，但windows下的编译，可能需要你看下别人怎么弄的。windows下的lib文件应该是和dll对应的符号表的文件。估计最近会做一下windows下的prebuilt，但没那么快，平时要卷啊，业余时间不多😂你看一lite.ai.toolkit的CMakeLists.txt，先把LITE_AI_BUILD_TEST关了，只编译库，不编译测试工程。先看看这个库编出来是咋样的。

![image](https://user-images.githubusercontent.com/48466610/155641740-1d0f6344-060b-42cb-8cb2-b2551bde85c8.png)
我配置了opencv，但是现在的opencv 都整合到 opencv_world455d.lib或者opencv_world455.lib，没有其他所谓的分支 opencv_core.lib，我该在哪里注释这个

**Comment by Pyro1999** [comment]
> > ....我没有在vs下编译过(对vs不熟悉，用clion多)，目前能确认的是mac和linux问题不大，但windows下的编译，可能需要你看下别人怎么弄的。windows下的lib文件应该是和dll对应的符号表的文件。估计最近会做一下windows下的prebuilt，但没那么快，平时要卷啊，业余时间不多😂你看一lite.ai.toolkit的CMakeLists.txt，先把LITE_AI_BUILD_TEST关了，只编译库，不编译测试工程。先看看这个库编出来是咋样的。
> 
> ![image](https://user-images.githubusercontent.com/48466610/155641740-1d0f6344-060b-42cb-8cb2-b2551bde85c8.png) 我配置了opencv，但是现在的opencv 都整合到 opencv_world455d.lib或者opencv_world455.lib，没有其他所谓的分支 opencv_core.lib，我该在哪里注释这个

老哥你解决这个问题了嘛。。。我也想知道怎么解决这个opencv_core.lib
