### ISSUE TITLE
哪个推理框架能一次推理一个batch的数据？

### ISSUE THREAD

**Issue by zhongwenkun886** [DefTruth/lite.ai.toolkit#198]
请问下， MNN | NCNN | TNN 这几个框架，哪个可以一次推理一个batch的数据（如batch=4，即四个样本）？
谢谢。

**Comment by DefTruth** [comment]
batch推理我也比较少用。目前知道的话，onnxruntime是支持动态batch推理的，需要在torch.onnx.export的时候，指定batch为动态维度，这样在推理的时候就可以不限制batch=1了。

**Comment by zhongwenkun886** [comment]
非常感谢
