### ISSUE TITLE
有计划支持 linux 吗？

### ISSUE THREAD

**Issue by hooklife** [DefTruth/lite.ai.toolkit#2]

**Comment by DefTruth** [comment]
有这个计划，最近就会把文档和docker镜像放出来

**Comment by DefTruth** [comment]
YOLOX已经安排上了 😜

**Comment by SuperGoKong** [comment]
请问 onnxruntime 自己装好后， 从/usr/local/include/.. 覆盖工程里面的吗？

**Comment by DefTruth** [comment]
> 

可以看README的说明，建议直接使用onnxruntime官方的prebuilt，下载对应操作系统的库，解压后按照我这里README说明将头文件和库放在指定的目录下。直接应用系统安装的库我也没试过，不知道会有啥坑。
