### ISSUE TITLE
增加昆虫识别

### ISSUE THREAD

**Issue by onexuan** [DefTruth/lite.ai.toolkit#201]
https://github.com/quarrying/quarrying-insect-id

可以增加昆虫识别模型？

**Comment by DefTruth** [comment]
lgtm~

**Comment by onexuan** [comment]
看了作者更新了，但好像没有更新model下载

**Comment by DefTruth** [comment]
> 

模型还没有更新，代码也还没有合并到主分支，但可以从dev分支获取

**Comment by DefTruth** [comment]
已经上传到百度云盘

**Comment by onexuan** [comment]
好嘞，我先了解了解你的项目

**Comment by onexuan** [comment]
作者你好，https://github.com/quarrying/quarrying-insect-id/tree/master/insectid/models 昆虫分割是不是目前没有？这里有两个model，一个分割一个识别 @DefTruth

**Comment by DefTruth** [comment]
只有NCNN版本的没有detector，因为模型转换出问题了。ONNX、MNN和TNN的都有。

**Comment by onexuan** [comment]
@DefTruth 好像得直接下载model再转才行，https://github.com/quarrying/quarrying-insect-id/issues/2

**Comment by onexuan** [comment]
@DefTruth  看看我转的quarrying insect detector，能用吗 : https://pan.baidu.com/s/1fALpZtQRysCWZ2BNVYsJ8g 提取码: utqc

**Comment by DefTruth** [comment]
直接转时可以转的，但是它的detector实际上是用了Yolo的Focus层，在ncnn中是不支持的，你要手动修改param文件，这个比较麻烦，所以我这里也没有实现这个版本。如果需要用到detector的话，建议参考我这里实现的onnxruntime、mnn和tnn这几个版本，ncnn版本的目前没有计划实现。

**Comment by DefTruth** [comment]
而且输出层也必须要改，ncnn不支持5维张量，它这detector的onnx中包含了decode模块，有个5维度的张量，也是没法用的。

**Comment by onexuan** [comment]
nihui 写的focus的的修改 https://zhuanlan.zhihu.com/p/275989233 @DefTruth

**Comment by DefTruth** [comment]
这个我也知道啊🤣，但问题是这个昆虫识别的库的作者没有开源pytorch的代码啊，你要从pytorch的代码上修改一些东西重新导出onnx才能拿来转ncnn，然后才能按照教程改Focus层。没办法搞的啊，我也没这么多时间来弄这个了。建议你考虑使用onnxruntime、mnn和tnn这几个版本，ncnn版本的目前没有计划实现。这个问题我就不再回复了。

**Comment by onexuan** [comment]
明白了，谢谢耐心解释

**Comment by caomuxifeng** [comment]
> @DefTruth 看看我转的quarrying insect detector，能用吗 : https://pan.baidu.com/s/1fALpZtQRysCWZ2BNVYsJ8g 提取码: utqc

大佬，你之前上传的这个过期了，可以再上传一遍吗，麻烦啦
