### ISSUE TITLE
Mac ARM M1芯片编译报错

### ISSUE THREAD

**Issue by chenjiachengzzz** [DefTruth/lite.ai.toolkit#202]
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lite.ai.toolkit/lib/liblite.ai.toolkit.0.1.0.dylib] Error 1
make[1]: *** [CMakeFiles/lite.ai.toolkit.dir/all] Error 2
make: *** [all] Error 2

**Comment by DefTruth** [comment]
暂时直接支持M1的架构，我这里提供的预编译的依赖库不是在M1的架构下编译的。M1的需要参考Linux下的编译过程，先在M1下编译好opencv和onnxruntime，再编译lite.ai.toolkit.

**Comment by chenjiachengzzz** [comment]
> 暂时不直接支持M1的架构，我这里提供的预编译的依赖库不是在M1的架构下编译的。M1的需要参考Linux下的编译过程，先在M1下编译好opencv和onnxruntime，再编译lite.ai.toolkit
