### ISSUE TITLE
有没有win10下VS使用的教程啊，对编译不太懂

### ISSUE THREAD

**Issue by lofyol** [DefTruth/lite.ai.toolkit#205]

**Comment by lofyol** [comment]
> 正在安排，windows下的编译可以先参考：
> 
> * [👉Windows10 build error(For Windows users) #196](https://github.com/DefTruth/lite.ai.toolkit/issues/196)
> 
> 以及中文README.md的windows部分

谢谢大佬，虽然我是做CV的，但自己确实太菜了

**Comment by DefTruth** [comment]
可以先看这个教程：
* #207

**Comment by lofyol** [comment]
> 可以先看这个教程：
> 
> * [🔥Windows10  VS2019  CUDA 11.1 配置lite.ai.toolkit库 #207](https://github.com/DefTruth/lite.ai.toolkit/issues/207)

谢谢啦，如果只用onnxruntime的话，不配置ncnn、TNN那些，代码会不会报错呀

**Comment by DefTruth** [comment]
不会的，参考教程里面。如果没有ncnn这些，编译时把ENABLE_MNN、ENABLE_TNN、ENABLE_NCNN设置为OFF
