### ISSUE TITLE
🔥Windows10  VS2019  CUDA 11.1 配置lite.ai.toolkit库

### ISSUE THREAD

**Issue by zhanghongyong123456** [DefTruth/lite.ai.toolkit#207]
## 补充说明
首先，非常感谢 @zhanghongyong123456 同学这份详细的windows下配置lite.ai.toolkit 的教程~ 简直太热心啦~ 用windows的同学可以先看这份教程进行配置~ 以及以下相关issues的讨论。

## References for Windows10 users
windows下的使用可以参考以下这几个讨论(some references for windows users)
* 👉  #6 
* 👉  #10 
* 👉  #32 
* 👉  #48 
* 👉  #39 
* 👉  #77 
* 👉  #242 

另外,是win32和system32，目前lite.ai.toolkit没有考虑32位的系统。还有就是在windows下编译完之后，需要手动把依赖库都拷贝到build/lite.ai.toolkit/lib和build/lite.ai.toolkit/bin，并且检查修改下模型文件的路径，比如说路径的反斜杠之类的。(Also, for win32 and system32, currently, lite.ai.toolkit does not consider 32-bit systems. Also, after compiling under Windows, you need to manually copy the dependent libraries to build/lite.ai.toolkit/lib and build/lite.ai.toolkit/bin, and check and modify the path of the model file, for example, The backslash of the path.)

## Search issues about windows
![image](https://user-images.githubusercontent.com/31974251/154252712-1e1816b2-0a11-4ce1-88f6-9f8be44f071e.png)

------------   

# Windows10 VS2019 CUDA 11.1 配置 lite.ai.toolkit库 

## 作者: @zhanghongyong123456

以下是配置教程原文。

--------------

第一步：相关依赖库的配置：
配置：
1.1 Opencv：
按照这篇博客，下载官方编译好的库解压安装，添加环境变量；我是用 opencv 4.5.5
https://blog.csdn.net/xgocn/article/details/104170088
1.2 配置 Onnxruntime：
按照这篇博客就行操作即可：
https://blog.csdn.net/qq_44747572/article/details/121340735?spm=1001.2014.3001.5501
这里注意自己CUDA的版本号，我采用的 onnxruntime-win-x64-gpu-1.9.0官方编译版本
1.3 配置TNN
直接下载安装包解压即可 github下载即可 ：
https://github.com/Tencent/TNN/releases/tag/v0.3.0
https://github.com/Tencent/TNN/releases/download/v0.3.0/tnn-v0.3.0-windows.zip
![image](https://user-images.githubusercontent.com/48466610/155839281-4e59b880-7d6d-451b-8ab5-4d43adc8f4bb.png)
1.4 github下载源码，自己编译MNN
按照这篇博客操作即可，，可以选debug 或者release 版本（可以在同一个文件夹编译两个版本），至于是否需要切换语言，可以先编译看看是否成功，不成功再去设置语言
https://blog.csdn.net/ouyangfushu/article/details/96476245
直接打开x64 Native Tools Command Prompt for VS 2019 编译即可，博客第一步、第二步我没有进行操作，也可以成功
![image](https://user-images.githubusercontent.com/48466610/155839406-afdd3045-be1f-4939-8e0b-a51c8010c79f.png)
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..  只需要设置 Debug 或者Release 即可。后续采用release 版本
1.4 配置 ncnn，参考这个链接
https://zhuanlan.zhihu.com/p/391609325
特别注意：在配置Protobuf时候，我在一个源文件夹下先后进行Debug以及 Release编译，即使这里不出问题，后续在编译的时候也会报错，所以如果想要配置release以及debug版本，个人强烈建议在两个源文件夹下进行分别编译；同样的在后续下载NCNN源码进行debug和release版本编译时候，也要创建两个源文件分别进行分别编译。
 在编译Vulkan时候，需要配置环境变量，否则后续在编译ncnn时候需要设置  set VULKAN_SDK=C:/VulkanSDK/1.3.204.0  后面跟你VulkanSDK的安装的路径，像下图这样
![image](https://user-images.githubusercontent.com/48466610/155840170-830e61db-801b-4e26-9069-7f11850e2e19.png)
1.5 开始配置  lite.ai.toolkit 库
1.5.1拉取项目库：
![image](https://user-images.githubusercontent.com/48466610/155840294-65b256b9-09cf-426c-b27b-168a3203590b.png)
1.5.2 替换项目子库
![image](https://user-images.githubusercontent.com/48466610/155840395-daa3acc8-a319-4191-afe7-094f7c3c8604.png)
![image](https://user-images.githubusercontent.com/48466610/155840453-f8137827-d934-47af-b2de-6921bb45ff0b.png)
opencv：
![image](https://user-images.githubusercontent.com/48466610/155840502-5a16eb0d-a759-4b77-b534-b7fb77ff35ec.png)
tnn：
![image](https://user-images.githubusercontent.com/48466610/155840539-e3310ca6-1ed1-4e46-991d-b80a6b619a59.png)
onnxruntime：需要下载你自己对应版本的源码，
![image](https://user-images.githubusercontent.com/48466610/155840599-114bb941-c471-4db7-a71b-9a0293e7fbe6.png)
![image](https://user-images.githubusercontent.com/48466610/155840632-e4f104a2-f980-4462-a05c-16197bc71c06.png)
我这里使用的onnxruntime-win-x64-gpu-1.9.0，所以下载的对应的源码进行替换，
![image](https://user-images.githubusercontent.com/48466610/155840691-5aea4bbb-c5af-48c8-a093-94b9fd64e347.png)
MNN：
源码下include下的MNN文件夹
ncnn：
自己编译的build/install/include/ncnn文件夹
![M9I_`GAEVJUFF77FE6AC~9D](https://user-images.githubusercontent.com/48466610/155840970-0a4fc0e6-b55c-4606-bf6c-d17d9c97b93f.png)
1.5.3 复制子库对应的lib以及dll到源文件夹：
![image](https://user-images.githubusercontent.com/48466610/155840961-b4b836e7-6aed-4a3e-a7d0-e182a0849f47.png)
这个将lite.ai.toolkit/lib文件夹下，（这里我第一次没有windows子文件夹，我忘记是我删除了还是后更新的，后面发现有子文件夹，我就在lib文件下复制了一份lib及dll库，他对应的子文件夹windows也复制了一份）
opencv：
![image](https://user-images.githubusercontent.com/48466610/155841140-e1ad93f6-016e-4ec1-b056-10eb138b25d8.png)
![image](https://user-images.githubusercontent.com/48466610/155841148-d7eead15-0ebc-47ff-b964-b1cc5cb7abc8.png)
tnn：
![image](https://user-images.githubusercontent.com/48466610/155841172-b2a38a52-f91d-4d59-b8ff-9deb04fd89ef.png)
![image](https://user-images.githubusercontent.com/48466610/155841185-ef60c32c-a4ee-4759-95b1-973f1e093ed4.png)
onnxruntime：
![image](https://user-images.githubusercontent.com/48466610/155841203-e5528ea1-80b1-4146-9299-2a78b6e37435.png)
MNN：我这里拷贝的是release版本，后续也是编译的MinSizeRel版本
![image](https://user-images.githubusercontent.com/48466610/155841227-ef8594a3-c3c7-4c67-b66f-929fc0a1a731.png)
ncnn：
![image](https://user-images.githubusercontent.com/48466610/155841235-e3d7e240-d3ab-4fc9-a9f6-e798a00b2f2f.png)
protobuf ：这个也复制了（因为编译错误很多次，所以就把用到的都复制了）
![image](https://user-images.githubusercontent.com/48466610/155841283-762d1174-0601-45a4-8f7a-8fe4ccfa0269.png)
总文件夹：
![image](https://user-images.githubusercontent.com/48466610/155841365-aaf6a9a8-b43b-43cb-a242-1587afc4d5cc.png)
1.5.4 配置
修改opencv配置：
![image](https://user-images.githubusercontent.com/48466610/155841459-0c9d26ac-94ec-482c-bf14-6aac111fb21e.png)
1.5.5 cmake：
方法一：
![image](https://user-images.githubusercontent.com/48466610/155841581-04f0f68c-19c7-45b6-b7a6-de8576f4853a.png)
![image](https://user-images.githubusercontent.com/48466610/155841603-9cf8412f-50b0-4615-9394-57d374376b05.png)
![image](https://user-images.githubusercontent.com/48466610/155841709-aa8674c6-fd6b-41aa-884a-e6cb88e0c923.png)

法二：
cmake GUI
![image](https://user-images.githubusercontent.com/48466610/155841888-660c928f-c97b-4382-bfa0-580215bdcbc9.png)
![image](https://user-images.githubusercontent.com/48466610/155842025-b64b3915-e2e9-4b19-a0ed-b1db7db7dadb.png)
![image](https://user-images.githubusercontent.com/48466610/155842080-85792caa-094e-4b07-ad70-cfcfa79e8aa3.png)
1.5.6 打开项目，准备编译：
![image](https://user-images.githubusercontent.com/48466610/155842167-b97a47e2-c6e3-4936-b05f-286a544d61bf.png)
![image](https://user-images.githubusercontent.com/48466610/155842338-72ca97e9-20cf-4195-a172-49a07b1707be.png)
配置 头文件：
![image](https://user-images.githubusercontent.com/48466610/155843309-29ca6f5e-241a-462c-99ba-d302f3f64e5f.png)
配置 lib路径：
![image](https://user-images.githubusercontent.com/48466610/155843342-be6f621a-9cdc-4b0d-b736-92666ecd2b76.png)
配置lib文件名：
![image](https://user-images.githubusercontent.com/48466610/155843368-ed5a4375-5d36-4a8b-b742-13fc4e8fd91c.png)
这是我的lib名：
opencv_world455.lib
onnxruntime.lib
MNN.lib
ncnn.lib
TNN.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib
libprotobuf.lib
vulkan-1.lib
glslang.lib
SPIRV.lib
OGLCompiler.lib
OSDependent.lib
MachineIndependent.lib
GenericCodeGen.lib
添加error解决：
![image](https://user-images.githubusercontent.com/48466610/155843421-70ba3628-9765-46fb-80b2-ea1ad1ffb37f.png)

1.5.7 生成：
![image](https://user-images.githubusercontent.com/48466610/155843429-10cb15fe-d150-418b-ae19-58af0c1640dc.png)
1.5.8 结束
![image](https://user-images.githubusercontent.com/48466610/155843466-f1131220-f15d-498d-b136-9f4e7fc78838.png)
可能有不妥当地方，欢迎大佬指出：

**Comment by DefTruth** [comment]
@zhanghongyong123456 哇~ 简直太赞啦！！！太感谢这位同学详细的windows配置教程啦！！！我要把这个issue置顶！

**Comment by zhanghongyong123456** [comment]
> @zhanghongyong123456 哇~ 简直太赞啦！！！太感谢这位同学详细的windows配置教程啦！！！我要把这个issue置
希望可以有所助力，主要是想跟随大佬的脚步前行。

**Comment by Jiangjiawei2** [comment]
我按照这个教程完成了，但在RVM中生成的EXE点开后闪退。还有我在test_lite_rvm.cpp中设置了断点，可实际上程序根本没有运行到test_lite()。请问有实现成功的人帮助下吗

**Comment by DefTruth** [comment]
> 我按照这个教程完成了，但在RVM中生成的EXE点开后闪退。还有我在test_lite_rvm.cpp中设置了断点，可实际上程序根本没有运行到test_lite()。请问有实现成功的人帮助下吗

你要确保所有的库都能链接上，比如要拷贝到exe相同的目录，并且模型文件已经下载好放在对应的位置，具体细节请参考rvm示例工程的C++代码。

**Comment by zhanghongyong123456** [comment]
> 我按照这个教程完成了，但在RVM中生成的EXE点开后闪退。还有我在test_lite_rvm.cpp中设置了断点，可实际上程序根本没有运行到test_lite()。请问有实现成功的人帮助

想查找缺少那个库，可以将一个个lib、dll依次拷贝到exe根目录，运行，不想查找直接拷贝这个文件下所有lib  dll
![image](https://user-images.githubusercontent.com/48466610/158090432-31d07c15-1b93-488a-a6f1-ea6b4a5cdcdb.png)

**Comment by 19PDP** [comment]
编译时提示
> 无法打开包括文件："vulkan/vulkan.h": No such file or directory"

解决办法：将 vulkan 安装目录下 Include 文件夹中的 vulkan 文件夹整个复制到 lite.ai.toolkit 目录下（就像复制 onnxruntime 的 include 文件夹那样）。

**Comment by zhanghongyong123456** [comment]
> 编译时提示
> 
> > 无法打开包括文件："vulkan/vulkan.h": No such file or directory"
> 
> 解决办法：将 vulkan 安装目录下 Include 文件夹中的 vulkan 文件夹整个复制到 lite.ai.toolkit 目录下（就像复制 onnxruntime 的 include 文件夹那样）。

这个直接在包含目录下添加vukan文件的include就可以了吧，

**Comment by xmuzyyy** [comment]
> > 编译时提示
> > > 无法打开包括文件："vulkan/vulkan.h": No such file or directory"
> > 
> > 
> > 解决办法：将 vulkan 安装目录下 Include 文件夹中的 vulkan 文件夹整个复制到 lite.ai.toolkit 目录下（就像复制 onnxruntime 的 include 文件夹那样）。
> 
> 这个直接在包含目录下添加vukan文件的include就可以了吧，

求助！！！！请问一下，这个Valkan在教程中哪里有要求下载呀？如果我只用onnx的模型，其他都不用的话，我最后应该只需要配opencv和onnx吧？生成lite.ai.toolkit的时候报错了TT

**Comment by zhanghongyong123456** [comment]
> 
![2022-03-21 10-51-45屏幕截图](https://user-images.githubusercontent.com/48466610/159199281-1b592377-1d36-452f-b99c-642f88dfb978.png)

在1.4 配置ncnn 参考链接里面呢，
1.4 配置 ncnn，参考这个链接
https://zhuanlan.zhihu.com/p/391609325

**Comment by DefTruth** [comment]
> 

感谢提醒，这是lite.ai.toolkit TNN版本的已知的bug，会导致在在windows下发生内存泄漏，mac和linux可以正常运行。正在修复中...  相关issue可见:  

* #240

**Comment by taotaoyuhust** [comment]
一定要用vs2019吗，我用vs2017一堆的错误

**Comment by zhanghongyong123456** [comment]
> 一定要用vs2019吗，我用vs2017一堆的错误

都是什么错误，我电脑只安装了2019，没有17所以没测试过

**Comment by taotaoyuhust** [comment]
![image](https://user-images.githubusercontent.com/18323333/160228599-94dcf237-25aa-4783-ad63-5fcfa5cfc6ab.png)

**Comment by taotaoyuhust** [comment]
![image](https://user-images.githubusercontent.com/18323333/160228617-b47037b1-c1e0-4e23-b2f2-95f083907368.png)

**Comment by taotaoyuhust** [comment]
重装了2019就好了。。楼主c++代码用到的语法太高级了。。
另外，onnxruntime得用1.9.0版本的，1.3.0的会报错

**Comment by Richardlyq** [comment]
![image](https://user-images.githubusercontent.com/78252642/160263850-f328b5b0-63b5-45de-8e68-69db27a05bea.png)
请问这个算编译成功了嘛？结合教程，我只用了onnxruntime（下载的1.7.0版本的，没用gpu）、opencv。前面还有好多看不懂的，5555~

**Comment by HAmazon59** [comment]
编译时貌似ONNXRUNTIME里少了个文件，请问大佬们应该怎么解决：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	无法打开包括文件: “onnxruntime/core/providers/cuda/cuda_provider_factory.h”: No such file or directory
![error](https://user-images.githubusercontent.com/102913800/161434471-6357e078-3cfd-43e6-8744-d03c726de5c6.png)
我能在Onnxruntime里找到这个文件，但他并不在include目录下，
![directory](https://user-images.githubusercontent.com/102913800/161434546-47d38b1d-4ae6-48de-9329-5850481df479.png)
而include\onnxruntime\core\providers目录下没有cuda文件夹
另外，如果我注释掉这段语句，编译完成后运行测试文件会出现
无法打开包括文件: “vulkan/vulkan.h”: No such file or directory	lite_age_googlenet	C:\Users\11454\Desktop\lite.ai.toolkit-main\ncnn\allocator.h	28	
的问题，请问大佬们该如何解决？

**Comment by l7518597** [comment]
请教一下，不调用GPU，只CPU用。只用onnxruntime应该怎么配置

**Comment by l7518597** [comment]
编译出这三个文件后  怎么用呢?

**Comment by chfeizy** [comment]
onnxruntime 1.8.1 1.8.2 1.11.0 以上都有cuda/cpu_provider_factory.h
但是1.9.0 1.9.1 1.10.0这三个版本是没有的
1.9.0 这个版本怎么编译通过的

**Comment by chfeizy** [comment]
“lite_rvm.exe”(Win32): 已加载“C:\lite.ai.toolkit-main\build\lite.ai.toolkit\bin\Debug\lite_rvm.exe”。已加载符号。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\ntdll.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\kernel32.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\KernelBase.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\lite.ai.toolkit-main\build\lite.ai.toolkit\bin\Debug\lite.ai.toolkit.dll”。已加载符号。
“lite_rvm.exe”(Win32): 已加载“C:\www\opencv_build\install\x64\vc16\bin\opencv_core455.dll”。已加载符号。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\ucrtbase.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\www\opencv_build\install\x64\vc16\bin\opencv_highgui455.dll”。已加载符号。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\gdi32.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\win32u.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\gdi32full.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\msvcp_win.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\user32.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\comdlg32.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\msvcrt.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\combase.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\rpcrt4.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\SHCore.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\shlwapi.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\shell32.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\advapi32.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\sechost.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\www\opencv_build\install\x64\vc16\bin\opencv_highgui455d.dll”。已加载符号。
“lite_rvm.exe”(Win32): 已加载“C:\www\opencv_build\install\x64\vc16\bin\opencv_imgcodecs455.dll”。已加载符号。
“lite_rvm.exe”(Win32): 已加载“C:\www\opencv_build\install\x64\vc16\bin\opencv_videoio455.dll”。已加载符号。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\ole32.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\oleaut32.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\onnxruntime.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\msvcp140d.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140d.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140_1d.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\ucrtbased.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\www\opencv_build\install\x64\vc16\bin\opencv_core455d.dll”。已加载符号。
“lite_rvm.exe”(Win32): 已加载“C:\www\opencv_build\install\x64\vc16\bin\opencv_imgproc455.dll”。已加载符号。
“lite_rvm.exe”(Win32): 已加载“C:\www\opencv_build\install\x64\vc16\bin\opencv_imgproc455d.dll”。已加载符号。
“lite_rvm.exe”(Win32): 已加载“C:\www\opencv_build\install\x64\vc16\bin\opencv_videoio455d.dll”。已加载符号。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\msvcp140.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\concrt140.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140_1.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\comctl32.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\www\opencv_build\install\x64\vc16\bin\opencv_imgcodecs455d.dll”。已加载符号。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\mfplat.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\cfgmgr32.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\mf.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\mfreadwrite.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\dxgi.dll”。
“lite_rvm.exe”(Win32): 已加载“C:\Windows\System32\d3d11.dll”。
线程 0x526c 已退出，返回值为 -1073741701 (0xc000007b)。
线程 0x29a4 已退出，返回值为 -1073741701 (0xc000007b)。
程序“[7240] lite_rvm.exe”已退出，返回值为 -1073741701 (0xc000007b)。
 
编译好了也复制过去了gpu运行还是报错

**Comment by DefTruth** [comment]
不支持Debug，只支持release

**Comment by terryluzhenfeng** [comment]
> 重装了2019就好了。。楼主c++代码用到的语法太高级了。。 另外，onnxruntime得用1.9.0版本的，1.3.0的会报错

编译成功后，怎么进行代码调试啊？大佬可有时间，解答一下
