### ISSUE TITLE
使用 pytorch_face_landmarks_landmark_detection_56_se_external.onnx 68点位识别下巴3个点位基本一条线还有rvm感觉有点卡可以怎么优化下

### ISSUE THREAD

**Issue by chfeizy** [DefTruth/lite.ai.toolkit#208]
downsample_ratio 可以调低于0.25 效果不是特别好了

**Comment by chfeizy** [comment]
![image](https://user-images.githubusercontent.com/6427629/155846315-f7ac0b49-0a35-48cd-b8bf-b782d62bf699.png)
看前面的提到测试刚好是mac 只能用cpu
难怪这么卡

**Comment by chfeizy** [comment]
下巴把人脸高度加个20 差不多可以用

**Comment by DefTruth** [comment]
是的，cpu跑rvm的话，不能实时，可以去看看modnet，号称实时，目前还没有集成进来。另外关键点检测会受人脸框的影响，要有比较适合的扩宽系数，最近有个开源的pipnet也可以了解下。
