### ISSUE TITLE
多线程预测会经常性出现不准确情况

### ISSUE THREAD

**Issue by xinyujituan** [DefTruth/lite.ai.toolkit#209]
多线程预测会经常性出现不准确情况！ 通过加锁调试发现是onnxruntime的问题 需要吧create_tensor和 run都加锁才能正常，这是怎么回事 onnxruntime不支持多线程？

**Comment by DefTruth** [comment]
不太清楚~ 多线程目前我也没测试过。

**Comment by DearSunMeng** [comment]
> 多线程预测会经常性出现不准确情况！ 通过加锁调试发现是onnxruntime的问题 需要吧create_tensor和 run都加锁才能正常，这是怎么回事 onnxruntime不支持多线程？

我测试多线程也发现这个问题，但是是偶发现象，另外想问问你那边的多线程运行速度怎么样？我这边验证多线程，每张图片都有两个线程在运行，然乎会出现某一张图片时间较长。有时候会到十几倍
