### ISSUE TITLE
Access to models

### ISSUE THREAD

**Issue by sctrueew** [DefTruth/lite.ai.toolkit#21]
Hi,

Thanks for your work. Could you please share the models on GDrive? because I can't access Baidu.

Thanks

**Comment by DefTruth** [comment]
> Hi,
> 
> Thanks for your work. Could you please share the models on GDrive? because I can't access Baidu.
> 
> Thanks

[Google Drive](https://drive.google.com/drive/folders/1p6uBcxGeyS1exc-T61vL8YRhwjYL4iD2) . Note, I can not upload all the *.onnx files because of the storage limitation of Google Driver (15G).

**Comment by zpmmehrdad** [comment]
@DefTruth Hi,

Thanks for sharing the models. I can't access this path. 404 not found

**Comment by DefTruth** [comment]
> @DefTruth Hi,
> 
> Thanks for sharing the models. I can't access this path. 404 not found

try this new one:  
https://drive.google.com/drive/folders/1p6uBcxGeyS1exc-T61vL8YRhwjYL4iD2?usp=sharing  

I don not know why the previous one expired ...

**Comment by MyraBaba** [comment]
@DefTruth 

Hi We cant access to the Baidu also. Would you mind to share all model in GoogleDrive ? you can use few more gmail account to have more Gig. :) How much is total model size ? 

Best  & Thanks

PS: Is there any accuracy decrease between mxnet ie arfacR100 and onnx converted models
 ?

**Comment by DefTruth** [comment]
> @DefTruth
> 
> Hi We cant access to the Baidu also. Would you mind to share all model in GoogleDrive ? you can use few more gmail account to have more Gig. :) How much is total model size ?
> 
> Best & Thanks
> 
> PS: Is there any accuracy decrease between mxnet ie arfacR100 and onnx converted models ?

1. the total size of all models is already 23+G now, but the free memory limitation of GoogleDrive is 15G.  
2. i will try to use few more gmail account later
3. i am trying to upload the model files using `git lfs` but not sure whether it can handle the all the model files
4. almost all the models are converted from `pth` with fp32 , it should not cause much degradation
