### ISSUE TITLE
ncnn rvm 抠图 会报错

### ISSUE THREAD

**Issue by chfeizy** [DefTruth/lite.ai.toolkit#210]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/6427629/155847764-7ed1bf5e-f1ea-4e60-bed7-5588e333a53f.png">
看起来是 
 ncnn::Mat src;
  this->transform(mat, src);
转化之后 data 没用数据了

**Comment by DefTruth** [comment]
ncnn 版本的 rvm目前是不支持的，确实是有这个问题，之前有类似的issue问过。现在只能用其他版本的实现。
* #138
