### ISSUE TITLE
yolox更新问题

### ISSUE THREAD

**Issue by gyy0592** [DefTruth/lite.ai.toolkit#22]
自从yolox更新之后 似乎不再适用新版模型了 请问哪里需要进行调整呢

**Comment by 1VeniVediVeci1** [comment]
注释掉yolox.cpp中的ortcv::utils::transform::normalize_inplace(canva, mean_vals, scale_vals); // float32

**Comment by xinsuinizhuan** [comment]
同问，注释掉，自己训练的模型，检测也错乱了。

**Comment by DefTruth** [comment]
具体是什么问题呢？YOLOX原来版本的onnx文件是可用的，不需要注释这句。归一化预处理应该是需要的。

**Comment by DefTruth** [comment]
> 自从yolox更新之后 似乎不再适用新版模型了 请问哪里需要进行调整呢

[ncnn-yolox.cpp](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/demo/ncnn/cpp/yolox.cpp)  官方实现里，新的c++推理确实没有了归一化操作

**Comment by DefTruth** [comment]
> 同问，注释掉，自己训练的模型，检测也错乱了。
如果是使用新的YOLOX官方库训的代码，可能需要注释以下这句。因为 [ncnn-yolox.cpp](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/demo/ncnn/cpp/yolox.cpp)  官方实现里，新的c++推理确实没有了归一化操作。   
```c++
Ort::Value YoloX::transform(const cv::Mat &mat)
{
  cv::Mat canva = mat.clone();
  cv::cvtColor(canva, canva, cv::COLOR_BGR2RGB);
  // resize without padding, todo: add padding as the official Python implementation.
  cv::resize(canva, canva, cv::Size(input_node_dims.at(3),
                                    input_node_dims.at(2)));
  // (1,3,640,640) 1xCXHXW
 //  ortcv::utils::transform::normalize_inplace(canva, mean_vals, scale_vals); // float32 注释掉这句
  return ortcv::utils::transform::create_tensor(
      canva, input_node_dims, memory_info_handler,
      input_values_handler, ortcv::utils::transform::CHW);
}
```   
但是如果是使用旧版本YOLOX代码训的，就不能注释这句。
