### ISSUE TITLE
win10编译成功了，运行rvm代码报错。

### ISSUE THREAD

**Issue by chenjiachengzzz** [DefTruth/lite.ai.toolkit#229]
<img width="1115" alt="1646838999(1)" src="https://user-images.githubusercontent.com/54382260/157471202-027e331f-a23b-462f-9360-63aa1b58132e.png">
我装的onnx是cpu版本的问题嘛

**Comment by DefTruth** [comment]
可以参考这个文档编译windows版本：
* #207
