### ISSUE TITLE
yolox   in tnn???

### ISSUE THREAD

**Issue by henbucuoshanghai** [DefTruth/lite.ai.toolkit#23]
do you have the tnn code of yolox?

**Comment by DefTruth** [comment]
Sorry, I don't have the tnn code of yolox now ~

**Comment by henbucuoshanghai** [comment]
I write one ,and get box.but the boxes are not right.....   I dont konw why.

**Comment by DefTruth** [comment]
> I write one ,and get box.but the boxes are not right..... I dont konw why.

can you share the code ? I am not sure what the problem you have encounter. And,  you should note that the newest  C++ preprocess of in official YOLOX repo after 2021/08/19 is difference with the old version. See this #22 .  I hope it helps ~

**Comment by henbucuoshanghai** [comment]
my main code is form the ncnn cpp code and tensorrt cpp code in yolox,
the model is from the official yolox too.
the box is not right, i donot know why.
