### ISSUE TITLE
已经生成exe执行文件了，但是报这个错是什么意思啊

### ISSUE THREAD

**Issue by chenjiachengzzz** [DefTruth/lite.ai.toolkit#232]
<img width="649" alt="1646996656(1)" src="https://user-images.githubusercontent.com/54382260/157855291-734e4c96-0082-4b26-896e-3a6382e9e89e.png">
已经生成exe执行文件了，但是报这个错是什么意思啊

**Comment by yc-Dong** [comment]
请问可以分享一下是如何在windows上跑起来的吗？

**Comment by yc-Dong** [comment]
您好，我已经收到您的邮件！我会尽快回复！

**Comment by DefTruth** [comment]
#207 

可以参考这个教程编译windows版本。另外就是注意一下编译完后exe的路径问题，因为你们是用vs编的，我是用cmake编的，生成exe的路径会不太一样。我看你这里exe所在的路径不太对，中间多隔了一层MinSizeRel文件夹，会找不到模型和资源文件，因为我假设的测试工程的可执行文件路径是 lite.ai.toolkit/build/lite.ai.toolkit/bin，所以往回跳3层刚好回到项目的根目录，但你这里多了一层MinSizeRel目录，所以还要再跳一层才能找到模型和资源文件
