### ISSUE TITLE
可以支持模型训练吗

### ISSUE THREAD

**Issue by jjqcat** [DefTruth/lite.ai.toolkit#233]
可以支持模型训练吗

**Comment by DefTruth** [comment]
目前不支持训练，lite.ai.toolkit主要关注模型的C++推理实现。如果您对关键点检测感兴趣的话，可以看看我的另一个开源项目：

* https://github.com/DefTruth/torchlm  

支持人脸关键点检测的训练、推理和100+种数据增强，可以通过pip一键安装。

**Comment by jjqcat** [comment]
[torchlm](https://github.com/DefTruth/torchlm) 这个只能用在人脸关键点训练推理？还是其它的检测都可以，如缺陷检测分类

**Comment by DefTruth** [comment]
> [torchlm](https://github.com/DefTruth/torchlm) 这个只能用在人脸关键点训练推理？还是其它的检测都可以，如缺陷检测分类

只是做人脸关键点的，目前没有精力做别的了😂
