### ISSUE TITLE
WIN10 自行编译的MNN-VULKAN GPU库无效

### ISSUE THREAD

**Issue by yyl9510** [DefTruth/lite.ai.toolkit#235]
我在win10上成功编译了此项目，运行也ok。
  我现在是通过mnn来推理的，但因为cpu版本的mnn无法做到实时，所以想编译GPU版本的mnn试试，因为电脑已经装了vulkan，就编译了mnn的cpu+vulkan的库，在项目中替换了带GPU的mnn库之后，运行还是在cpu上（通过任务管理器的性能看负载，和图片的处理速度得出的）
  我将MNN::ScheduleConfig schedule_config; 这里也设置成了 schedule_config.backupType = MNN_FORWARD_VULKAN; （原来是MNN_FORWARD_CPU），依然无效。
  请问有办法让RVM在MNN环境下调用GPU吗？
  然后不知道MNN,ONNXRUNTIME更推荐使用哪一个呢？

**Comment by DefTruth** [comment]
主要的配置逻辑是在这段改：
```c++
void MNNRobustVideoMatting::initialize_interpreter()
{
  // 1. init interpreter
  mnn_interpreter = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(mnn_path));
  // 2. init schedule_config
  schedule_config.numThread = (int) num_threads;
  MNN::BackendConfig backend_config;
  backend_config.precision = MNN::BackendConfig::Precision_High; // default Precision_High
  schedule_config.backendConfig = &backend_config;
  // 3. create session
  mnn_session = mnn_interpreter->createSession(schedule_config);
  // 4. init input tensor
  src_tensor = mnn_interpreter->getSessionInput(mnn_session, "src");
  // 5. init input dims
  input_height = src_tensor->height();
  input_width = src_tensor->width();
  dimension_type = src_tensor->getDimensionType(); // CAFFE
  mnn_interpreter->resizeTensor(src_tensor, {1, 3, input_height, input_width});
  mnn_interpreter->resizeSession(mnn_session);
  src_size = 1 * 3 * input_height * input_width;
  // 6. rxi
  r1i_tensor = mnn_interpreter->getSessionInput(mnn_session, "r1i");
  r2i_tensor = mnn_interpreter->getSessionInput(mnn_session, "r2i");
  r3i_tensor = mnn_interpreter->getSessionInput(mnn_session, "r3i");
  r4i_tensor = mnn_interpreter->getSessionInput(mnn_session, "r4i");
```
配置完重新编译，再运行rvm。至于为什么用不到GPU，我也不太清楚你的使用情况，可以看看有没有什么特殊的宏是不被开启的，或者用你编译的MNN的头文件替换掉lite.ai.toolkit中的MNN头文件试一下，虽然我是直接拷贝的MNN的头文件，但不排除MNN不同的编译方式会在编译时通过cmake注入不同的宏，这种处理很常见。

**Comment by yyl9510** [comment]
我重新编译了几次，头文件也换成了编译结果里面的include，还是只调用了CPU。
这是我定义的所有的宏：WIN32;_WINDOWS;NDEBUG;_CONSOLE;NOMINMAX;_CRT_SECURE_NO_WARNINGS;PREPROCESS_DEBUG;_UNICODE
UNICODE，我觉得不是宏定义的问题吧。
我的配置逻辑是这样的，和原本的相比就是增加了`schedule_config.mode = MNN_GPU_TUNING_NORMAL | MNN_GPU_MEMORY_IMAGE;` 和 `schedule_config.backupType = MNN_FORWARD_VULKAN;` 去掉了 `schedule_config.numThread = (int)num_threads;`
：
``` 
void MNNRobustVideoMatting::initialize_interpreter()
{
	// 1. init interpreter
	mnn_interpreter = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(mnn_path));
	// 2. init schedule_config
	//schedule_config.numThread = (int)num_threads;
	MNN::BackendConfig backend_config;
	backend_config.precision = MNN::BackendConfig::Precision_High; // default Precision_High
	schedule_config.backendConfig = &backend_config;
	schedule_config.mode = MNN_GPU_TUNING_NORMAL | MNN_GPU_MEMORY_IMAGE;
	schedule_config.backupType = MNN_FORWARD_VULKAN;
	// 3. create session
	mnn_session = mnn_interpreter->createSession(schedule_config);
	// 4. init input tensor
	src_tensor = mnn_interpreter->getSessionInput(mnn_session, "src");	//it should be src here ,not NULL
	// 5. init input dims
	input_height = src_tensor->height();
	input_width = src_tensor->width();
	dimension_type = src_tensor->getDimensionType(); // CAFFE
	mnn_interpreter->resizeTensor(src_tensor, { 1, 3, input_height, input_width });
	mnn_interpreter->resizeSession(mnn_session);
	src_size = 1 * 3 * input_height * input_width;
	// 6. rxi
	r1i_tensor = mnn_interpreter->getSessionInput(mnn_session, "r1i");
	r2i_tensor = mnn_interpreter->getSessionInput(mnn_session, "r2i");
	r3i_tensor = mnn_interpreter->getSessionInput(mnn_session, "r3i");
	r4i_tensor = mnn_interpreter->getSessionInput(mnn_session, "r4i");
}
```
不知道在mac或者linux上复制我这里的代码，能成功调用GPU运行吗？
不能的话说明是代码的问题，能的话说明是我编译的问题对吧？

**Comment by DefTruth** [comment]
不太清楚。你可以考虑单独把rvm.cpp和rvm.h摘出来的，参考我写的前后处理逻辑，自己再稍微封装下就能用，不需要依赖lite.ai.toolkit。各个模型之间的实现是完全解耦的。

**Comment by yyl9510** [comment]
> 不太清楚。你可以考虑单独把rvm.cpp和rvm.h摘出来的，参考我写的前后处理逻辑，自己再稍微封装下就能用，不需要依赖lite.ai.toolkit。各个模型之间的实现是完全解耦的。

我就是摘出来用的
MNN到底该怎么调用GPU运行呢，要是有个MNN调用GPU的demo我试试就好了。因为我现在很迷茫的点在于，不知道到底是代码这里有问题，还是编译那里除了问题。
还是非常感谢你的解答~

**Comment by yyl9510** [comment]
ok 了， 可以调vulkan的GPU版本
使用`schedule_config.backupType = MNN_FORWARD_VULKAN;`是不行的，需要使用`schedule_config.type = MNN_FORWARD_VULKAN;`
现在的问题是使用vulkan反而比cpu的更慢了

**Comment by DefTruth** [comment]
可以试一下onnxruntime的gpu版本

**Comment by Pony23333** [comment]
> ok 了， 可以调vulkan的GPU版本 使用`schedule_config.backupType = MNN_FORWARD_VULKAN;`是不行的，需要使用`schedule_config.type = MNN_FORWARD_VULKAN;` 现在的问题是使用vulkan反而比cpu的更慢了

You can consider 

> ok 了， 可以调vulkan的GPU版本 使用`schedule_config.backupType = MNN_FORWARD_VULKAN;`是不行的，需要使用`schedule_config.type = MNN_FORWARD_VULKAN;` 现在的问题是使用vulkan反而比cpu的更慢了

You can try using parallelling branches on CPU and GPU to accelerate as MNN supports.
