### ISSUE TITLE
Windows编译成功但是生成的exe报错

### ISSUE THREAD

**Issue by nihenxiu** [DefTruth/lite.ai.toolkit#239]
请问一下大佬，windows vs2019按照 #207 编译生成lite.ai.toolkit.dll和lite.ai.toolkit.lib后，将其余所需的库都拷贝到相应目录下（如下图1），然后右击lite_rvm点生成，成功生成（如下图2），随后按照 #234 将所有库都拷贝到exe目录下（如下图3），最后点击exe报错如下图4，请问该怎么解决呢
![PS7 }_E}ECWEQTOS~X4O3O7](https://user-images.githubusercontent.com/78015819/158345922-7d2860f6-1b43-459b-a034-d10ad10266ba.png)
![88@GPH7W6Q~9S6XWJFK1M2F](https://user-images.githubusercontent.com/78015819/158346040-8e28c6b5-4f39-4b02-8852-1a457a1466ff.png)
![{6M{WG92W9DEYDYFJA7_QQL](https://user-images.githubusercontent.com/78015819/158346063-e228d052-4f9e-4f1e-84cb-7315839a5d66.png)
![UW2RZ3J$N(@8 `9VTPEIQ6P](https://user-images.githubusercontent.com/78015819/158346118-ad7099fa-8a69-40bb-872e-a0e8ea6028d0.png)

**Comment by DefTruth** [comment]
试一下mobilenet的模型

**Comment by nihenxiu** [comment]
![V)(Z{U{Y OSRK}7DVS6L3)H](https://user-images.githubusercontent.com/78015819/158367937-a00621bd-e9b7-4525-9f4b-5e3b7f052b23.png)
![(UUX9YNQC}$480MKV}SOTNI](https://user-images.githubusercontent.com/78015819/158367974-1b4c0638-188c-432f-8db4-6a919163aa94.png)
试了另外几个模型，仍然是这样😭

**Comment by DefTruth** [comment]
再试一下release模式下编译的吧。或者在test_lite_rvm.cpp里面加一些log，看看具体是什么问题。我感觉你的exe所在的路径不太对，中间多隔了一层Debug文件夹，会找不到模型和资源文件，因为我假设的测试工程的exe路径是 lite.ai.toolkit/build/lite.ai.toolkit/bin，所以往回跳3层刚好回到项目的根目录，但你这里多了一层Debug目录，所以还要再跳一层才能找到模型和资源文件

**Comment by Jiangjiawei2** [comment]
@nihenxiu 您好，报错的问题请问您解决了吗

**Comment by hanxizai** [comment]
您好请问问题解决了嘛
