### ISSUE TITLE
Running models in half precision FP16

### ISSUE THREAD

**Issue by livingbeams** [DefTruth/lite.ai.toolkit#24]
I am trying to run the FP16 version of the model "rvm_mobilenetv3_fp16.onnx"

I am trying to write a FP16 version of the helper function
Ort::Value ortcv::utils::transform::create_tensor()

I understand I have to use the function:
inline Value Value::CreateTensor(const OrtMemoryInfo* info, void* p_data, size_t p_data_byte_count, const int64_t* shape, size_t shape_len, ONNXTensorElementDataType type)

With ONNXTensorElementDataType  = ONNX_TENSOR_ELEMENT_DATA_TYPE_BFLOAT16     // Non-IEEE floating-point format based on IEEE754 single-precision

But i am stuck working out how to handle half resolution vectors in c++

Probably it is necessary to handle uint16 types to handle the pointers and make some conversion to half floats at some point, but I am lost about how to handle this.

**Comment by DefTruth** [comment]
many thanks to let me know this error~i will try to fix this bug as soon as i can
