### ISSUE TITLE
windows生成lite.ai.toolkit报错

### ISSUE THREAD

**Issue by hanxizai** [DefTruth/lite.ai.toolkit#242]
![JNK7I36HGP$2M@FS}IQKNUF](https://user-images.githubusercontent.com/92412351/159006962-450c8928-f103-4056-b5f5-bc7987b9f101.png)

**Comment by DefTruth** [comment]
#207 

windows可以参考这篇教程进行配置

**Comment by hanxizai** [comment]
> 

大佬，我是参考这个教程进行编译的但是还是报了错T ^ T

**Comment by DefTruth** [comment]
看起来像系统函数冲突的问题，但在windows下，我已经设置NONMINMAX的宏了。你可以参考一些相关的解决方案吧。精力有限，我目前还没有时间在windows下编译过，你可以看一下issue里其他小伙伴的解决方案，或者考虑用Mac或Linux版本。  其实也可以单独把你想用的模型摘出来，参考里面的C++前后处理逻辑可以实现一份自己的推理代码。

* [error C2589: “(”: “::”右边的非法标记；error C2059: 语法错误 : “::”](https://blog.csdn.net/xidianzhimeng/article/details/21181279?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1.pc_relevant_antiscanv2&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1.pc_relevant_antiscanv2&utm_relevant_index=1)

**Comment by hanxizai** [comment]
> 看起来像系统函数冲突的问题，但在windows下，我已经设置NONMINMAX的宏了。你可以参考一些相关的解决方案吧。精力有限，我目前还没有时间在windows下编译过，你可以看一下issue里其他小伙伴的解决方案，或者考虑用Mac或Linux版本。 其实也可以单独把你想用的模型摘出来，参考里面的C++前后处理逻辑可以实现一份自己的推理代码。
> 
> * [error C2589: “(”: “::”右边的非法标记；error C2059: 语法错误 : “::”](https://blog.csdn.net/xidianzhimeng/article/details/21181279?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1.pc_relevant_antiscanv2&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1.pc_relevant_antiscanv2&utm_relevant_index=1)
> 
> ![image](https://user-images.githubusercontent.com/31974251/159017146-ff254996-0a29-49d5-93db-67a847d29551.png)

好的，辛苦大佬了(*^▽^*)

**Comment by xmuzyyy** [comment]
> > 看起来像系统函数冲突的问题，但在windows下，我已经设置NONMINMAX的宏了。你可以参考一些相关的解决方案吧。精力有限，我目前还没有时间在windows下编译过，你可以看一下issue里其他小伙伴的解决方案，或者考虑用Mac或Linux版本。 其实也可以单独把你想用的模型摘出来，参考里面的C++前后处理逻辑可以实现一份自己的推理代码。
> > 
> > * [error C2589: “(”: “::”右边的非法标记；error C2059: 语法错误 : “::”](https://blog.csdn.net/xidianzhimeng/article/details/21181279?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1.pc_relevant_antiscanv2&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1.pc_relevant_antiscanv2&utm_relevant_index=1)
> > 
> > ![image](https://user-images.githubusercontent.com/31974251/159017146-ff254996-0a29-49d5-93db-67a847d29551.png)
> 
> 好的，辛苦大佬了(_^▽^_)

请问你解决了吗，我也在最后遇到问题了 TVT

**Comment by hanxizai** [comment]
> > > 看起来像系统函数的问题，但在windows下，我已经设置了NONMINMAX的宏了。你可以一些相关的解决方案吧。精力有限，我目前还没有时间在windows下编译过，你可以看看问题里其他小伙伴的问题，或者考虑Mac或Linux版本。其实代码也可以用你自己想用的模型提取出来，里面的C++前后处理逻辑可以实现自己的推理。
> > > 
> > > * [error C2589: “(”: “::” 正确的错误标注；error C2059: 语法: “::”](https://blog.csdn.net/xidianzhimeng/article/details/21181279?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1.pc_relevant_antiscanv2&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1.pc_relevant_antiscanv2&utm_relevant_index=1)
> > > 
> > > ![图片](https://user-images.githubusercontent.com/31974251/159017146-ff254996-0a29-49d5-93db-67a847d29551.png)
> > 
> > 
> > 好，辛苦大佬了( _^▽^_ )
> 
> 你解决了，我最后遇到问题了请TVT

T ^ T我重新编译但是问题还是没有解决

**Comment by DefTruth** [comment]
你加上了NOMINMAX的宏之后也是有问题吗？或者可以手动改一下 lite.ai.defs.h , 定义好 NOMINMAX 再编译。
```C++
#ifdef LITE_WIN32
# define NONMINMAX  // 这里是有一个系统判断的，但我似乎写错了应该是NOMINMAX不是NONMINMAX
#endif

// 你在外部重新定义一下NOMINMAX再编译windows版本的试试
# define NOMINMAX
```

**Comment by DefTruth** [comment]
你加上了NOMINMAX的宏之后也是有问题吗？或者可以手动改一下 lite.ai.defs.h , 定义好 NOMINMAX 再编译。
```C++
#ifdef LITE_WIN32
# define NONMINMAX  // 这里是有一个系统判断的，但我似乎写错了应该是NOMINMAX不是NONMINMAX
#endif

// 你在外部重新定义一下NOMINMAX再编译windows版本的试试
# define NOMINMAX
```

**Comment by hanxizai** [comment]
> 你加上了NOMINMAX的宏之后也是有问题吗？或者可以手动改一下 lite.ai.defs.h , 定义好 NOMINMAX 再编译。
> 
> ```c++
> #ifdef LITE_WIN32
> # define NONMINMAX  // 这里是有一个系统判断的，但我似乎写错了应该是NOMINMAX不是NONMINMAX
> #endif
> 
> // 你在外部重新定义一下NOMINMAX再编译windows版本的试试
> # define NOMINMAX
> ```

谢谢大佬！！编译成功啦
