### ISSUE TITLE
Add FaceBoxesV2 and PIPNet

### ISSUE THREAD

**Issue by DefTruth** [DefTruth/lite.ai.toolkit#243]
* add FaceBoxesV2 and PIPNet19, PIPNet29, PIPNet68, PIPNet98

**Comment by chfeizy** [comment]
对应的模型网盘还没上传呀

**Comment by DefTruth** [comment]
是的，模型会稍后上传。

**Comment by DefTruth** [comment]
已经上传

**Comment by chfeizy** [comment]
辛苦了 试试效果

**Comment by chfeizy** [comment]
faceboxesv2 这个 是一定要 640x640吗
用摄像头会报错num_anchors=0 but detected bbox_num=8525

**Comment by DefTruth** [comment]
不需要啊，接口内部会做resize的，之后输出的会做坐标反算

**Comment by DefTruth** [comment]
目前比较推荐scrfd和yolov5face, 这两个效果比较好

**Comment by chfeizy** [comment]
图片可以运行 摄像头 会报错 看代码 是做resize了，好试下推荐的

**Comment by DefTruth** [comment]
> 图片可以运行 摄像头 会报错 看代码 是做resize了，好试下推荐的

有视频测试的代码吗？我看看能不能检查出问题？

**Comment by DefTruth** [comment]
ok, 我大概知道是哪里出问题了，感谢提醒🤣

**Comment by chfeizy** [comment]
还有点问题 头稍微低点 额头 会识别重叠 但是可以用score排除
