### ISSUE TITLE
关于fp32和fp16的问题

### ISSUE THREAD

**Issue by Jiangjiawei2** [DefTruth/lite.ai.toolkit#244]
现在已成功在cpu上跑通RVM的ONNX,MNN，但是速度还是太慢，在MNN上扣一张图的时间大概在138ms，想进一步提速，于是想试试fp16和int8,看到作者在别的issuse说现在不支持fp16。想请问下，是lite目前不支持fp16，还是MNN目前没有fp16呢，如果可以使用fp16,是否需要仿照大佬自己写推理框架？

**Comment by DefTruth** [comment]
lite目前没有考虑fp16，以后可能会增加fp16的支持，预计是基于MNN和ORT来做。MNN是支持fp16的，可以在MNNConvert阶段通过指定参数--fp16就可以。具体的讨论可以看一下我的另一个回答。

* https://github.com/DefTruth/RobustVideoMatting.lite.ai.toolkit/issues/27

**Comment by DefTruth** [comment]
补充一下：MNN是可以直接加载fp16和int8的模型进行推理的，前后处理逻辑和fp32是一样的，MNN内部做了这种转换的处理，所以mnn_rvm.cpp的代码应该不需要怎么改动，你可以试一下。

**Comment by MatchX** [comment]
mnn转换fp16模型很简单 举个栗子 MNNConvert -f ONNX --modelFile cdfs1116_sim.onnx --MNNModel cdfsout_fp16.mnn --fp16 --bizCode biz 其他和fp32没有区别
