### ISSUE TITLE
VS2019，生成lite.ai.toolkit时报错：MSB307,命令"setlocal

### ISSUE THREAD

**Issue by xmuzyyy** [DefTruth/lite.ai.toolkit#245]
VS2019，生成lite.ai.toolkit时报错：MSB307,命令"setlocal，具体如下：
![A报错](https://user-images.githubusercontent.com/90310256/159150963-1ced9e9d-ee96-4aa7-ad22-2318f25b9007.png)

按照网上的建议依次试过以下方法，都不行：
1. 以管理员身份运行VS
2. cmake时，设置的build目录不对的原因（我检查了，确保是正确的。）
3. 属性->生成事件->生成前事件 路径里所有的/都改为\
这里要提一下的是，我在 ->生成后事件 的命令行是空的，我看网上都不是空的，不知道怎么回事，我“在生成中使用”改成“否”，还是不行。

求助T^T 小组四个人弄了两天了都还没好，就差这最后一步了....

**Comment by DefTruth** [comment]
这个问题还是首次见。发现大家在windows下遇到的问题都不同，不太确定你这里的cmake是否有问题。另外一些编译成功的案例和已知问题的解决方案可以参考：  

* #242 
* #207 

windows我确实不太熟悉，基本没怎么用，目前是比较感谢有位同学提供了windows的编译下编译教程，#207 ，所以现在是比较建议用Mac和Linux的版本，windows版本的预编译库可能要到4月份才有时间做了(手上并没有windows的电脑，哭....)

**Comment by DefTruth** [comment]
补充一下: windows下相关度的依赖库，现在是需要拷贝到 `lite.ai.toolkit/lib/windows` 文件夹中，之前是 `lite.ai.toolkit/lib` , 但是最新的lite.ai.toolkit，为了管理不同操作系统的依赖库，修改了依赖库的存放路径，与 #207 里的 `lite.ai.toolkit/lib` 稍有不同。所以如果是通过cmake命令行的方式编译，需要把库放在对应操作系统名称的文件夹内。我在CMakeLists中根据操作系统指定了不同的依赖库文件夹路径

**Comment by xmuzyyy** [comment]
已解决，原来是在某一步中忘记把MNN文件夹导入到工程根目录下了！
现在编译成功了！接下来要怎么办呢？是否有相关教程呀~~

**Comment by DefTruth** [comment]
可以看一下README.md的使用案例，Supported Model Matrix 里面有每一个算法demo使用链接，可以点进去看。
