### ISSUE TITLE
VS2019运行test_lite_rvm.cpp报错

### ISSUE THREAD

**Issue by hanxizai** [DefTruth/lite.ai.toolkit#246]
![QO@J{9976EU B3(7VW6AR1N](https://user-images.githubusercontent.com/92412351/159192269-de20ac80-c2ed-4a06-89ca-0b899cca5957.png)

**Comment by DefTruth** [comment]
需要先把依赖库都拷贝到可执行文件所在的目录。

**Comment by hanxizai** [comment]
> 以下方式可以尝试：
> 
> * 1. 需要先把依赖库都拷贝到可执行文件所在的目录。
> * 2. 并且我感觉你的exe所在的路径不太对，中间多隔了一层MinSizeRel文件夹，会找不到模型和资源文件，因为我假设的测试工程的exe路径是 lite.ai.toolkit/build/lite.ai.toolkit/bin，所以往回跳3层刚好回到项目的根目录，但你这里多了一层MinSizeRel目录，所以还要再跳一层才能找到模型和资源文件;
> * 3. 需要先下载模型文件放到对应的hub文件夹，具体的路径可以看test_lite_rvm.cpp源码
> * 4. 可以修改test_lite_rvm.cpp源码让路径指向你存放模型文件的地方
> * 5. 直接在VS点运行是不行的，因为我是用CLion+CMake来管理代码的，在VS下，你需要按照自己的情况修改上述的地方。
> * 6. 编译通过说明应该编译是没问题，剩下的大概率是依赖库链接和资源文件路径的问题
> * 7. 相关的issue:
>      
>      * [Windows编译成功但是生成的exe报错 #239](https://github.com/DefTruth/lite.ai.toolkit/issues/239)
>      * [windows编译通过但是生成的EXE闪退，怎么解决？ #234](https://github.com/DefTruth/lite.ai.toolkit/issues/234)
>      * [已经生成exe执行文件了，但是报这个错是什么意思啊 #232](https://github.com/DefTruth/lite.ai.toolkit/issues/232)

大佬，我重新链接了lib库然后在控制台运行时报了另外一个 错误，但是我文件的路径是使用的绝对路径 T ^ T
![image](https://user-images.githubusercontent.com/92412351/159199056-73c70dfb-9e63-49e8-a647-8ee9e64215ba.png)

**Comment by Jiangjiawei2** [comment]
你把生成的lite.ai.toolkit.dll.放到exe所在目录试试

**Comment by hanxizai** [comment]
> lite.ai.toolkit.dll

大佬，exe目录里面有这个文件T ^ T

**Comment by hanxizai** [comment]
> 你把生成的lite.ai.toolkit.dll.放到exe所在目录试试

大佬，exe目录里面有这个文件T ^ T

**Comment by DefTruth** [comment]
打开MP4出错，说明opencv的videoio编解码模块不支持MP4，编解码MP4需要用到ffmpeg，你检查一下ffmpeg相关的库看看。  我写有一篇文章是讲opencv和ffmpeg的关系的，你也可以考虑看看，不知道是否有帮助：  
* [🤓opencv+ffmpeg编译打包全解指南](https://zhuanlan.zhihu.com/p/472115312)

**Comment by hanxizai** [comment]
> 打开MP4出错，说明opencv的videoio编解码模块不支持MP4，编解码MP4需要用到ffmpeg，你检查一下ffmpeg相关的库看看。 我写有一篇文章是讲opencv和ffmpeg的关系的，你也可以考虑看看，不知道是否有帮助：
> 
> * [🤓opencv+ffmpeg编译打包全解指南](https://zhuanlan.zhihu.com/p/472115312)

好的，谢谢大佬Thanks♪(･ω･)ﾉ

**Comment by hanxizai** [comment]
> 打开MP4出错，说明opencv的videoio编解码模块不支持MP4，编解码MP4需要用到ffmpeg，你检查一下ffmpeg相关的库看看。 我写有一篇文章是讲opencv和ffmpeg的关系的，你也可以考虑看看，不知道是否有帮助：
> 
> * [🤓opencv+ffmpeg编译打包全解指南](https://zhuanlan.zhihu.com/p/472115312)

大佬，我将OpenCV版本换为3.4.15后程序就可以运行了ヾ(✿ﾟ▽ﾟ)ノ
