### ISSUE TITLE
现在关于抠图的模型就两个，请问作者最近有考虑将Modnet加入进来嘛

### ISSUE THREAD

**Issue by Jiangjiawei2** [DefTruth/lite.ai.toolkit#247]
如题，最近Modnet挺火的，但是我在网上还没有找到C++开源代码。想问下作者最近有将Modnet加入lite的想法嘛

**Comment by DefTruth** [comment]
应该会加进来，应该是4月份吧，需要先看下工程化的难度怎么样。

**Comment by DefTruth** [comment]
ongoing, may merge into main branch some days latter
