### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Lost-little-dinosaur** [DefTruth/lite.ai.toolkit#248]
您好大佬，我想问一下为什么我直接下载完就给我一堆报错呀，我用Clion看的，搞了半天Demo都跑不起来,,,,是不是我太菜了，一直给我出include的问题，cmakelist.txt也一直不对，我直接用您readme里的也不行，，，好难啊

**Comment by DefTruth** [comment]
放一下报错信息？

**Comment by DefTruth** [comment]
你也可以看一下这个mac的使用案例，windows下的配置是类似的，修改一下CMakelists，链接到相关的库。 

* https://github.com/DefTruth/RobustVideoMatting.lite.ai.toolkit

**Comment by Lost-little-dinosaur** [comment]
您好，是这样的，我参考了您给的链接，里面说要预编译动态链接库，然后我点进去也不太看得懂，，，因为我刚学C++，好多东西都不太懂55555
我根据那个编译的方法试了一下，发现会有这样的报错：

![image](https://user-images.githubusercontent.com/82520400/159407917-d7bad6b8-e922-4fa6-a9ae-b6f62c0a971c.png)

然后我用clion和cmake里面的报错是这样的
![image](https://user-images.githubusercontent.com/82520400/159408399-85729b8a-8524-46e9-97ff-2f428584b8ee.png)
就是include的问题，也不知道为什么

**Comment by Lost-little-dinosaur** [comment]
不好意思我啥都不不太懂，，麻烦大佬了55555

**Comment by DefTruth** [comment]
很抱歉，这个开源项目并不打算讲解基础的c++知识，该开源仓库也不是面向c++初学者的项目。使用lite.ai.toolkit之前，您需要具备以下的基础能力：  
* 了解深度学习的应用，包括但不限于目标检测、人脸检测、分割和抠图等等
* 了解通用推理引擎的基本应用，比如onnxruntime、mnn、tnn和ncnn中至少一种
* 有实际的工程经验，至少了解cmake的基础用法和cmakelists的基础语法，并能够阅读CMakeLists.txt
* 熟悉不同操作系统下的编译和链接原理，比如至少要知道mac下的库是不能在windows用的。我给你发的例子，readme已经说的很清楚，只支持mac，但你在windows上跑，这是不可能成功的
* 拥有仔细阅读README、查看相关issue和通过搜索引擎查找资料的能力

所以个人的建议就是，您可以先找一个简单一点的开源demo来跑，因为个人精力有限，平时还需要工作，所以不打算一一展开回答这些基础的工程知识的问题。加油哈~

**Comment by DefTruth** [comment]
windows下的配置，请参考相关issue:  

* #

里面罗列了详细的配置教程，以及相关的issue，lite.ai.toolkit并不原生支持windows。最优体验请使用mac或linux。

**Comment by Lost-little-dinosaur** [comment]
好滴 多谢大佬 我已经将工作转交给团队内会c++的同学 已经给star啦 ！
