### ISSUE TITLE
Windows配置环境

### ISSUE THREAD

**Issue by yuntaoshou** [DefTruth/lite.ai.toolkit#249]
有人在Windows下运行成功了吗？有偿指导一下。

**Comment by Mamba-ZJP** [comment]
你能指导下我不？

**Comment by yuntaoshou** [comment]
有已经配置好的文件需要吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月06日 14:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [DefTruth/lite.ai.toolkit] Windows配置环境 (Issue #249) |

你能指导下我不？

**Comment by Mamba-ZJP** [comment]
好的 发我邮箱？还是怎么？

**Comment by Mamba-ZJP** [comment]
发我邮箱:mamba_zjp@qq.com。感谢

**Comment by yuntaoshou** [comment]
200块钱发给你。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月06日 15:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [DefTruth/lite.ai.toolkit] Windows配置环境 (Issue #249) |

***@***.***。感谢

**Comment by Mamba-ZJP** [comment]
不用了，谢谢。我才整好，可以跑了
