### ISSUE TITLE
MNN异构混合计算运行Vulkan失败

### ISSUE THREAD

**Issue by Pony23333** [DefTruth/lite.ai.toolkit#250]
为了加速移动端的计算，正在考虑适用异构混合计算的方法，正好MNN声称支持这种方法，没有找到别人的例子所以干脆直接自己实现了。目前成功用同一个Interpreter初始化了两个Session，一个跑CPU一个跑Vulkan，但是最后跑Vulkan的跑到了默认的CPU上。

我的问题是，lite.ai.toolkit并没有include到vulkan的部分，请问这部分应该是在哪里实现的呢？MNN吗？看了别人提了类似的问题，但是也没有给出来具体的配置，能不能给一个具体的支持MNN vulkan的方法？

下面是我的例子：

`
// 1. init interpreter
  mnn_interpreter = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromBuffer(res, num));
  
  // 2. init schedule_config
  schedule_config.numThread = (int) num_threads;
  schedule_gpu_config.numThread = (int) num_threads;
  schedule_gpu_config.type = static_cast<MNNForwardType>(MNN_FORWARD_VULKAN);
  MNN::BackendConfig backend_cpu_config;
  MNN::BackendConfig backend_gpu_config;
  backend_gpu_config.precision = MNN::BackendConfig::Precision_High; // default Precision_High
  backend_cpu_config.precision = MNN::BackendConfig::Precision_High; // default Precision_High

  schedule_config.backendConfig = &backend_cpu_config;
  schedule_gpu_config.backendConfig = &backend_gpu_config;
  // 3. create session
  mnn_session = mnn_interpreter->createSession(schedule_config);
  mnn_gpu_session = mnn_interpreter->createSession(schedule_gpu_config);
  // 4. init input tensor
  input_tensor = mnn_interpreter->getSessionInput(mnn_session, nullptr);
  input_gpu_tensor = mnn_interpreter->getSessionInput(mnn_gpu_session, nullptr);
`

**Comment by DefTruth** [comment]
我暂时没有做vulkan的支持，但模型的c++前后处理是一致的，你需要修改一下schedule的配置，并且需要把vulkan的头文件也放在lite.ai.toolkit/include下，以确保能include进来（需要你自己在需要的地方include）。 或者可能是你把带vulkan的头文件的MNN头文件直接替换我这里的头文件(不太确定vulkan的头文件是否会被包含在MNN的头文件的，如果是vulkan版本的MNN的话)。可以参考以下issue:  

* #235

**Comment by Pony23333** [comment]
找到了问题所在，在cmake/lite.ai.toolkit-cmd.cmake文件里，编译MNN时只链接了MNN，而没有其他后端，可以添加MNN_Express和MNN_Vulkan，之后就可以使能异构混合计算了

**Comment by DefTruth** [comment]
赞
