### ISSUE TITLE
请问编译NCNN版本的lite.ai.toolkit出现下面这种错误是怎么回事呀？

### ISSUE THREAD

**Issue by lemonnader** [DefTruth/lite.ai.toolkit#252]
![image](https://user-images.githubusercontent.com/47074357/159855497-ee6c36d7-8866-4fb7-a764-d322892c1259.png)

**Comment by DefTruth** [comment]
你是怎么编译的

**Comment by DefTruth** [comment]
因为现在是默认使用onnxruntime作为必选的推理引擎的，所以onnxruntime是必须要有的，也就是说，只能编onnxruntime+ncnn，需要有onnxruntime的动态库和头文件，然后在 build.sh 中 设置 ENABLE_NCNN=ON
