### ISSUE TITLE
关于RVM抠图细节问题

### ISSUE THREAD

**Issue by Jiangjiawei2** [DefTruth/lite.ai.toolkit#254]
MNN原来的抠图操为：在下采样完成抠图后，再上采样输出，但是这样在高下采样情况会造成锯齿现象。现在想更改为将Mask上采样后，点乘原视频数据。这样的输出就是高分辨率的。但是在改代码时遇到问题，就是怎么样将原始的tensor输入到generate_matting中呢
![1648133349(1)](https://user-images.githubusercontent.com/52107229/159943350-30e60975-1939-4861-8a53-9ce0476a92f5.jpg)
请问作者能指导下吗

**Comment by DefTruth** [comment]
可以考虑一下几种方式：  
* 1. 参考我写的一篇文章，可以导一个高分辨率的静态onnx出来，然后再转MNN，知乎文章在[🔧填坑: RobustVideoMatting(5k+🔥 star)视频抠图静态ONNX模型转换](https://zhuanlan.zhihu.com/p/459088407), 你想要什么样的分辨率，就按照文章里面提到的计算公式来操作，lite.ai.toolkit里面的后处理代码可以复用，但前处理代码你要看一下需不需要修改（一般不需要，因为已经根据模型输入的大小自动计算了）
* 2. 关于output_tensor，我理解你说的应该是将得到alpha值上采样（你说的mask?）. MNN的机制就是device和host，无论怎样都是得先从device拷贝数据到host之后才能用，处理完后，得到一个pha_mat，就是alpha透明度，这就是正常的cv::Mat，你应该是操作这个Mat就可以了，他的值域是[0,1]，你可以看到rvm.cpp里面的代码，应该比较好理解
* 3. 我的另一篇文章有提到一些常见的形态学处理技巧，你也可以试一下，[详细记录MGMatting(CVPR2021) 🔥MNN、TNN和ONNXRuntime C++移植（长文警告!）](https://zhuanlan.zhihu.com/p/442949027)

**Comment by Jiangjiawei2** [comment]
感谢作者的耐心回复，之前已经通过知乎文章学会了怎么转MNN模型，方案i之前已经实现了，就是速度比较慢。所以想到将alpha上采样，再乘以原始数据的方式得到最终输出。可以保持低分辨率输入快速推理的优点，同时得到高分辨率的输出。
     但是目前代码看了一天多，关于数据处理这部分还是理不清楚，而且我是在Release模式编译，生成dll文件后，无法进入到函数内部设置断点调试。具体问题就是在mnn_rvm.cpp中。当使用
cv::VideoCapture video_capture(video_path);
cv::Mat mat;
video_capture.read(mat)
这三行代码得到原始视频数据的mat后，怎么操作才能把mat变成一个符合generate_matting输入形式的tensor呢。我理解了在第ii点中作者说的需要从device拷贝数据到host之后才能用。下图红框中应该就是拷贝数据使用的过程。
![1648179533(1)](https://user-images.githubusercontent.com/52107229/160049645-008a9d8f-b639-4528-9dc0-e0ceee56ded2.jpg)
目前我想做的是把原始的mat也输入到generate_matting中，再与上采样的pha操作得到merge。
![1648180362(1)](https://user-images.githubusercontent.com/52107229/160051039-a506d635-58bc-4bc4-b864-ab9bf6b1097d.jpg)
我看到在源代码中，是通过
this->transform(mat_rs);
mnn_interpreter->runSession(mnn_session);
auto output_tensors = mnn_interpreter->getSessionOutputAll(mnn_session);
这三步得到output_tensors的，那么我是否可以这样写
this->transform(mat);
mnn_interpreter->runSession(mnn_session);
auto ori_tensors = mnn_interpreter->getSessionOutputAll(mnn_session);
得到一个ori_tensors,再把他传入generate_matting呢。
