### ISSUE TITLE
请问如何查看rvm每帧抠图需要的时间

### ISSUE THREAD

**Issue by hanxizai** [DefTruth/lite.ai.toolkit#255]

**Comment by DefTruth** [comment]
需要你自己在接口外部测试一下

**Comment by hanxizai** [comment]
> 需要你自己在接口外部测试一下
噢噢好的，谢谢大佬。请问修改合成背景需要修改哪部分的代码((유∀유|||))

**Comment by DefTruth** [comment]
以下这个示例工程有一些相关的讨论，你可以查看一下里面的issue:

* https://github.com/DefTruth/RobustVideoMatting.lite.ai.toolkit/issues
