### ISSUE TITLE
使用GPU编译rvm报错

### ISSUE THREAD

**Issue by hanxizai** [DefTruth/lite.ai.toolkit#257]
我使用的是官方编译的onnxruntime-1.9.0-gpu版本cudnn是11.4版本
![image](https://user-images.githubusercontent.com/92412351/160224816-59b617ab-73bc-4dbd-82e8-c23f69702906.png)

**Comment by hanxizai** [comment]
我也查看了issue中的相关问题，但是没有解决

**Comment by DefTruth** [comment]
你重复引用了2份头文件导致类型重定义，lite.ai.toolkit/onnxruntime中就有一份头文件，然后你这又从你下载的onnxruntime中引用了另一份头文件。可能是你头文件路径设置不太对吧，可以参考: #207 的做法。或者考虑使用mac或linux的预编译库，因为我手上没有windows系统的电脑，对windows也不熟悉，所以可能比较难解决你的问题。

**Comment by hanxizai** [comment]
> 你重复引用了2份头文件导致类型重定义，lite.ai.toolkit/onnxruntime中就有一份头文件，然后你这又从你下载的onnxruntime中引用了另一份头文件。可能是你头文件路径设置不太对吧，可以参考: #207 的做法。或者考虑使用mac或linux的预编译库，因为我手上没有windows系统的电脑，对windows也不熟悉，所以可能比较难解决你的问题。

谢谢大佬，每次都麻烦你，编译好了但是GPU使用率不高

**Comment by hanxizai** [comment]
> > 你重复引用了2份头文件导致类型重定义，lite.ai.toolkit/onnxruntime中就有一份头文件，然后你这又从你下载的onnxruntime中引用了另一份头文件。可能是你头文件路径设置不太对吧，可以参考: #207 的做法。或者考虑使用mac或linux的预编译库，因为我手上没有windows系统的电脑，对windows也不熟悉，所以可能比较难解决你的问题。
> 
> 谢谢大佬，每次都麻烦你，编译好了但是GPU使用率不高

GPU使用率才百分之几，但是CPU使用率确很大，是我有地方又配置出错了嘛
