### ISSUE TITLE
[Workflows]: Need CI for Windows/Linux/MacOS Building

### ISSUE THREAD

**Issue by Baiyuetribe** [DefTruth/lite.ai.toolkit#258]
[DefTruth](https://github.com/DefTruth)作者由于精力有限，觉得window编译需要真实设备，导致该项目window预编译非常困难。#48 

希望新增GitHub Action自动化解决该问题。
可参考的案例： https://gist.github.com/NickNaso/0d478f1481686d5bcc868cac06620a60
案例实现了C++项目自动编译windows、macos、linux等

**Comment by DefTruth** [comment]
感谢~😂  不过没有真实设备测试过的话，很难确保workflow能跑通.... 主要还是有依赖库的问题。这个项目我肯定是会维护下去的，希望对各位同学有所帮助 ~ 只是什么时候能捏比较完整的各个平台的预编译库，只能是有个大致的规划，但具体的时间这个是没法确定的。大家可以把lite.ai.toolkit当做一个推理引擎的案例库来用，可以参考某些算法的前后处理等等。
