### ISSUE TITLE
请问一下，yolov5 支持5.0版本吗？

### ISSUE THREAD

**Issue by LudwigHugoL** [DefTruth/lite.ai.toolkit#26]

**Comment by DefTruth** [comment]
@LudwigHugoL 有段时间没有跟进yolov5的情况了。你可以直接使用我这里提供的onnx文件和这里的c++实现。  
[yolov5*.onnx](https://github.com/DefTruth/lite.ai.toolkit/blob/main/docs/hub/lite.ai.toolkit.hub.onnx.md#lite.ai.toolkit.hub.onnx-object-detection)  
关于如何转换onnx文件，可以参考这份工程化记录 [ort_yolov5.zh.md)](https://github.com/DefTruth/lite.ai.toolkit/blob/main/docs/ort/ort_yolov5.zh.md)  
希望对你有所帮助~
