### ISSUE TITLE
onnx怎么转mnn

### ISSUE THREAD

**Issue by MatchX** [DefTruth/lite.ai.toolkit#263]
我看作者的yolov5l.onnx 输出是四个 名称分别为 pred outpu2 outpu3 outpu4 TNN模型也是如此 但是 我看MNN的模型yolov5l.mnn 却只有一个输出 pred 而且我看代码 后处理都是只计算了pred输出的数据
1.请问你这个mnn模型是怎么生成的?
2.为何后处理只计算pred输出的数据?

**Comment by DefTruth** [comment]
outpu2 outpu3 outpu4是冗余的中间张量，只有pred是有用的。转换工程可以看一下我的记录文档：
* https://github.com/DefTruth/lite.ai.toolkit/blob/main/docs/ort/ort_yolov5.zh.md

**Comment by MatchX** [comment]
> outpu2 outpu3 outpu4是冗余的中间张量，只有pred是有用的。转换工程可以看一下我的记录文档：
> 
> * https://github.com/DefTruth/lite.ai.toolkit/blob/main/docs/ort/ort_yolov5.zh.md

好的 谢谢指导 我还有个问题请教 在BasicMNNHandler::initialize_handler中 会调用batch channel height等几个函数 获取模型的输入维度信息 我这都失败了 调试显示dim里 没有任何数据 batch函数去返回dim[0]时 就崩溃了 我这用MNN是1.2.0 模型用的是你上传的网盘的模型 我试了nanodet和retinaface等模型 都不能获得维度信息
