### ISSUE TITLE
请问基于ONNXRuntime的YOLOP速度何如？CPU下会比python快吗？

### ISSUE THREAD

**Issue by RangeLiu** [DefTruth/lite.ai.toolkit#266]

**Comment by DefTruth** [comment]
如果都是使用onnxruntime做推理，速度并不一定会更快，因为python版本的onnxruntime实际上只是通过pybind11给c++的动态库做了一层wrapper，本质上都是调用到了c++的库。所以你的场景不需要用到c++，那我比较推荐使用python版本的onnxruntime或onnxruntime-gpu就可以了

**Comment by RangeLiu** [comment]
> 如果都是使用onnxruntime做推理，速度并不一定会更快，因为python版本的onnxruntime实际上只是通过pybind11给c++的动态库做了一层wrapper，本质上都是调用到了c++的库。所以你的场景不需要用到c++，那我比较推荐使用python版本的onnxruntime或onnxruntime-gpu就可以了

明白了，谢谢回复。
