### ISSUE TITLE
deeplabv3 with mobilenet?

### ISSUE THREAD

**Issue by antithing** [DefTruth/lite.ai.toolkit#267]
Hi, thank you for including deeplabv3_resnet101_coco.onyx model, do you have the mobilenet or resnet50 version of deeplabv3 as well?

Thank you!

**Comment by DefTruth** [comment]
sorry, i am not focus on instance segmentation now, but the version v0.1.2 of lite.ai.toolkit is ongoing, so, any advices are welcome ~ I may pay some attentions to some advices, but guarantee all the advices will be come true

**Comment by antithing** [comment]
Okay thank you! Would it be possible for me to convert a pytorch model to onyx?
