### ISSUE TITLE
Ubuntu 16.04 编译问题

### ISSUE THREAD

**Issue by yangzhegithub** [DefTruth/lite.ai.toolkit#27]
opencv，onnxruntime 已按照指引编译配置妥当，但是运行sh ./build.sh出现这样的错误：
![1](https://user-images.githubusercontent.com/25588020/135226180-05e3f166-a497-4951-b19e-c906193d3cf4.png)
![2](https://user-images.githubusercontent.com/25588020/135226223-033683dd-3b0c-436c-a3a6-848dacacba7e.png)
大佬抽空看看。或者给个详细教程，哈哈

**Comment by DefTruth** [comment]
@yangzhegithub 可能是编译器设置需要做一些修改，可以参考：  
https://stackoverflow.com/questions/55458487/stdexpf-and-stdlogf-not-recognized-by-gcc-7-2-0  
最近应该会放出linux下编译的binary和镜像

**Comment by yangzhegithub** [comment]
ok, 继续调试下。
