### ISSUE TITLE
命令行运行报错

### ISSUE THREAD

**Issue by hanxizai** [DefTruth/lite.ai.toolkit#270]

**Comment by hanxizai** [comment]
> ![image](https://user-images.githubusercontent.com/92412351/161534831-512ac6bf-78b2-44ca-8e13-2ef1fddd86c0.png)
![image](https://user-images.githubusercontent.com/92412351/161538780-4182ce2a-d83d-46aa-886d-a8660e6162d3.png)

**Comment by hanxizai** [comment]
> 提示是出现函数或宏重定义，你看下是否在设置include头文件出现了问题

好的大佬，已经解决了头文件的问题但是现在报操作符的错误，难道是我源码的错误吗
![image](https://user-images.githubusercontent.com/92412351/161656329-54c9cec1-9901-4e1e-ae89-4c3ce658c79b.png)

**Comment by DefTruth** [comment]
不要用命令行直接编，因为工程比较复杂，需要用到cmake，你这样是编不过的，可以先了解一下cmake和cmakelists的用法，windows下请参考: 
* #207

**Comment by hanxizai** [comment]
> 不要用命令行直接编，因为工程比较复杂，需要用到cmake，你这样是编不过的，可以先了解一下cmake和cmakelists的用法，windows下请参考:
> 
> * [🔥Windows10  VS2019  CUDA 11.1 配置lite.ai.toolkit库 #207](https://github.com/DefTruth/lite.ai.toolkit/issues/207)

所以我只能在VS2019中编译生成.exe文件使用吗
