### ISSUE TITLE
Linux Build Error

### ISSUE THREAD

**Issue by AthanatiusC** [DefTruth/lite.ai.toolkit#271]
I got this error while building in Linux:

```
/usr/bin/ld: cannot find -lopencv_core
/usr/bin/ld: cannot find -lopencv_imgproc
/usr/bin/ld: cannot find -lopencv_imgcodecs
/usr/bin/ld: cannot find -lopencv_video
/usr/bin/ld: cannot find -lopencv_videoio
/usr/bin/ld: cannot find -lonnxruntime
collect2: error: ld returned 1 exit status
```

Please help! thanks!

**Comment by DefTruth** [comment]
you need to prepare all the third party deps libs your self, such as opencv with ffmpeg, onnxruntime, also need NCNN/MNN/TNN if you need to build those version of lite.ai.toolkit. please check README for more details. I have already provide some prebuilt libs of lite.ai.toolkit for linux with onnxruntime support.

**Comment by DefTruth** [comment]
### Linux and Windows.

⚠️ **Lite.Ai.ToolKit** is not directly support Linux and Windows now. For Linux and Windows, you need to build or download(if have official builts) the shared libs of **OpenCV**、**ONNXRuntime** and any other Engines(like MNN, NCNN, TNN) firstly, then put the headers into the specific directories or just let these directories unchange(use the headers offer by this repo, the header file of the dependent library of this project is directly copied from the corresponding official library). However, the dynamic libraries under different operating systems need to be recompiled or downloaded. MacOS users can directly use the dynamic libraries of each dependent library provided by this project:
* **lite.ai.toolkit/opencv2**
  ```shell
    cp -r you-path-to-downloaded-or-built-opencv/include/opencv4/opencv2 lite.ai.toolkit/opencv2
  ```
* **lite.ai.toolkit/onnxruntime**
  ```shell
    cp -r you-path-to-downloaded-or-built-onnxruntime/include/onnxruntime lite.ai.toolkit/onnxruntime
  ```
* **lite.ai.toolkit/MNN**
  ```shell
    cp -r you-path-to-downloaded-or-built-MNN/include/MNN lite.ai.toolkit/MNN
  ```
* **lite.ai.toolkit/ncnn**
  ```shell
    cp -r you-path-to-downloaded-or-built-ncnn/include/ncnn lite.ai.toolkit/ncnn
  ```
* **lite.ai.toolkit/tnn**
  ```shell
    cp -r you-path-to-downloaded-or-built-TNN/include/tnn lite.ai.toolkit/tnn
  ```

and put the libs into **lite.ai.toolkit/lib/(linux|windows)** directory. Please reference the build-docs[<sup>1</sup>](#lite.ai.toolkit-1) for **third_party**.
* **lite.ai.toolkit/lib/(linux|windows)**
  ```shell
    cp you-path-to-downloaded-or-built-opencv/lib/*opencv* lite.ai.toolkit/lib/(linux|windows)/
    cp you-path-to-downloaded-or-built-onnxruntime/lib/*onnxruntime* lite.ai.toolkit/lib/(linux|windows)/
    cp you-path-to-downloaded-or-built-MNN/lib/*MNN* lite.ai.toolkit/lib/(linux|windows)/
    cp you-path-to-downloaded-or-built-ncnn/lib/*ncnn* lite.ai.toolkit/lib/(linux|windows)/
    cp you-path-to-downloaded-or-built-TNN/lib/*TNN* lite.ai.toolkit/lib/(linux|windows)/
  ```

Note, your also need to install ffmpeg(<=4.2.2) in Linux to support the opencv videoio module. See [issue#203](https://github.com/DefTruth/lite.ai.toolkit/issues/6). In MacOS, ffmpeg4.2.2 was been package into lite.ai.toolkit, thus, no installation need in OSX. In Windows, ffmpeg was been package into opencv dll prebuilt by the team of opencv. Please make sure -DWITH_FFMPEG=ON and check the configuration info when building opencv.
* first, build ffmpeg(<=4.2.2) from source.
```shell
git clone --depth=1 https://git.ffmpeg.org/ffmpeg.git -b n4.2.2
cd ffmpeg
./configure --enable-shared --disable-x86asm --prefix=/usr/local/opt/ffmpeg --disable-static
make -j8
make install
```
* then, build opencv with -DWITH_FFMPEG=ON, just like
```shell
#!/bin/bash

mkdir build
cd build

cmake .. \
  -D CMAKE_BUILD_TYPE=Release \
  -D CMAKE_INSTALL_PREFIX=your-path-to-custom-dir \
  -D BUILD_TESTS=OFF \
  -D BUILD_PERF_TESTS=OFF \
  -D BUILD_opencv_python3=OFF \
  -D BUILD_opencv_python2=OFF \
  -D BUILD_SHARED_LIBS=ON \
  -D BUILD_opencv_apps=OFF \
  -D WITH_FFMPEG=ON 
  
make -j8
make install
cd ..
```
after built opencv, you can follow the steps to build lite.ai.toolkit.

* Windows: You can reference to [issue#6](https://github.com/DefTruth/lite.ai.toolkit/issues/6)
* Linux: The Docs and Docker image for Linux will be coming soon ~ [issue#2](https://github.com/DefTruth/lite.ai.toolkit/issues/2)
* Happy News !!! : 🚀 You can download the latest **ONNXRuntime** official built libs of Windows, Linux, MacOS and Arm !!! Both CPU and GPU versions are available. No more attentions needed pay to build it from source. Download the official built libs from [v1.8.1](https://github.com/microsoft/onnxruntime/releases). I have used version 1.7.0 for Lite.Ai.ToolKit now, you can download it from [v1.7.0](https://github.com/microsoft/onnxruntime/releases/tag/v1.7.0), but version 1.8.1 should also work, I guess ~  🙃🤪🍀. For **OpenCV**, try to build from source(Linux) or down load the official built(Windows) from [OpenCV 4.5.3](https://github.com/opencv/opencv/releases). Then put the includes and libs into specific directory of Lite.Ai.ToolKit.

* GPU Compatibility for Windows: See [issue#10](https://github.com/DefTruth/lite.ai.toolkit/issues/10).
* GPU Compatibility for Linux: See [issue#97](https://github.com/DefTruth/lite.ai.toolkit/issues/97).

**Comment by DefTruth** [comment]
also, you can download the linux prebuilt libs from [releases](https://github.com/DefTruth/lite.ai.toolkit/releases), and, then, reuse the opencv, ffpmeg and onnxruntime prebuilt libs provided by lite.ai.toolkit

**Comment by AthanatiusC** [comment]
hello, i have already built the minimal dependency like OpenCV and OnnxRuntime, copied all the libs and turned off NCNN/MNN/TNN support in CMAKE (e.g enable ncnn engine), i also have tried copy the prebuult libs and copied them into lite.ai.toolkit libs. 

I dont know why but it seems like CMAKE does not link lite.ai.toolkit/libs when building..

**Comment by DefTruth** [comment]
hi~ you may need to  put the libs into `lite.ai.toolkit/lib/linux` directory, not `lite.ai.toolkit/lib`. the CMakeLists.txt provided by lite.ai.toolkit will auto detect your linux os and the point the library link to `lite.ai.toolkit/lib/linux` dir.

**Comment by AthanatiusC** [comment]
Ah i see!! Thank you very much!! I will try to rebuilt it.

**Comment by AthanatiusC** [comment]
Hello, i am sorry for re commenting on closed issue, but can i please ask for help?
i got error while building the example project, the lite.ai.toolkit is already successfully built but i still got this error:

```
[build]      Creating library E:/Work/c++/fafnir/build/Debug/lite_yolov5.lib and object E:/Work/c++/fafnir/build/Debug/lite_yolov5.exp
[build] MSVCRTD.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ) [E:\Work\c++\fafnir\build\lite_yolov5.vcxproj]
[build] E:\Work\c++\fafnir\build\Debug\lite_yolov5.exe : fatal error LNK1120: 1 unresolved externals [E:\Work\c++\fafnir\build\lite_yolov5.vcxproj]
``` 

My cmake :
```
set(LITE_AI_DIR E:/Work/c++/lite.ai.toolkit/build/lite.ai.toolkit)
include_directories(${LITE_AI_DIR}/include)
link_directories(${LITE_AI_DIR}/lib/MinSizeRel)
link_directories(E:/Work/c++/lite.ai.toolkit/lib/windows)
set(TOOLKIT_LIBS lite.ai.toolkit onnxruntime)
set(OpenCV_LIBS opencv_core455 opencv_imgcodecs455 opencv_imgproc455 opencv_video455 opencv_videoio455)

add_executable(lite_yolov5 test.cpp)
target_link_libraries(lite_yolov5 ${TOOLKIT_LIBS} ${OpenCV_LIBS})
```

**Comment by DefTruth** [comment]
opencv in windows is a singleton lib, not have split libs like opencv in mac and linux.

**Comment by AthanatiusC** [comment]
which means, i have to combine all the libs into single folder?

**Comment by DefTruth** [comment]
not sure. opencv lib in windows is named like opencv_worldxxx.dll ? you may need to link this dll. I'm not familiar with Windows OS.

**Comment by DefTruth** [comment]
![image](https://user-images.githubusercontent.com/31974251/162564789-0f1089f4-61db-43e3-8413-87a0e94422d6.png)

See #207

**Comment by AthanatiusC** [comment]
Ah i see!
thank you i will try it again!

**Comment by quocnhat** [comment]
"cp you-path-to-downloaded-or-built-ncnn/lib/*ncnn* lite.ai.toolkit/lib/(linux|windows)/"
Hi, there is no ncnn/lib folder after build ncnn. How to find that lib. Thank you
