### ISSUE TITLE
MNN模型获取输入维度信息直接崩溃

### ISSUE THREAD

**Issue by MatchX** [DefTruth/lite.ai.toolkit#274]
在BasicMNNHandler::initialize_handler中 会调用batch() channel() height()等几个函数 获取模型的输入维度信息 我这都失败了 调试显示dim里 没有任何数据 batch函数去返回dim[0]时 就崩溃了 我这用MNN是1.2.0 模型用的是你上传的网盘的模型 我试了nanodet和retinaface等模型 都不能获得维度信息 请问是是哪里的问题呢？

**Comment by DefTruth** [comment]
有详细的报错信息吗？

**Comment by MatchX** [comment]
> 有详细的报错信息吗？

没有报错信息 直接崩溃 
![image](https://user-images.githubusercontent.com/10858194/161932844-f5a5bf94-f0aa-4ef6-be46-6a32c85b322a.png)
函数执行到这里 mBuffer.dim是个空指针

**Comment by MatchX** [comment]
@DefTruth

**Comment by DefTruth** [comment]
我测试的时候mnn的模型都是正常的，你是怎么测试的？有代码吗？这样我似乎也没办法知道具体是出什么问题

**Comment by MatchX** [comment]
> 我测试的时候mnn的模型都是正常的，你是怎么测试的？有代码吗？这样我似乎也没办法知道具体是出什么问题

代码如下 在win10 用vs2019运行 MNN是1.2.0 @DefTruth：
MNN::ScheduleConfig scheduleconfig;
scheduleconfig.numThread = 2;
MNN::BackendConfig backendConfig;
backendConfig.precision = MNN::BackendConfig::PrecisionMode::Precision_Normal;
backendConfig.memory = MNN::BackendConfig::Memory_High;
scheduleconfig.backendConfig = &backendConfig;
scheduleconfig.type = MNN_FORWARD_CPU;

auto m_Interpreter = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(
"./models/mnn/nanodet-plus-m_416.mnn"));

auto m_Session = m_Interpreter->createSession(scheduleconfig);
auto m_inputTensor = m_Interpreter->getSessionInput(m_Session, nullptr);
std::shared_ptr<MNN::Tensor>inputUser(new MNN::Tensor(m_inputTensor, MNN::Tensor::CAFFE));
int bpp = inputUser->channel();
int size_w = inputUser->width();
int size_h = inputUser->height();

**Comment by MatchX** [comment]
> 我在mac和Linux测试时正常的。你确认下模型是否被加载进去？我用的也是MNN 1.2.0， inputUser似乎没有被初始化？没被初始化是读不到维度的。

我也在Linux上测试了 确实没有问题 一切正常 看来这个是因为在windows上的mnn库确实不能获取模型的输入维度信息 @DefTruth

**Comment by DefTruth** [comment]
这也可能跟编译器相关的，linux和mac上g++和clang在编译时会做一些优化，能把一些可能导致内存泄露的问题进行内联编译，而msvc则不一定会，它会对用户的要求更严格。所以有时候Linux能运行，但是windows却不能运行。你的inputUser变量这种写法我不太确定是否规范，因为你new了一个tensor指向m_inputTensor，但是没有执行类似copyFromXXX的操作来填充张量，你可以查一下。另外就是，如果你直接通过m_inputTensor->channel()能获取维度，而通过inputUser->channel()却不行，那应该就是写法有问题，你可以从这个角度考虑一下，仅是个人建议。
