### ISSUE TITLE
请问一下windows,onnxruntime条件下生成的exe文件，怎么设置去输出视频的alpha吗

### ISSUE THREAD

**Issue by 1034456901** [DefTruth/lite.ai.toolkit#279]
![image](https://user-images.githubusercontent.com/78294109/162946952-3f365d99-a10c-464e-b725-c2e32ca300c4.png)
![image](https://user-images.githubusercontent.com/78294109/162947079-1efe01cb-d01f-424a-be6d-7294e28975e9.png)
现在视频可以正常分割，现在需求的是视频的alpha输出，应该去怎么修改源码呢，求助

**Comment by DefTruth** [comment]
你可以看一下demo的用法啊，结果里面就有pha_mat(alpha)的了：
* https://github.com/DefTruth/lite.ai.toolkit/blob/main/examples/lite/cv/test_lite_rvm.cpp  

以及可以看一下一个示例工程:

* https://github.com/DefTruth/RobustVideoMatting.lite.ai.toolkit

**Comment by S0ngJX** [comment]
你好，我也想问一下这个问题，我看了一下视频处理的逻辑（detect_video（）），似乎是分帧，然后调用detect进行图片处理（this->detect(mat, content, downsample_ratio, true);）再用video_writer.write合成，请问是这样的吗，如果是的话为什么我修改了代码之后生成的还是前景合成视频呢，我把detect_video中174行代码修改成了这个：
![image](https://user-images.githubusercontent.com/102271216/163100295-4504267d-f194-4fd8-85e8-c87ccac596de.png)

**Comment by S0ngJX** [comment]
作者你好，我也有相似的问题，我看了detect_vide()的代码之后，其实视频分割就是逐帧调用图片分割detect处理的吧？然后用video_writer.write合成，我修改了detect_vide()174行的代码如下后，为什么生成的还是前景合成视频呢？
![image](https://user-images.githubusercontent.com/102271216/163103312-d195d1de-b78c-4880-b224-2a4b837789ea.png)

**Comment by DefTruth** [comment]
最新的代码已经增加了输入新的背景进行合成，请查看示例：

* https://github.com/DefTruth/lite.ai.toolkit/blob/main/examples/lite/cv/test_lite_rvm.cpp
