### ISSUE TITLE
PicoDet support!

### ISSUE THREAD

**Issue by Baxulio** [DefTruth/lite.ai.toolkit#280]
Hi there! 
Thanks to all contributors for this excellent project. I really appreciate what you do guys. 

I want to ask is there any possibility to add PicoDet([for more information](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.4/configs/picodet)) object detector support to the project? It's much faster than NanoDet, and more accurate. Also that would enhance the project's portfolio and make the project more valuable. 

Here is a working project with onnx models:
https://github.com/hpc203/picodet-onnxruntime

P.S. Also want to note that this guy (https://github.com/hpc203) knowns what he does and has good projects. That would be great to add his projects to the toolkit, and if possible add him to contributors list. Thanks!

**Comment by DefTruth** [comment]
may support some days later ~

**Comment by DefTruth** [comment]
也可以先参考我写的这篇文章添加模型：
* [💡如何在lite.ai.toolkit(1.5k+ 🔥stars)中增加您的模型？](https://zhuanlan.zhihu.com/p/523876625)

**Comment by DefTruth** [comment]
Sorry ~ I have been busy lately ~ I may not have time to try this model
