### ISSUE TITLE
有人试过intel的openvino吗

### ISSUE THREAD

**Issue by tonyye2018** [DefTruth/lite.ai.toolkit#288]
我参照cuda的使用方法：
  OrtOpenVINOProviderOptions options;
  options.device_type = "GPU_FP32";
  options.device_id = "";
  options.num_of_threads = 8;
  options.use_compiled_network = false;
  options.blob_dump_path = "";
  options.enable_opencl_throttling = false;
  //session_options.AppendExecutionProvider_OpenVINO(options);

  std::string settings_str;
  settings_str.append("CPU_FP32");
  OrtSessionOptionsAppendExecutionProvider_OpenVINO(session_options, settings_str.c_str());
这两种方法都在执行
ort_session = new Ort::Session(ort_env, onnx_path, session_options);
的时候崩溃了

**Comment by cvDFT** [comment]
openvino官方有指南
