### ISSUE TITLE
我使用了官方编译好的linux链接库，但是在执行链接的时候出现libopencv_videoio.so: undefined reference to，请问这个该怎么解决

### ISSUE THREAD

**Issue by ztrong-forever** [DefTruth/lite.ai.toolkit#294]
![image](https://user-images.githubusercontent.com/62659186/167236922-101044ec-fe0e-4c52-ae6d-5a86af90934f.png)

**Comment by DefTruth** [comment]
建议使用CMake并按照README的说明配置好环境变量，具体用法可以参考Linux下的编译和集成文档：  
* [Linux.zh.md](https://github.com/DefTruth/lite.ai.toolkit/blob/main/docs/build/Linux.zh.md)
