### ISSUE TITLE
最近很火的动物毛发抠图，能否集成进来？

### ISSUE THREAD

**Issue by Baiyuetribe** [DefTruth/lite.ai.toolkit#298]
https://github.com/JizhiziLi/GFM

**Comment by DefTruth** [comment]
LGTM~

**Comment by DefTruth** [comment]
也可以先参考我写的这篇文章添加模型：
* [💡如何在lite.ai.toolkit(1.5k+ 🔥stars)中增加您的模型？](https://zhuanlan.zhihu.com/p/523876625)

**Comment by DefTruth** [comment]
Sorry ~ I have been busy lately ~ I may not have time to try this model
