### ISSUE TITLE
在win10上怎么部署、测试？

### ISSUE THREAD

**Issue by gitqinxinyu** [DefTruth/lite.ai.toolkit#3]

**Comment by DefTruth** [comment]
还没有时间做Win10的兼容测试，平时工作太忙了，后期会抽时间做好兼容。目前主要考虑兼容MacOS和Linux，最近会计划放出一个linux的镜像。在Win10下，你需要编译opencv和onnxruntime的动态库，然后把它们放在third_party文件夹中，并在setup_3rdparty.cmake中设置好你的依赖路径。你可以参考 [这里](https://github.com/DefTruth/lite.ai/tree/main/docs/third_party) 的编译教程来编译opencv和onnxruntime. 或者考虑使用Mac或Linux版本

**Comment by DefTruth** [comment]
可以参考 #6 和 #10

**Comment by meifannao** [comment]
怎么编译opencv和onnxruntime的动态库
