### ISSUE TITLE
solov2在mnn上实现的问题

### ISSUE THREAD

**Issue by Evoluange** [DefTruth/lite.ai.toolkit#302]
您好，我用SOLOv2做实例分割，之前在移动端做ncnn前传框架，C++代码参照
[https://github.com/DayBreak-u/SOLOV2_ncnn](https://github.com/DayBreak-u/SOLOV2_ncnn)
但是目前计划换成MNN做前传，把NCNN代码转换成MNN的C++代码
目前遇到一个问题是
![image](https://user-images.githubusercontent.com/25747262/169192548-e355637f-3571-45cb-ae60-680f5fa00675.png)
输出头在feature_pred做1*1卷积操作得到输出mask，想请教这个操作在MNN下如何用代码实现呢？
是否有实现solov2实例分割的MNN版本呢？

**Comment by DefTruth** [comment]
目前我没有实现过solov2的MNN 版本，这段ncnn的代码应该是调用了ncnn的卷积算子，这个kernel_pred应该像是预测出来的；你可以尝试直接调用MNN的卷积算子做类似操作。

**Comment by anliyuan** [comment]
老哥，这个问题解决了么，可以求一份代码吗？
