### ISSUE TITLE
模型转换问题

### ISSUE THREAD

**Issue by ChaoII** [DefTruth/lite.ai.toolkit#303]
请问一下，很多模型从onnx转ncnn都存在很多困难，请问作者是如何转换的啊？onnx-sim也不好使

**Comment by DefTruth** [comment]
是有这个问题，这个可能和ncnn的设计有关，ncnn::Mat假设batch=1，然后只有h,w,c，三个维度，所以最多只能处理(1,h,w,c)这样的张量。如果你的模型中存在了很多超过4维的张量，或者有很多slices操作.... 是需要手动先去除这些操作才能转换成功的。

**Comment by DefTruth** [comment]
另外，建议可以尝试一下使用nihui大佬的pnnx来做模型转换啊：  

* [PNNX: PyTorch Neural Network Exchange](https://zhuanlan.zhihu.com/p/427620428)
