### ISSUE TITLE
如何转换 photo2cartoon 这个onnx

### ISSUE THREAD

**Issue by lmq5294249** [DefTruth/lite.ai.toolkit#306]
https://github.com/minivision-ai/photo2cartoon
这个卡通化看起来很不错，是否可以将onnx转为ncnn 或 MNN 、TNN model

**Comment by DefTruth** [comment]
也可以先参考我写的这篇文章添加模型：
* [💡如何在lite.ai.toolkit(1.5k+ 🔥stars)中增加您的模型？](https://zhuanlan.zhihu.com/p/523876625)

**Comment by DefTruth** [comment]
已添加，请查看最新代码和README示例
