### ISSUE TITLE
MNN 测试速度

### ISSUE THREAD

**Issue by manguoooneil** [DefTruth/lite.ai.toolkit#307]
你好！我在使用该项目时，在ubuntu18.04平台，转化的mnn模型推理速度，较onnx模型相差了很多（Intel cpu,相同线程）。请问能给一些建议嘛？

**Comment by DefTruth** [comment]
你可以考虑自己编译一个带相应后端推理加速支持的MNN，比如vulkan或cuda，我这里预编译库基本是裸编的，每个人的机子硬件不太一样，你可以看看MNN文档的编译选项。另外就是onnxruntime是针对intel专门做了优化的。
