### ISSUE TITLE
FAN segmentation? 

### ISSUE THREAD

**Issue by antithing** [DefTruth/lite.ai.toolkit#311]
Hi! Thanks again for the awesome library.
Do you plan to add FAN?

https://github.com/NVlabs/FAN

It looks really interesting.

Thanks!

**Comment by DefTruth** [comment]
可以先参考我写的这篇文章添加模型：
* [💡如何在lite.ai.toolkit(1.5k+ 🔥stars)中增加您的模型？](https://zhuanlan.zhihu.com/p/523876625)

**Comment by DefTruth** [comment]
Sorry ~ I have been busy lately ~ I may not have time to try this model
