### ISSUE TITLE
Human Head Segmentation问题

### ISSUE THREAD

**Issue by 205418367** [DefTruth/lite.ai.toolkit#317]
非常感谢您的开源！我今天用MNN跑了一下Human Head Segmentation，发现推理结果存在异常，尝试了多个MNN版本都是如此。我想了解一下是不是我的问题？

**Comment by DefTruth** [comment]
可以贴一下具体的异常和效果吗？我这边跑了样例是正常的

**Comment by 205418367** [comment]
![nwlrbbmqbh](https://user-images.githubusercontent.com/47652945/173318250-efe4fbbd-ea1b-431a-adba-d3a2432feea3.jpg)
1、这与MNN版本有关系吗？
2、你用的是什么版本？
3、我用minivision_head_seg.onnx转MNN模型时会报一些错误。

**Comment by 205418367** [comment]
1、这与MNN版本有关系吗？
2、你用的是什么版本？
3、我用minivision_head_seg.onnx转MNN模型时会报一些错误。
[nwlrbbmqbh.zip](https://github.com/DefTruth/lite.ai.toolkit/files/8889636/nwlrbbmqbh.zip)

**Comment by 205418367** [comment]
这是我的推理代码，看不出什么问题。
[HeadSeg.zip](https://github.com/DefTruth/lite.ai.toolkit/files/8889658/HeadSeg.zip)

**Comment by 205418367** [comment]
好像找到问题了，输出的mask需要顺时针旋转90度，而且结果不太好
![nwlrbbmqbh](https://user-images.githubusercontent.com/47652945/173336624-bac12030-f40e-4e50-ac96-b6d731c560a8.jpg)

**Comment by DefTruth** [comment]
> 1、这与MNN版本有关系吗？ 2、你用的是什么版本？ 3、我用minivision_head_seg.onnx转MNN模型时会报一些错误。 [nwlrbbmqbh.zip](https://github.com/DefTruth/lite.ai.toolkit/files/8889636/nwlrbbmqbh.zip)
我用的是MNN 1.2.0

**Comment by DefTruth** [comment]
我测试的时候用pretreat->convert效果会不太对，我是直接用的内存拷贝的方式。另外，我这里也提供了一个转换后的MNN文件，你可以下载来试试。我不是直接ONNX->MNN的，直接转的模型效果有点问题。我用了tnn-convert做中间处理。过程如下：

```text
*.onnx -> tnn-convert --optimize -> *.opt.onnx -> MNNConvert -> *.mnn
```
