### ISSUE TITLE
Not working under windows 10

### ISSUE THREAD

**Issue by virtualenv** [DefTruth/lite.ai.toolkit#32]
Hello,

I am trying to test it under Windows 10 with Visual Studio 2019.
It compiles fine, but it always gives me the same error :
the application was unable to start correctly 0xc000007b.
Already tried with Release, Debug, MinSizeRel and RelWithDebInfo.
Could you please help me ?

Thank you.

**Comment by DefTruth** [comment]
It seems to be a common problem in windows system, not a bug in this repo.  I think , may be some sys dll is missing or the path of the sys dll is not matched to the environment variable. Also, you can refer to the solution here 👇
* https://www.drivereasy.com/knowledge/how-to-fix-the-application-is-unable-to-start-correctly-0xc00007b-error/      

some other users have already run this repo on the windows system, you can refer to this discussion #10 and #16 , i hope it helps ~

**Comment by virtualenv** [comment]
Thank you DefTruth!
Was really a matter of placing the dlls in the right place!

Congratulations ! Amazing Job!

**Comment by DefTruth** [comment]
> Thank you DefTruth! Was really a matter of placing the dlls in the right place!
> 
> Congratulations ! Amazing Job!

haha~ wish you have a good travel  🙃🤪🍀
