### ISSUE TITLE
看一下这个算法呗

### ISSUE THREAD

**Issue by 205418367** [DefTruth/lite.ai.toolkit#327]
https://github.com/zllrunning/face-parsing.PyTorch
![6](https://user-images.githubusercontent.com/47652945/174938045-245e7dbe-c04c-473b-a8d7-8532f4593d60.jpg)

**Comment by DefTruth** [comment]
LGTM~

**Comment by 205418367** [comment]
已经有人用NCNN实现了～
https://github.com/FeiGeChuanShu/ncnn_MakeupTransfer.git

**Comment by DefTruth** [comment]
added ~
