### ISSUE TITLE
can you share yolov6 parameter file for ncnn onnx mnn tnn？

### ISSUE THREAD

**Issue by lzz144** [DefTruth/lite.ai.toolkit#331]
yolov6s-640x640-for-ncnn.opt.param
yolov6s-640x640-for-ncnn.opt.bin

how can i download？

**Comment by DefTruth** [comment]
you can download these converted NCNN *.param&bin files of YOLOv6 from ([Baidu Drive](https://pan.baidu.com/s/1hlnqyNsFbMseGFWscgVhgQ#list/path=%2F)  code: sc7f), see [NCNN Hub](https://github.com/DefTruth/lite.ai.toolkit/blob/main/docs/hub/lite.ai.toolkit.hub.ncnn.md#object-detection).  Documents about how to convert YOLOv6 to NCNN/MNN/TNN/ONNX formats, please check my zhihu blog:  
* [知乎文章：🤓凑个热闹之 美团 YOLOv6 ORT/MNN/TNN/NCNN C++推理部署](https://zhuanlan.zhihu.com/p/533643238)
