### ISSUE TITLE
Android arm64-v8a TNN 环境 BasicTNNHandler::get_input_data_format(instance, "src") 获取的input_data_format 不对

### ISSUE THREAD

**Issue by Chernobyl81** [DefTruth/lite.ai.toolkit#335]
Hi,  当我在Linux下运行测试程序没有问题，但当我交叉编译到 android环境下，发现`BasicTNNHandler::get_input_data_format(instance, "src") `返回的 input_data_format 是 4（ DATA_FORMAT_NC4HW4），而Linux环境下是正常的 0 (DATA_FORMAT_NCHW)
两个环境下用的都是 `rvm_mobilenetv3_fp32-640-480-sim.opt.tnnproto rvm_mobilenetv3_fp32-640-480-sim.opt.tnnmodel`
请问这是怎么回事？

**Comment by DefTruth** [comment]
这可能是TNN的问题，你可以查一下如何强制设置成NCHW。模型文件本身肯定是一样的，只是应该是TNN在不同的硬件下的默认处理不一样。最近工作比较忙，暂时没有精力将 lite.ai.toolkit 移植到 Arm 上了 ~

**Comment by Chernobyl81** [comment]
Hi, @DefTruth 我直接将BasicTNNHandler::get_input_data_format(instance, "src") 返回设置成 (DATA_FORMAT_NCHW 就可以了，谢谢
