### ISSUE TITLE
.Net5使用cuda错误：Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'.

### ISSUE THREAD

**Issue by wangjp1233** [DefTruth/lite.ai.toolkit#336]
onnxruntime::logging::LoggingManager::DefaultLogger Attempt to use DefaultLogger but none has been registered.

**Comment by DefTruth** [comment]
Sorry ~ I have been busy lately ~ I have not tried using Lite.ai. Toolkit in .NET

**Comment by wangjp1233** [comment]
Thank you for replying to my email. I have solved this problem



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月10日(周日) 下午4:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DefTruth/lite.ai.toolkit] .Net5使用cuda错误：Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'. (Issue #336)




 
Sorry ~ I have been busy lately ~ I have not tried using Lite.ai. Toolkit in .NET

**Comment by wangjp1233** [comment]
Less CUDNN installed



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月10日(周日) 下午4:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DefTruth/lite.ai.toolkit] .Net5使用cuda错误：Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'. (Issue #336)




 
Sorry ~ I have been busy lately ~ I have not tried using Lite.ai. Toolkit in .NET
