### ISSUE TITLE
Yolo5s_face NCNN bug solved ?

### ISSUE THREAD

**Issue by quocnhat** [DefTruth/lite.ai.toolkit#338]
Hi, Have you debugged in [138](https://github.com/DefTruth/lite.ai.toolkit/issues/138) yet?
I test yolo5s-face using ncnn and the bug show as below. How can I solve that, thank you

LITENCNN_DEBUG LogId: ../hub/yolov5sface-opt.param
=============== Input-Dims ==============
Input: input: shape: c=0 h=0 w=0
=============== Output-Dims ==============
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)

**Comment by DefTruth** [comment]
Sorry ~ I am busy recently ~ I may not have time to debug, I recommend you to use the ONNXRuntime or MNN version of YOLO5Face

**Comment by quocnhat** [comment]
I see, Thanks. 
Closing issue now

**Comment by quocnhat** [comment]
Hi @DefTruth , I want to spend time on this bug. May I get some valuable hints on how to debug this error?

**Comment by DefTruth** [comment]
> Hi @DefTruth , I want to spend time on this bug. May I get some valuable hints on how to debug this error?

Here is my document about how to convert YOLO5face to ONNX/NCNN/MNN/TNN formats. Please check: 

* [🍅🍅超准确人脸检测(带关键点)YOLO5Face C++工程详细记录](https://zhuanlan.zhihu.com/p/461878005)
