### ISSUE TITLE
ultraface 怎么去掉nms的多余狂啊

### ISSUE THREAD

**Issue by jinfagang** [DefTruth/lite.ai.toolkit#339]
试了：

```
        face_det.detect(img, face_list, 0.9, 0.6, 30);

```

就跟图上一样，咋个弄啊

**Comment by jinfagang** [comment]
<img width="239" alt="image" src="https://user-images.githubusercontent.com/21303438/179025809-fc16b89c-f3a6-4634-a95d-ea80cbb13073.png">

**Comment by DefTruth** [comment]
非常抱歉~ 最近工作日比较忙，回复的比较晚了... 这比较像NMS没有成功把框给过滤了，可能是IOU阈值设置的太大导致的。我之前倒是没有遇到这种情况，但最近可能没时间来检查这个问题了。或者建议大佬可以试试YOLO5Face或者SCRFD，看看效果是否会有改善

**Comment by DefTruth** [comment]
另一种可能就是如果您是在一段视频中连续调用的话，需要每次都清除掉前一帧的框，因为我在nms中不会做这个清除，所以也有可能是视频流中累计的框导致的。

**Comment by jinfagang** [comment]
解决了，是我不小心注释掉了一行代码😮‍💨
