### ISSUE TITLE
win10运行test_lite_rvm提示应用程序无法正常启动(0xc000007b)

### ISSUE THREAD

**Issue by songjie1100** [DefTruth/lite.ai.toolkit#340]
这边是参照置顶的win10配置并编译完成，已经将三个必要dll文件放在了编译目录，以下是启动提示
和库目录和头目录
![image](https://user-images.githubusercontent.com/51940564/179495021-b1c2b543-d4b6-4bc9-ac56-2d45beff42c0.png)
![image](https://user-images.githubusercontent.com/51940564/179495155-0e1a1750-5207-4dd3-b985-327c50243d9a.png)
![image](https://user-images.githubusercontent.com/51940564/179495275-1c3fb85c-768f-4687-be12-c71e587c89a8.png)
![image](https://user-images.githubusercontent.com/51940564/179495369-345a49b6-76ee-4e35-9951-26b397ced519.png)

**Comment by DefTruth** [comment]
换4.5.2版本的opencv试试？4.5.5的似乎有些问题，另外就是需要将opencv和onnxruntime的动态库也拷贝到exe所在的目录

**Comment by songjie1100** [comment]
> 换4.5.2版本的opencv试试？4.5.5的似乎有些问题，另外就是需要将opencv和onnxruntime的动态库也拷贝到exe所在的目录

好的，我试试

**Comment by jason-sunjiankang** [comment]
我也遇到这个问题了，更换opencv版本没有得到解决

**Comment by DiaosWang** [comment]
@jason-sunjiankang 你好，这个问题你现在解决了吗？  我更换opencv版本也无法解决。

**Comment by DiaosWang** [comment]
> @jason-sunjiankang 你好，这个问题你现在解决了吗？ 我更换opencv版本也无法解决。
我换成opencv4.5.2解决了。
先前在cmd中使用`set path=path-to-dll;%path%`添加这些dll文件的路径到系统路径PATH中，但是运行exe还是报错：`0xc000007b`。
所以借鉴https://github.com/DefTruth/lite.ai.toolkit/issues/6#issuecomment-918721762，将必要的dll文件放在exe同级文件夹下，如下图：
![image](https://github.com/DefTruth/lite.ai.toolkit/assets/47164366/2813c147-46e5-461d-ac65-5d05aa1d92ae)
