### ISSUE TITLE
关于win编译lite.ai.toolkit 几个文件相同的错误：

### ISSUE THREAD

**Issue by zhanghongyong123456** [DefTruth/lite.ai.toolkit#349]
![image](https://user-images.githubusercontent.com/48466610/181903438-3cf8eabf-1210-469c-b74c-30dc1e83b5f6.png)
我想问知道这几个plantid.h 以及 mnn、ncnn、tnn.plantid新增加的吗，出现都是一样的错误，是否是BUG呢，也没发现错误提示所谓的语法错误，期待大佬回复

**Comment by DefTruth** [comment]
可能是win下的一些字符串的问题

**Comment by zhanghongyong123456** [comment]
> 可能是win下的一些字符串的问题

是的，当我更改了win 系统的语言设置 由 中文———> 英文 是可以通过编译的
