### ISSUE TITLE
编译lite.ai.toolkit的整个工程在ubuntu18上，出现如下错误，只贴了一部分  求大佬指点

### ISSUE THREAD

**Issue by bopker** [DefTruth/lite.ai.toolkit#350]
请问可否用arrch64编译呢，这个代码能部署到arm吗
编译时  我只开启了mnn  可以找到 libmnn  但是编译过程中报如下的错

**Comment by bopker** [comment]
![图片](https://user-images.githubusercontent.com/57901697/183787202-43fbac08-0477-4fb7-b31c-669e6044bc7c.png)

**Comment by DefTruth** [comment]
需要同时编译onnxruntime的版本

**Comment by bopker** [comment]
> 需要同时编译onnxruntime的版本

我想问问编译onnxruntime 需要拉取子项目吗
![图片](https://user-images.githubusercontent.com/57901697/184046717-d5a87f1e-d9d5-4db7-951e-4012514a8e22.png)
