### ISSUE TITLE
C++ 17 Exception error 

### ISSUE THREAD

**Issue by shersoni610** [DefTruth/lite.ai.toolkit#351]
Hello,

in ort_utils.h, there is a compilation error on MAC

error: ISO C++17 does not allow dynamic exception specifications [-Wdynamic-exception-spec]
                                               unsigned int data_format = CHW) throw(std::runtime_error);

**Comment by nguyenthuy1681999** [comment]
My solution: 
delete "throw(std::runtime_error)" 
https://rules.sonarsource.com/cpp/RSPEC-2303
