### ISSUE TITLE
YOLO7什么时候支持

### ISSUE THREAD

**Issue by l7518597** [DefTruth/lite.ai.toolkit#354]
如题，YOLO7什么时候支持啊  这个库太好用啦

**Comment by DefTruth** [comment]
最近工作比较忙，可能暂时没时间添加进来。您可以参考一下yolov5,yolov6的实现进行添加

**Comment by DefTruth** [comment]
或者关注 [⚡️PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy)  , 我们最近会release一个新版本，里面提供了yolov7的推理支持

**Comment by l7518597** [comment]
好的 谢谢  还是喜欢lite.ai.tookit

**Comment by ljl123456789ds** [comment]
> 最近工作比较忙，可能暂时没时间添加进来。您可以参考一下yolov5,yolov6的实现进行添加

参考那两个代码他内部回报错，大佬有点难搞

**Comment by CSGO01** [comment]
> 或者关注[⚡️PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy) ，我们最近会发布一个新版本，里面提供了yolov7的推理支持

会出v8吗，还是说你加入了飞桨，不在维护这个项目了
