### ISSUE TITLE
请问有考虑支持 瑞芯微的 RKNN和海思的NNIE吗 

### ISSUE THREAD

**Issue by yukuilong** [DefTruth/lite.ai.toolkit#359]
请问有考虑支持 瑞芯微的 RKNN和海思的NNIE吗

**Comment by DefTruth** [comment]
这个repo暂时没有计划。另外可以关注我们的[PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy) , 应该很快会发新的版本

## 重要通知 (Important Note) !!! 🔥🔥🔥

中文简体：本项目将不再频繁更新，更优的部署体验请尝试[⚡️PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy) : ⚡️一款简单易用的推理部署工具箱。覆盖业界主流优质预训练模型并提供开箱即用的开发体验，包括图像分类、目标检测、图像分割、人脸检测、人体关键点识别、文字识别等多任务，满足开发者多场景，多硬件、多平台的快速部署需求，并同时支持 **C++** 和 **Python** 两种语言。**lite.ai.toolkit** 中的核心模型未来将会以contrib的方式集成到[⚡️PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy) 中。欢迎同学们使用 ✋👉[⚡️PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy).

----

English: This project will no longer be updated frequently. For a better deployment experience, please try [⚡️PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy): ⚡️An Easy-to-use and Fast Deep Learning Model Deployment Toolkit. Covering the industry's mainstream high-quality pre-training models and providing out-of-the-box development experience, including image classification, object detection, image segmentation, face detection, human key point detection, text recognition and so on, to meet the needs of developers in multiple scenarios and multiple hardware, multi-platform deployment requirements. Furthermore, FastDeploy supports both **C++** and **Python** languages. The core models in **lite.ai.toolkit** will be integrated into [⚡️PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy) in a contrib way in the future. Welcome to use ✋👉[⚡️PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy).

----
