### ISSUE TITLE
Yolov5 classification

### ISSUE THREAD

**Issue by sctrueew** [DefTruth/lite.ai.toolkit#363]
Hi,

Is it possible to support [Yolov5-classification](https://github.com/ultralytics/yolov5/pull/8956) models?

Thanks

**Comment by DefTruth** [comment]
Hi @sctrueew  ~ we may consider to support this latest official yolov5 models in [⚡️PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy), would you like to reopen this issue in [FastDeploy](https://github.com/PaddlePaddle/FastDeploy) ?


----

English: This project will no longer be updated frequently. For a better deployment experience, please try [⚡️PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy): ⚡️An Easy-to-use and Fast Deep Learning Model Deployment Toolkit. Covering the industry's mainstream high-quality pre-training models and providing out-of-the-box development experience, including image classification, object detection, image segmentation, face detection, human key point detection, text recognition and so on, to meet the needs of developers in multiple scenarios and multiple hardware, multi-platform deployment requirements. Furthermore, FastDeploy supports both **C++** and **Python** languages. The core models in **lite.ai.toolkit** will be integrated into [⚡️PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy) in a contrib way in the future. Welcome to use ✋👉[⚡️PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy).

----

**Comment by sctrueew** [comment]
That's great. I'll follow FastDeoply
