### ISSUE TITLE
stable-diffusion最近一直霸榜趋势榜，希望大佬能新增c++版

### ISSUE THREAD

**Issue by Baiyuetribe** [DefTruth/lite.ai.toolkit#366]
https://github.com/CompVis/stable-diffusion
![image](https://user-images.githubusercontent.com/43716063/188273099-cd180ed8-52ca-4a32-a151-aa1e0547685e.png)

**Comment by DefTruth** [comment]
可以关注下我们的 [PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy) repo，stable-diffusion近期会在FastDeploy中进行集成
