### ISSUE TITLE
argmax太慢了

### ISSUE THREAD

**Issue by SonwYang** [DefTruth/lite.ai.toolkit#368]
我用repo里面的argmax进行分割后处理，在768*768的图片上，每帧需要花费400ms的时间。各位大佬有没有更快的方法？

**Comment by DefTruth** [comment]
可以关注下我们的 [PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy) repo，更优的部署体验请尝试FastDeploy😎
