### ISSUE TITLE
如何获取多维输出

### ISSUE THREAD

**Issue by dwygs** [DefTruth/lite.ai.toolkit#369]
我的模型是基于热图的姿态检测，模型输出shape是一个张量（1，3，48，64），如果通过直接用指针方式获取，会打乱数据排布后处理就麻烦一些，所以想请教一下onnxruntime能不能直接获取一个tensor，或者可以对结果进行reshape操作

**Comment by DefTruth** [comment]
可以关注下我们的 [PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy) repo，更优的部署体验请尝试FastDeploy😎

**Comment by OroChippw** [comment]
> 我的模型是基于热图的姿态检测，模型输出shape是一个张量（1，3，48，64），如果通过直接用指针方式获取，会打乱数据排布后处理就麻烦一些，所以想请教一下onnxruntime能不能直接获取一个tensor，或者可以对结果进行reshape操作

已经解决 如果获得的输出tensor为masks大小为【1,4,1080，1920】，我们想把它存在一张名为mask的mat里面

‘’‘’
for (unsigned int index = 0 ;  index < 4; index++)
	{
		cv::Mat mask(srcImage.rows, srcImage.cols, CV_8UC1);
		for (unsigned int i = 0; i < mask.rows; i++) 
		{
			for (unsigned int j = 0; j < mask.cols; j++)
			{
				mask.at<uchar>(i, j) = masks[i * mask.cols + j +1920 * 1080] ;
			}
		}
‘’‘’
