### ISSUE TITLE
PipNet access

### ISSUE THREAD

**Issue by kiralygomba** [DefTruth/lite.ai.toolkit#370]
Hello!

Amazing work, thank you! I am using your RetinaFace onnx model and I have already tried a number of facial landmark detectors (mine own and some from you), but I really need the PipNet onnx files. Unfortunately from Europe I cannot download in any way from Baidu. I even tried the free downloaders and registering from a Jordan phonenumber, but no success. Could you upload the PipNet onnx files to Google Drive or add them to docker? Thank you!

**Comment by DefTruth** [comment]
also available at https://github.com/DefTruth/torchlm/releases/tag/torchlm-0.1.6-alpha

**Comment by kiralygomba** [comment]
Thanks. For future reference: what I did was use torchIm's method to convert and create the desired .onnx file (watch out for the parameters to match - backbone, number of landmark...etc.) and I could use that directly in lite.ai.toolkit.
