### ISSUE TITLE
windows版本的64位基于onnxruntime gpu的有人成功跑起来了吗

### ISSUE THREAD

**Issue by chfeizy** [DefTruth/lite.ai.toolkit#372]
目前使用1.11.1不使用cuda直接cpu可以跑起来
开启ENABLE_ONNXRUNTIME_CUDA到了 
auto output_tensors = ort_session->Run(
            Ort::RunOptions{nullptr}, input_node_names.data(),
            input_tensors.data(), num_inputs, output_node_names.data(),
            num_outputs
    );
直接就报错
目前测试的rvm

**Comment by DefTruth** [comment]
关于RVM，我们已经在 [PaddlePaddle/FastDeploy](https://github.com/PaddlePaddle/FastDeploy) 中进行了一版移植，目前支持CPU/GPU/TensorRT推理，另外FastDeploy目前也集成了PaddleSeg的抠图模型和分割模型，你也可以尝试下哈：  
- https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/matting/rvm/python

**Comment by chfeizy** [comment]
[PIPNet](https://github.com/jhb86253817/PIPNet)
还需要PIPNet 这个
