### ISSUE TITLE
请教一个关于c++的问题

### ISSUE THREAD

**Issue by TitansWhale** [DefTruth/lite.ai.toolkit#375]
感谢作者分享，看了作者源码学到很多东西。
在[ort_handler.cpp](https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/core/ort_handler.cpp)
代码的104行中
![image](https://user-images.githubusercontent.com/26743177/209356404-20d349b9-91fe-45ec-bc9f-0e2abf4b42ea.png)
onnx_path 指向了一个临时内存，在离开构造函数之后。_w_onnx_path会被释放掉。会导致onnx_path失效。（作为c++初学者，我想知道我的理解是否有错？）

**Comment by DefTruth** [comment]
这个不影响的，路径也之后在这个构造函数的作用作用域用到，initialize_handler()在这个构造函数的作用域内。
