### ISSUE TITLE
How to obtain KPS from using Retinaface implementation

### ISSUE THREAD

**Issue by cyrusbehr** [DefTruth/lite.ai.toolkit#385]
First of all, thank you for the great work.

I am working off of the retinaface example, however I also require the facial landmarks (which are not extracted in the implementation for some reason). 

I can see that the output at index 2 is the face landmarks, and has shape: 

```
Output: 2 Name: landmarks Dim: 0 :1
Output: 2 Name: landmarks Dim: 1 :31984
Output: 2 Name: landmarks Dim: 2 :10

```

1) How are the landmarks represented. Is it `(x0, x1, x2, x3, x4, y0, y1, y2, y3, y4)` or `(x0, y0, x1, y1, x2, y2, ...)`?
2) Once I have the xy pairs, how do I convert them back to original image reference frame?

**Comment by cyrusbehr** [comment]
I ended up using [this](https://github.com/linghu8812/tensorrt_inference/tree/master/project/RetinaFace) TensorRT implementation and adapting it for onnxruntime (the post processing code is identical).

**Comment by angelabr** [comment]
Hi @cyrusbehr would it be possible to share that part of the code? Thank you
