### ISSUE TITLE
MacOS 下开启 Metal 会崩溃

### ISSUE THREAD

**Issue by xp19870106** [DefTruth/lite.ai.toolkit#386]
在void MNNRobustVideoMatting::initialize_interpreter()中，修改代码，设置Metal，如下
  MNN::BackendConfig backend_config;
  backend_config.precision = MNN::BackendConfig::Precision_High; // default Precision_High
  schedule_config.backendConfig = &backend_config;
  schedule_config.type = MNN_FORWARD_METAL;
  schedule_config.backupType = MNN_FORWARD_METAL;

在执行static void test_mnn()的时候，会崩溃
<img width="1141" alt="截屏2023-05-12 15 23 48" src="https://github.com/DefTruth/lite.ai.toolkit/assets/5085902/0f68d299-232e-42d5-ac79-fcfa2187292b">

请问是否我开在MNN Metal的方式不对

**Comment by DefTruth** [comment]
暂时没有测试过metal哈

**Comment by xp19870106** [comment]
> 暂时没有测试过metal哈

那如果想要开启GPU加速，在Mac下目前是用什么方案呢？

**Comment by LiYufengzz** [comment]
mnn调用非cpu后端的时候，需要使用CopyFromHostTensor来进行tensor的拷贝，否则会出现空指针导致crash
