### ISSUE TITLE
求兼容macOS m1

### ISSUE THREAD

**Issue by Bayson-create** [DefTruth/lite.ai.toolkit#388]
您好，我使用m1芯片MacBook build您的工程文件后，生成的可执行文件，因为无法链接到x86库（我的电脑上都是arm64库，build时也要通过rosetta转译后才能成功），无法成功运行。希望您能够更新整个toolkit对m1的arm64架构进行兼容，谢谢您的理解🌹

**Comment by wangzijian1010** [comment]
> -DCMAKE_SYSTEM_PROCESSOR=x86_64 -DCMAKE_OSX_ARCHITECTURES=x86_64 cmake配置系统x86_64可以跑起来 自己的项目就CMakeLists.txt引入系统的arm库

大佬你好 我也是最近准备在mac m1芯片上准备运行这个代码 你说的解决方法 是在根目录的cmakelist.txt中加吗？ 能否更细致一点呢 谢谢大佬

**Comment by chfeizy** [comment]
我是用的CLion,在cmake里配置
<img width="1013" alt="image" src="https://github.com/DefTruth/lite.ai.toolkit/assets/6427629/697166bd-f9dc-43be-bbf2-63d0ca66e79b">
就可以

**Comment by wangzijian1010** [comment]
> 我是用的CLion,在cmake里配置 <img alt="image" width="1013" src="https://user-images.githubusercontent.com/6427629/255457486-697166bd-f9dc-43be-bbf2-63d0ca66e79b.png"> 就可以
感谢大佬！！！ 谢谢 雀食热心肠

**Comment by chfeizy** [comment]
单独把lite里的代码拿出来，重新cmkelists.txt配置本地的opencv和ffmpeg，还有onnxruntime 也可以的
