### ISSUE TITLE
mnn_rvm.cpp 怎么使用动态分辨率的输入

### ISSUE THREAD

**Issue by sg0771** [DefTruth/lite.ai.toolkit#407]
我将模型的onnx直接转成 mnn模型， 直接从模型读取出来的分辨率是-1， 设置输入分辨率后运行失败

**Comment by emojiLee** [comment]
> 我将模型的onnx直接转成 mnn模型， 直接从模型读取出来的分辨率是-1， 设置输入分辨率后运行失败
你解决动态使用分辨率了么？
