### ISSUE TITLE
未定义引用

### ISSUE THREAD

**Issue by liuzefengi** [DefTruth/lite.ai.toolkit#410]
对‘OrtSessionOptionsAppendExecutionProvider_CUDA’未定义的引用
![Uploading 选区_004.png…]()

**Comment by wangzijian1010** [comment]
你好 你是不是没有开启根目录下CMakelist.txt中的onnxruntime的编译选项 具体代码为
`option(ENABLE_ONNXRUNTIME_CUDA "enable ONNXRuntime engine with CUDA provider" OFF) ` 可以将这个设置为True
