### ISSUE TITLE
你好，在调换为我自己的模型的时候图片的框是对的，但是模型的名字是错的，请问要在哪里修改模型类别的数量和名字呢，谢谢！ 

### ISSUE THREAD

**Issue by linzhuoyingxmu** [DefTruth/lite.ai.toolkit#414]

**Comment by wangzijian1010** [comment]
你好 你用的是那一个算法呢 yolov5吗

**Comment by linzhuoyingxmu** [comment]
yolox-nano

**Comment by DefTruth** [comment]
yolox目前还没有暴露label name给用户修改，可以考虑两种方式：自己按照类别进行匹配，或者修改yolox_v0.1.1.h头文件源码进行替换并重新编译。

https://github.com/DefTruth/lite.ai.toolkit/blob/e72636b58590a05bb1a55872c99ca8b441089862/lite/ort/cv/yolox_v0.1.1.h#L41-L51
