### ISSUE TITLE
VS2019编译时出现下面的错误，请问是什么原因？

### ISSUE THREAD

**Issue by EudicL** [DefTruth/lite.ai.toolkit#429]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2001	无法解析的外部符号 "void __cdecl ortcv::utils::transform::normalize_inplace(class cv::Mat &,float const * const,float const * const)" (?normalize_inplace@transform@utils@ortcv@@YAXAEAVMat@cv@@QEBM1@Z)	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2001	无法解析的外部符号 "struct Ort::Value __cdecl ortcv::utils::transform::create_tensor(class cv::Mat const &,class std::vector<__int64,class std::allocator<__int64> > const &,struct Ort::MemoryInfo const &,class std::vector<float,class std::allocator<float> > &,unsigned int)" (?create_tensor@transform@utils@ortcv@@YA?AUValue@Ort@@AEBVMat@cv@@AEBV?$vector@_JV?$allocator@_J@std@@@std@@AEBUMemoryInfo@5@AEAV?$vector@MV?$allocator@M@std@@@9@I@Z)	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2001	无法解析的外部符号 "class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > __cdecl lite::utils::to_wstring(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?to_wstring@utils@lite@@YA?AV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)

**Comment by wangzijian1010** [comment]
> 严重性 代码 说明 项目 文件 行 禁止显示状态 错误 LNK2001 无法解析的外部符号 "void __cdecl ortcv::utils::transform::normalize_inplace(class cv::Mat &,float const * const,float const * const)" (?normalize_inplace@transform@utils@ortcv@@YAXAEAVMat@cv@@QEBM1@Z)
> 
> 严重性 代码 说明 项目 文件 行 禁止显示状态 错误 LNK2001 无法解析的外部符号 "struct Ort::Value __cdecl ortcv::utils::transform::create_tensor(class cv::Mat const &,class std::vector<__int64,class std::allocator<__int64> > const &,struct Ort::MemoryInfo const &,class std::vector<float,class std::allocator > &,unsigned int)" (?create_tensor@transform@utils@ortcv@@ya?AUValue@Ort@@AEBVMat@cv@@aebv?$vector@_JV?$allocator@_J@std@@@std@@AEBUMemoryInfo@5@AEAV?$vector@MV?$allocator@M@std@@@9@I@Z)
> 
> 严重性 代码 说明 项目 文件 行 禁止显示状态 错误 LNK2001 无法解析的外部符号 "class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > __cdecl lite::utils::to_wstring(class std::basic_string<char,struct std::char_traits,class std::allocator > const &)" (?to_wstring@utils@lite@@ya?AV?$basic_string@_WU?$char_traits@_W@std@@v?$allocator@_W@2@@std@@aebv?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@4@@z)

您好 目前还没支持Windows版本的版本 不过我之前也尝试编译过这种问题一般是onnxruntime没有安装成功等等一系列的环境问题
