### ISSUE TITLE
Is this tool suitable for personal models? or only for open-source models?

### ISSUE THREAD

**Issue by yongqianxiao** [DefTruth/lite.ai.toolkit#443]
Is this tool suitable for personal models, or can it only be used with open-source models? If it can load self-designed models, how can I use it? Could someone please provide some guidance?

**Comment by DefTruth** [comment]
暂时只对某些开源模型做特定的支持。自定义的任意模型，推荐直接使用MNN/ORT/TRT原生API进行推理。

**Comment by yongqianxiao** [comment]
好的，谢谢
