### ISSUE TITLE
测试test_lite_facefusion_pipeline.cpp 和test_lite_face_swap.cpp这两个类的时候报错

### ISSUE THREAD

**Issue by tangzhezhi** [DefTruth/lite.ai.toolkit#447]
报错信息如下：/home/facefusion-onnxrun/python/model_matrix.npy，看了代码应该是您这个依赖是写死的。
但是也没有找到这个依赖模型的下载地址。是否有链接地址提供。
谢谢！

**Comment by tangzhezhi** [comment]
我在facefusion-onnxrun-main\facefusion-onnxrun-main\python目录中找到了。

**Comment by wangzijian1010** [comment]
> 报错信息如下：/home/facefusion-onnxrun/python/model_matrix.npy，看了代码应该是您这个依赖是写死的。 但是也没有找到这个依赖模型的下载地址。是否有链接地址提供。 谢谢！
是的我这个依赖是写死的 我会修复这个问题 谢谢

**Comment by wangzijian1010** [comment]
> > 报错信息如下：/home/facefusion-onnxrun/python/model_matrix.npy，看了代码应该是您这个依赖是写死的。 但是也没有找到这个依赖模型的下载地址。是否有链接地址提供。 谢谢！
> 
> 是的我这个依赖是写死的 我会修复这个问题 谢谢


#448 你好已经修复了 路径的问题
