### ISSUE TITLE
BoundingBoxType的label_text想改成string类型，但是很多报错

### ISSUE THREAD

**Issue by xinsuinizhuan** [DefTruth/lite.ai.toolkit#50]
![图片](https://user-images.githubusercontent.com/40679769/136818409-eefc0287-eea4-47db-b302-641c937b5596.png)

![图片](https://user-images.githubusercontent.com/40679769/136818498-70ca0c4a-d154-48f0-a869-48df9a1f1553.png)

想自己给label_text赋值string，然后发现label_text是为NULL，没法赋值，所以想把label_text改为string

**Comment by DefTruth** [comment]
因为很多模型都用了原来的label_text，直接修改的话会导致不兼容，需要把用到box类的都修改了

**Comment by DefTruth** [comment]
能把onnx文件和你的类别放上来？我尝试帮你改一改？

**Comment by xinsuinizhuan** [comment]
我弄成功了。
![图片](https://user-images.githubusercontent.com/40679769/136887152-d2bfb11b-a5b5-4058-ae47-bf61af23bc07.png)

在析构函数里面再销毁，news的

**Comment by xinsuinizhuan** [comment]
> 
> 
> 优秀~

![图片](https://user-images.githubusercontent.com/40679769/136887840-e8b2c7d1-0687-4666-aecc-8d51bb69cb76.png)
感谢。这样，就初始化的时候，new一次，销毁时销毁掉，不用每次检测的时候，box里面来new和delete

**Comment by xinsuinizhuan** [comment]
你好，原来的析构函数是：
~YoloV5() override = default;
我这样修改后，是不是析构函数不会调用父类BasicOrtHandler中的析构函数，释放资源了？
初始化调用的父类的出初始化，但是析构的时候，没调用父类，父类中创建的new的资源感觉没有释放掉。

**Comment by DefTruth** [comment]
> 你好，原来的析构函数是： ~YoloV5() override = default; 我这样修改后，是不是析构函数不会调用父类BasicOrtHandler中的析构函数，释放资源了？ 初始化调用的父类的出初始化，但是析构的时候，没调用父类，父类中创建的new的资源感觉没有释放掉。

应该会调用父类的析构函数，我之前有测试过。你可以打log看看，或者把这个释放资源的函数改到子类也可以，父类析构时会判断是不是空指针。
