### ISSUE TITLE
demo中，默认模式就是onnxruntime模式？

### ISSUE THREAD

**Issue by xinsuinizhuan** [DefTruth/lite.ai.toolkit#53]

**Comment by DefTruth** [comment]
是的，默认模式是onnxruntime，支持的算子比较多，一般在PC跑性能不错，端上的性能可能不如MNN和NCNN，但也基本够用了。目前这个仓库支持的MNN和NCNN的模型还很少，只有RobustVideoMatting和NanoDet，暂时不建议开启。默认用的推理引擎就是onnxruntime。另外，由于加入了NCNN和MNN支持，新的代码结构有些变动，不过整体和之前的版本差不多，可以看test_lite_xxx.cpp的具体案例。
