### ISSUE TITLE
Using onnxruntime iobinding to eliminate useless transfers

### ISSUE THREAD

**Issue by livingbeams** [DefTruth/lite.ai.toolkit#60]
It would be great to be able to use onnxruntime iobinding to eliminate useless transfers to improve the performance.

For the RobustVideoMatting network the author explains how use the iobinding in python to keep the tensors of the recurrent states in the GPU (avoiding copying them to the CPU and back to the GPU in the next frame):
https://github.com/PeterL1n/RobustVideoMatting/blob/master/documentation/inference.md

I've been looking for information to implement this iobinding in c++ but I couldn't find any reference.

I've figured out how to get the iobinding object from a pointer of the session:
ort_iobinding = new Ort::IoBinding(*ort_session);

To bind the outputs there are to methods:
void BindOutput(const char* name, const Value&);
void BindOutput(const char* name, const MemoryInfo&);

I think the correct way would be to create a MemoryInfo for CUDA device, but not sure if the following way would be correct:
Ort::MemoryInfo info_cuda("Cuda", OrtAllocatorType::OrtArenaAllocator, 0, OrtMemTypeDefault);
for (int i = 0; i < num_outputs; i++) ort_iobinding->BindOutput(output_node_names[i], info_cuda);

To bind the outputs there is only one method:
void BindInput(const char* name, const Value&);

To create the Ort::Value for the "src" input and bind it I think we can do:
Ort::Value srcTensor = Ort::Value::CreateTensor<float>(memory_info_handler, src_values.data(), src_size, src_dims.data(), src_dims.size());
ort_iobinding->BindInput(input_node_names[0], srcTensor);

But I haven't been able to figure out how to create the tensors for the recurrent states as CUDA data.

I've tried the following code putting everything in the CPU just to check it works:

-Once at the begining:
ort_iobinding = new Ort::IoBinding(*ort_session);
for (int i = 0; i < num_outputs; i++) ort_iobinding->BindOutput(output_node_names[i], memory_info_handler);

- Every frame:
Ort::Value srcTensor = Ort::Value::CreateTensor<float>(memory_info_handler, src_values.data(), src_size, src_dims.data(), src_dims.size());
Ort::Value r1iTensor = Ort::Value::CreateTensor<float>(memory_info_handler, r1i_values.data(), r1i_size, r1i_dims.data(), r1i_dims.size());
Ort::Value r2iTensor = Ort::Value::CreateTensor<float>(memory_info_handler, r2i_values.data(), r2i_size, r2i_dims.data(), r2i_dims.size());
Ort::Value r3iTensor = Ort::Value::CreateTensor<float>(memory_info_handler, r3i_values.data(), r3i_size, r3i_dims.data(), r3i_dims.size());
Ort::Value r4iTensor = Ort::Value::CreateTensor<float>(memory_info_handler, r4i_values.data(), r4i_size, r4i_dims.data(), r4i_dims.size());
Ort::Value dsrTensor = Ort::Value::CreateTensor<float>(memory_info_handler, dsr_values.data(), dsr_size, dsr_dims.data(), dsr_dims.size());
ort_iobinding->BindInput(input_node_names[0], srcTensor);
ort_iobinding->BindInput(input_node_names[1], r1iTensor);
ort_iobinding->BindInput(input_node_names[2], r2iTensor);
ort_iobinding->BindInput(input_node_names[3], r3iTensor);
ort_iobinding->BindInput(input_node_names[4], r4iTensor);
ort_iobinding->BindInput(input_node_names[5], dsrTensor);
ort_session->Run(Ort::RunOptions{ nullptr }, *ort_iobinding);
auto output_tensors = ort_iobinding->GetOutputValues();

And it works correctly, but obviously at the same performance. The point would be to figure out how to keep the tensors of the recurrent states always in the GPU memory.

**Comment by zhanghongyong123456** [comment]
> 如果能够使用 onnxruntime iobinding 来消除无用的传输以提高性能，那就太好了。
> 
> 对于 RobustVideoMatting 网络，作者解释了如何使用 python 中的 iobinding 将循环状态的张量保留在 GPU 中（避免将它们复制到 CPU 并在下一帧返回到 GPU）： [https ://github.com/ PeterL1n/RobustVideoMatting/blob/master/documentation/inference.md](https://github.com/PeterL1n/RobustVideoMatting/blob/master/documentation/inference.md)
> 
> 我一直在寻找在 C++ 中实现这个 iobinding 的信息，但我找不到任何参考。
> 
> 我已经弄清楚如何从会话的指针中获取 iobinding 对象： ort_iobinding = new Ort::IoBinding(*ort_session);
> 
> 要将输出绑定到方法： void BindOutput(const char* name, const Value&); void BindOutput(const char* name, const MemoryInfo&);
> 
> 我认为正确的方法是为 CUDA 设备创建 MemoryInfo，但不确定以下方法是否正确： Ort::MemoryInfo info_cuda("Cuda", OrtAllocatorType::OrtArenaAllocator, 0, OrtMemTypeDefault); for (int i = 0; i < num_outputs; i++) ort_iobinding->BindOutput(output_node_names[i], info_cuda);
> 
> 要绑定输出，只有一种方法： void BindInput(const char* name, const Value&);
> 
> 要为“src”输入创建 Ort::Value 并绑定它，我认为我们可以这样做： Ort::Value srcTensor = Ort::Value::CreateTensor(memory_info_handler, src_values.data(), src_size, src_dims.data( ), src_dims.size()); ort_iobinding->BindInput(input_node_names[0], srcTensor);
> 
> 但是我还没有弄清楚如何为循环状态创建张量作为 CUDA 数据。
> 
> 我已经尝试将以下代码放入 CPU 中以检查它是否有效：
> 
> - 开始时一次： ort_iobinding = new Ort::IoBinding(*ort_session); for (int i = 0; i < num_outputs; i++) ort_iobinding->BindOutput(output_node_names[i], memory_info_handler);
> 
> * 每帧：
>   Ort::Value srcTensor = Ort::Value::CreateTensor(memory_info_handler, src_values.data(), src_size, src_dims.data(), src_dims.size()); 
>   Ort::Value r1iTensor = Ort::Value::CreateTensor(memory_info_handler, r1i_values.data(), r1i_size, r1i_dims.data(), r1i_dims.size()); 
>   Ort::Value r2iTensor = Ort::Value::CreateTensor(memory_info_handler, r2i_values.data(), r2i_size, r2i_dims.data(), r2i_dims.size()); 
>   Ort::Value r3iTensor = Ort::Value::CreateTensor(memory_info_handler, r3i_values.data(), r3i_size, r3i_dims.data(), r3i_dims.size()); 
>   Ort::Value r4iTensor = Ort::Value::CreateTensor(memory_info_handler, r4i_values.data(), r4i_size, r4i_dims.data(), r4i_dims.size());
>   Ort::Value dsrTensor = Ort::Value::CreateTensor(memory_info_handler, dsr_values.data(), dsr_size, dsr_dims.data(), dsr_dims.size()); 
>   ort_iobinding->BindInput(input_node_names[0], srcTensor); 
>   ort_iobinding->BindInput(input_node_names[1], r1iTensor); 
>   ort_iobinding->BindInput(input_node_names[2], r2iTensor); 
>   ort_iobinding->BindInput(input_node_names[3], r3iTensor); 
>   ort_iobinding->BindInput(input_node_names[4], r4iTensor); 
>   ort_iobinding->BindInput(input_node_names[5], dsrTensor); 
>   ort_session->Run(Ort::RunOptions{ nullptr }, *ort_iobinding); 
>   auto output_tensors = ort_iobinding->GetOutputValues();
> 
> 它工作正常，但显然具有相同的性能。关键是要弄清楚如何将循环状态的张量始终保留在 GPU 内存中。



> 

请问大佬你这个GPU加速实现了吗
