### ISSUE TITLE
看看这个，挺有意思，集成进来？

### ISSUE THREAD

**Issue by xinsuinizhuan** [DefTruth/lite.ai.toolkit#72]
https://github.com/ibaiGorordo/ONNX-Mobile-Human-Pose-3D

**Comment by DefTruth** [comment]
之后有时间可以玩一下

**Comment by 205418367** [comment]
百度的[PP-TinyPose](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/keypoint/tiny_pose)
[c++实现](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/deploy/cpp)，能否集成进来？

**Comment by DefTruth** [comment]
Sorry ~ I have been busy lately ~ I may not have time to try this model
