### ISSUE TITLE
MG Matting 

### ISSUE THREAD

**Issue by antithing** [DefTruth/lite.ai.toolkit#85]
Hi! Do you have any plans to implement mask guiding matting into this toolkit?

https://github.com/yucornetto/MGMatting

It would be amazing to run it through c++! 

Thanks.

**Comment by DefTruth** [comment]
LGTM

**Comment by antithing** [comment]
Hi again,  sorry to bug you, did you have a chance to look at this? Is it likely to make it into this toolkit?  Thanks again for your amazing work

**Comment by DefTruth** [comment]
Yes, I am really going to try to add this model to the toolkit, but I have been too busy recently. It may be completed after a week or two.

**Comment by antithing** [comment]
Great! Thank you very much

**Comment by DefTruth** [comment]
added
